### ISSUE TITLE
model_training KeyError: 'SM_CHANNEL_TRAIN' and Value at 'nameContains' failed to satisfy constraint when using SageMakerTrainingOperator

### ISSUE THREAD

**Issue by JavierLopezT** [aws/sagemaker-python-sdk#1036]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: XGBoost built-in Algorithm
- **Framework Version**: 0.9-1
- **Python Version**: 3.7.1
- **CPU or GPU**: CPU
- **Python SDK Version**: Airflow 1.10.4, sagemaker 1.38.6, boto3 1.9.224
- **Are you using a custom image**: No

### Describe the problem
Using a SageMakerTrainingOperator in Airflow gives me KeyError: 'SM_CHANNEL_TRAIN'. Once in the sagemaker panel in aws web, I go to training jobs with errors and it says: 

### Minimal repro / logs
 The airflow log is the following 

```
[2019-09-10 13:36:55,372] {base_task_runner.py:115} INFO - Job 317: Subtask model_training [2019-09-10 13:36:55,371] {credentials.py:1182} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2019-09-10 13:36:56,058] {base_task_runner.py:115} INFO - Job 317: Subtask model_training [2019-09-10 13:36:56,058] {cli.py:516} INFO - Running <TaskInstance: retraining_sagemaker.model_training 2019-09-10T13:36:38.058584+00:00 [running]> on host ip-172-31-43-111.eu-west-1.compute.internal
[2019-09-10 13:36:56,074] {sagemaker_base_operator.py:88} INFO - Preprocessing the config and doing required s3_operations
[2019-09-10 13:36:56,090] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:36:56,090[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:36:56,444] {sagemaker_base_operator.py:98} INFO - After preprocessing the config is:
 {
    "AlgorithmSpecification": {
        "TrainingImage": "141502667606.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-xgboost:0.90-1-cpu-py3",
        "TrainingInputMode": "File"
    },
    "HyperParameters": {
        "eval_metric": "error@0.1",
        "num_rounds": "400",
        "objective": "binary:logistic"
    },
    "InputDataConfig": [
        {
            "ChannelName": "training",
            "DataSource": {
                "S3DataSource": {
                    "S3DataDistributionType": "FullyReplicated",
                    "S3DataType": "S3Prefix",
                    "S3Uri": "s3://antifraud/production/data/20190910/vue_com_final_data.csv"
                }
            }
        }
    ],
    "OutputDataConfig": {
        "S3OutputPath": "s3://antifraud/production/models/20190910"
    },
    "ResourceConfig": {
        "InstanceCount": 1,
        "InstanceType": "ml.m4.2xlarge",
        "VolumeSizeInGB": 30
    },
    "RoleArn": "arn:aws:iam::126522147578:role/service-role/AmazonSageMaker-ExecutionRole-20190305T175813",
    "StoppingCondition": {
        "MaxRuntimeInSeconds": 86400
    },
    "TrainingJobName": "sagemaker-xgboost-2019-09-10-13-36-56-040"
}
[2019-09-10 13:36:56,444] {sagemaker_training_operator.py:82} INFO - Creating SageMaker Training Job sagemaker-xgboost-2019-09-10-13-36-56-040.
[2019-09-10 13:36:56,473] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:36:56,472[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:36:56,612] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:36:56,612[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:36:56,716] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:36:56,716[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:36:57,092] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:36:57,092[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:36:57,214] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:36:57,214[0m] {[34msagemaker_hook.py:[0m714} INFO[0m - 2019-09-10 13:36:57 Starting - Starting the training job[0m
[2019-09-10 13:37:27,261] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:37:27,261[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:37:27,322] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:37:27,322[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:37:27,440] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:37:27,440[0m] {[34msagemaker_hook.py:[0m565} INFO[0m - 2019-09-10 13:36:59 Starting - Launching requested ML instances[0m
[2019-09-10 13:37:57,495] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:37:57,494[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:37:57,634] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:37:57,634[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:38:27,802] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:38:27,802[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:38:27,859] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:38:27,859[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:38:27,995] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:38:27,994[0m] {[34msagemaker_hook.py:[0m565} INFO[0m - 2019-09-10 13:38:24 Starting - Preparing the instances for training[0m
[2019-09-10 13:38:58,052] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:38:58,052[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:38:58,121] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:38:58,120[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:39:28,379] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:28,379[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:39:28,438] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:28,438[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:39:28,569] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:28,569[0m] {[34msagemaker_hook.py:[0m565} INFO[0m - 2019-09-10 13:39:11 Downloading - Downloading input data[0m
[2019-09-10 13:39:58,623] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,622[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:39:58,774] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,774[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:39:58,849] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,848[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - 2019-09-10 13:39:50,574 sagemaker-containers INFO     Imported framework sagemaker_xgboost_container.training[0m
[2019-09-10 13:39:58,849] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,849[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - 2019-09-10 13:39:50,575 sagemaker-containers INFO     Failed to parse hyperparameter eval_metric value error@0.1 to Json.[0m
[2019-09-10 13:39:58,849] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,849[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - Returning the value itself[0m
[2019-09-10 13:39:58,849] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,849[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - 2019-09-10 13:39:50,575 sagemaker-containers INFO     Failed to parse hyperparameter objective value binary:logistic to Json.[0m
[2019-09-10 13:39:58,849] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,849[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - Returning the value itself[0m
[2019-09-10 13:39:58,849] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,849[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - 2019-09-10 13:39:50,578 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)[0m
[2019-09-10 13:39:58,850] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,849[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - 2019-09-10 13:39:50,592 sagemaker_xgboost_container.training INFO     Running XGBoost Sagemaker in algorithm mode[0m
[2019-09-10 13:39:58,850] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,850[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - 2019-09-10 13:39:50,596 sagemaker-containers ERROR    Reporting training FAILURE[0m
[2019-09-10 13:39:58,850] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,850[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - 2019-09-10 13:39:50,596 sagemaker-containers ERROR    framework error: [0m
[2019-09-10 13:39:58,850] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,850[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_trainer.py", line 76, in train
    entrypoint()
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 82, in main
    train(framework.training_env())
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 78, in train
    run_algorithm_mode()
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 46, in run_algorithm_mode
    train_path = os.environ[sm_env_constants.SM_CHANNEL_TRAIN]
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None[0m
[2019-09-10 13:39:58,850] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,850[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - KeyError: 'SM_CHANNEL_TRAIN'
[0m
[2019-09-10 13:39:58,850] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,850[0m] {[34msagemaker_hook.py:[0m548} INFO[0m - 'SM_CHANNEL_TRAIN'[0m
[2019-09-10 13:39:58,866] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,866[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:39:58,957] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:58,957[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:39:59,064] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:39:59,064[0m] {[34msagemaker_hook.py:[0m565} INFO[0m - 2019-09-10 13:39:54 Training - Training image download completed. Training in progress.
2019-09-10 13:39:54 Uploading - Uploading generated training model[0m
[2019-09-10 13:40:29,106] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:40:29,106[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:40:29,167] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:40:29,167[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:40:29,339] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:40:29,339[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:40:29,402] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:40:29,402[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:40:29,516] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:40:29,516[0m] {[34msagemaker_hook.py:[0m565} INFO[0m - 2019-09-10 13:39:59 Failed - Training job failed[0m
[2019-09-10 13:40:59,564] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:40:59,564[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:40:59,625] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:40:59,624[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:40:59,719] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:40:59,718[0m] {[34mcredentials.py:[0m1182} INFO[0m - Found credentials in shared credentials file: [1m~/.aws/credentials[0m[0m
[2019-09-10 13:40:59,822] {taskinstance.py:1047} ERROR - Error training sagemaker-xgboost-2019-09-10-13-36-56-040: Failed Reason: AlgorithmError: framework error: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_trainer.py", line 76, in train
    entrypoint()
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 82, in main
    train(framework.training_env())
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 78, in train
    run_algorithm_mode()
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 46, in run_algorithm_mode
    train_path = os.environ[sm_env_constants.SM_CHANNEL_TRAIN]
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'SM_CHANNEL_TRAIN'

'SM_CHANNEL_TRAIN'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/dist-packages/airflow/contrib/operators/sagemaker_training_operator.py", line 89, in execute
    max_ingestion_time=self.max_ingestion_time
  File "/usr/local/lib/python3.7/dist-packages/airflow/contrib/hooks/sagemaker_hook.py", line 352, in create_training_job
    check_interval, max_ingestion_time
  File "/usr/local/lib/python3.7/dist-packages/airflow/contrib/hooks/sagemaker_hook.py", line 767, in check_training_status_with_log
    raise AirflowException('Error training {}: {} Reason: {}'.format(job_name, status, reason))
airflow.exceptions.AirflowException: Error training sagemaker-xgboost-2019-09-10-13-36-56-040: Failed Reason: AlgorithmError: framework error: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_trainer.py", line 76, in train
    entrypoint()
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 82, in main
    train(framework.training_env())
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 78, in train
    run_algorithm_mode()
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 46, in run_algorithm_mode
    train_path = os.environ[sm_env_constants.SM_CHANNEL_TRAIN]
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'SM_CHANNEL_TRAIN'

'SM_CHANNEL_TRAIN'
[2019-09-10 13:40:59,823] {taskinstance.py:1078} INFO - Marking task as FAILED.
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training Traceback (most recent call last):
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/bin/airflow", line 32, in <module>
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     args.func(args)
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.7/dist-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     return f(*args, **kwargs)
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.7/dist-packages/airflow/bin/cli.py", line 522, in run
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     _run(args, dag, ti)
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.7/dist-packages/airflow/bin/cli.py", line 440, in _run
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     pool=args.pool,
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.7/dist-packages/airflow/utils/db.py", line 74, in wrapper
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     return func(*args, **kwargs)
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.7/dist-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     result = task_copy.execute(context=context)
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.7/dist-packages/airflow/contrib/operators/sagemaker_training_operator.py", line 89, in execute
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     max_ingestion_time=self.max_ingestion_time
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.7/dist-packages/airflow/contrib/hooks/sagemaker_hook.py", line 352, in create_training_job
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     check_interval, max_ingestion_time
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.7/dist-packages/airflow/contrib/hooks/sagemaker_hook.py", line 767, in check_training_status_with_log
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     raise AirflowException('Error training {}: {} Reason: {}'.format(job_name, status, reason))
[2019-09-10 13:40:59,835] {base_task_runner.py:115} INFO - Job 317: Subtask model_training airflow.exceptions.AirflowException: Error training sagemaker-xgboost-2019-09-10-13-36-56-040: Failed Reason: AlgorithmError: framework error: 
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training Traceback (most recent call last):
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_trainer.py", line 76, in train
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     entrypoint()
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 82, in main
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     train(framework.training_env())
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 78, in train
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     run_algorithm_mode()
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/local/lib/python3.5/dist-packages/sagemaker_xgboost_container/training.py", line 46, in run_algorithm_mode
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     train_path = os.environ[sm_env_constants.SM_CHANNEL_TRAIN]
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training   File "/usr/lib/python3.5/os.py", line 725, in __getitem__
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training     raise KeyError(key) from None
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training KeyError: 'SM_CHANNEL_TRAIN'
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training 
[2019-09-10 13:40:59,836] {base_task_runner.py:115} INFO - Job 317: Subtask model_training 'SM_CHANNEL_TRAIN'
[2019-09-10 13:41:04,032] {logging_mixin.py:95} INFO - [[34m2019-09-10 13:41:04,031[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
```

The message in SageMaker Panel is:
![Screen Shot 2019-09-10 at 4 54 57 PM](https://user-images.githubusercontent.com/11339132/64624994-c2c55b80-d3eb-11e9-9c9c-0a9d5d82d23a.png)

Attached can be found a pice of the data

[vue_com_aws.csv.zip](https://github.com/aws/sagemaker-python-sdk/files/3596305/vue_com_aws.csv.zip)

- **Exact command to reproduce**:

My dag is the following:

```
from airflow import DAG
from airflow.contrib.operators.sagemaker_training_operator import SageMakerTrainingOperator
from airflow.operators.dummy_operator import DummyOperator
from sagemaker.workflow.airflow import training_config
import sagemaker
from sagemaker.amazon.amazon_estimator import get_image_uri
import datetime as dt
from datetime import timedelta, datetime
import boto3

today = datetime.today().strftime('%Y%m%d')

default_args = {
        'owner': 'airflow',
        'start_date': dt.datetime(2019,8,28,18,0,0),
        'concurrency':1,
        'retries':0
        }

with DAG('retraining_sagemaker',
         default_args=default_args,
         schedule_interval = timedelta(days=1)
         ) as dag:

    start = DummyOperator(
            task_id = 'start')
    
    container = get_image_uri(boto3.Session().region_name,
                          'xgboost', 
                          repo_version='0.90-1')
    estimator = sagemaker.estimator.Estimator(container, 
                                              role = 'AmazonSageMaker-ExecutionRole-20190305T1758XXX',
                                              train_instance_count = 1,
                                              train_instance_type = 'ml.m4.2xlarge',
                                              output_path = f's3://antifraud/production/models/{today}',
                                              hyperparameters = {'num_rounds':400,
                                                                 'objective':'binary:logistic',
                                                                 'eval_metric':'error@0.1'})
    
    train_config = training_config(estimator=estimator,
                                   inputs = f's3://datrapalo-antifraud/production/data/{today}/vue_com_final_data.csv')
    
    model_training = SageMakerTrainingOperator(
            task_id = 'model_training',
            config = train_config,
            wait_for_completion = True)
    
start >>  model_training
```
Other dags and tasks within the same DAG are working properly. For further information, I have successfully trained models with that data in the notebooks.

**Comment by laurenyu** [comment]
I've reached out to the team that owns XGBoost to see if they have any insight. Thanks for your patience!

**Comment by aws-patlin** [comment]
Hi Javier,

I noticed in your InputDataConfig, you have ChannelName set to "training". Can you try setting this to "train" instead? Let me know if this resolves your issue!

**Comment by JavierLopezT** [comment]
Hello, I solved it using s3_input objects:
s3_input_train = sagemaker.s3_input(s3_data='s3://antifraud/production/data/{domain}-{product}-{today}/train_data.csv',
                                        content_type='text/csv')
    s3_input_validation = sagemaker.s3_input(s3_data='s3://antifraud/production/data/{domain}-{product}-{today}/validation_data.csv',
                                        content_type='text/csv')
    
   train_config = training_config(estimator=estimator,
                                   inputs = {'train':s3_input_train,
                                             'validation':s3_input_validation})

Thank you very much for your support

**Comment by aws-patlin** [comment]
Glad to hear you were able to find a solution! Yes, our documentation is less than adequate currently, and we are actively working to improve it. Thanks for your feedback!

**Comment by warner121** [comment]
I came across the same issue while following the tutorial. For me the issue was with the following line, as I had followed the suggestion in the terminal and upgraded the repo version.

`container = get_image_uri(boto3.Session().region_name,
                          'xgboost', 
                          repo_version='0.90-1')`

Simply removing the repo_version argument got it working.

**Comment by mchusma** [comment]
We also have been unable to get repo_version working. Just removing that makes it run.
