### ISSUE TITLE
Endpoint failure when the  MXNetmodel is created with source_dir and the script not at root

### ISSUE THREAD

**Issue by anotinelg** [aws/sagemaker-python-sdk#1059]
**System Information**

Python Version: 3.6
sagemaker-python-sdk Version: master (1.42.1.dev0)
sagemaker-mxnet-serving-container: 1.1.4.dev0)  (using sagemkaer-infernece 1.0.1)
Are you using a custom image: no

**Describe the problem**

I am trying to deploy a model with a script which is located inside a source directory in a subdirectory. The model is successfully created, but When the model is started, the script is not found by the code of the sagemaker-mxnet-inference-serving (master)

My source directory is:

```
- src
---- mypackage
--------__init__.py
--------myscript.py
--------utils.py
```

I create the model as:
```
MXNetModel( entry_point='mypackage/myscript.py',
                         source_dir= './src'
                         ...       
                         py_version='py3')
```

The output.tar.gz is the following:
```
- model/
---- my model.params
---- ...
---- code / 
--------------mypackage
-------------------__init__.py
-------------------myscript.py
-------------------utils.py
```

Nota that the myscript.py is not copied to the code directory. 

looking into the code, I was surprised about that line:
https://github.com/aws/sagemaker-python-sdk/blob/67f90120f6432a2cb3dfe95f5fc59d1f606e607e/src/sagemaker/model.py#L806

how it is supposed to locate the code if we only take the basename? or is copy of the file to the root is missing? 

My suggestion is to not use os.path.basename when we have the condition 
`is_mms=True` and we provided a source_dir to create the MXNetModel

Note: this seems to work when myscript.py is located at the root of the src/ directory.
```
- src
---- mypackage
--------__init__.py
--------utils.py
-----myscript.py

```

Anexe:
I add the log of the server when it fails to find my script:
```
2019-09-23 16:12:41,539 [INFO ] main com.amazonaws.ml.mms.ModelServer -
MMS Home: /usr/local/lib/python3.6/site-packages
Current directory: /
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 1
Max heap size: 1844 M
Python executable: /usr/local/bin/python3.6
Config file: /etc/sagemaker-mms.properties
Inference address: http://0.0.0.0:8080
Management address: http://127.0.0.1:8081
Model Store: /.sagemaker/mms/models
Initial Models: ALL
Log dir: /logs
Metrics dir: /logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
2019-09-23 16:12:41,587 [INFO ] main com.amazonaws.ml.mms.wlm.ModelManager - Model model loaded.
2019-09-23 16:12:41,602 [INFO ] main com.amazonaws.ml.mms.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2019-09-23 16:12:41,672 [INFO ] main com.amazonaws.ml.mms.ModelServer - Inference API bind to: http://0.0.0.0:8080
2019-09-23 16:12:41,672 [INFO ] main com.amazonaws.ml.mms.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2019-09-23 16:12:41,672 [INFO ] main com.amazonaws.ml.mms.ModelServer - Management API bind to: http://127.0.0.1:8081
Model server started.
2019-09-23 16:12:41,677 [WARN ] pool-2-thread-1 com.amazonaws.ml.mms.metrics.MetricCollector - worker pid is not available yet.
2019-09-23 16:12:41,704 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9000
2019-09-23 16:12:41,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]56
2019-09-23 16:12:41,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2019-09-23 16:12:41,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.8
2019-09-23 16:12:41,708 [INFO ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9000
2019-09-23 16:12:41,716 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9000.
2019-09-23 16:12:42,518 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Backend worker process die.
2019-09-23 16:12:42,518 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Traceback (most recent call last):
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_service_worker.py", line 172, in <module>
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - worker.run_server()
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_service_worker.py", line 150, in run_server
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - self.handle_connection(cl_socket)
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_service_worker.py", line 116, in handle_connection
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - service, result, code = self.load_model(msg)
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_service_worker.py", line 96, in load_model
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_loader.py", line 134, in load
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - model_service = model_class()
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/sagemaker_mxnet_serving_container/handler_service.py", line 40, in __init__
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - super(HandlerService, self).__init__(transformer=self._user_module_transformer())
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/sagemaker_mxnet_serving_container/handler_service.py", line 44, in _user_module_transformer
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - user_module = importlib.import_module(environment.Environment().module_name)
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - return _bootstrap._gcd_import(name[level:], package, level)
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'myscript'
```

**Comment by anotinelg** [comment]
I update the ticket adding the log of the server which fails to import the myscript.py

```
2019-09-23 16:12:41,539 [INFO ] main com.amazonaws.ml.mms.ModelServer -
MMS Home: /usr/local/lib/python3.6/site-packages
Current directory: /
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 1
Max heap size: 1844 M
Python executable: /usr/local/bin/python3.6
Config file: /etc/sagemaker-mms.properties
Inference address: http://0.0.0.0:8080
Management address: http://127.0.0.1:8081
Model Store: /.sagemaker/mms/models
Initial Models: ALL
Log dir: /logs
Metrics dir: /logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
2019-09-23 16:12:41,587 [INFO ] main com.amazonaws.ml.mms.wlm.ModelManager - Model model loaded.
2019-09-23 16:12:41,602 [INFO ] main com.amazonaws.ml.mms.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2019-09-23 16:12:41,672 [INFO ] main com.amazonaws.ml.mms.ModelServer - Inference API bind to: http://0.0.0.0:8080
2019-09-23 16:12:41,672 [INFO ] main com.amazonaws.ml.mms.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2019-09-23 16:12:41,672 [INFO ] main com.amazonaws.ml.mms.ModelServer - Management API bind to: http://127.0.0.1:8081
Model server started.
2019-09-23 16:12:41,677 [WARN ] pool-2-thread-1 com.amazonaws.ml.mms.metrics.MetricCollector - worker pid is not available yet.
2019-09-23 16:12:41,704 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9000
2019-09-23 16:12:41,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]56
2019-09-23 16:12:41,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2019-09-23 16:12:41,705 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.8
2019-09-23 16:12:41,708 [INFO ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9000
2019-09-23 16:12:41,716 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9000.
2019-09-23 16:12:42,518 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Backend worker process die.
2019-09-23 16:12:42,518 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Traceback (most recent call last):
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_service_worker.py", line 172, in <module>
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - worker.run_server()
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_service_worker.py", line 150, in run_server
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - self.handle_connection(cl_socket)
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_service_worker.py", line 116, in handle_connection
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - service, result, code = self.load_model(msg)
2019-09-23 16:12:42,519 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_service_worker.py", line 96, in load_model
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/model_loader.py", line 134, in load
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - model_service = model_class()
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/sagemaker_mxnet_serving_container/handler_service.py", line 40, in __init__
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - super(HandlerService, self).__init__(transformer=self._user_module_transformer())
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/sagemaker_mxnet_serving_container/handler_service.py", line 44, in _user_module_transformer
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - user_module = importlib.import_module(environment.Environment().module_name)
2019-09-23 16:12:42,520 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - return _bootstrap._gcd_import(name[level:], package, level)
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
2019-09-23 16:12:42,521 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'myscript'
```

**Comment by mvsusp** [comment]
Hi @anotinelg ,

Did you try the following instead:

```python
MXNetModel( entry_point='myscript.py',
                         source_dir= './src/mypackage'
                         ...       
                         py_version='py3')
```

The source directory must be the root folder to be imported properly by the MXNet serving container.

Thanks for using SageMaker!

**Comment by laurenyu** [comment]
closing due to inactivity. feel free to reopen if necessary.

**Comment by analyticsrepo1** [comment]
still an issue 
how do i import "MXNetModel" 

in
xnet_model = MXNetModel(model_data='s3://my_bucket/pretrained_model/model.tar.gz',
                         role=role,
                         entry_point='inference.py',
                         framework_version='1.6.0',
                         py_version='py3')

**Comment by laurenyu** [comment]
@analyticsrepo1 

```python
from sagemaker.mxnet import MXNetModel
```

if you encounter further issues, I'd suggest opening a new issue!
