### ISSUE TITLE
Sagmeker-local mode-file not found on windows

### ISSUE THREAD

**Issue by Ritika-a** [aws/sagemaker-python-sdk#1139]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: MXNet Object Detection
- **Framework Version**: Latest
- **Python Version**: 3.6
- **CPU or GPU**: CPU 
- **Python SDK Version**: sagemaker-1.44.3
- **Are you using a custom image**: No- Using the Object Detection image from saegmaker

### Describe the problem
I am trying to run the object detection algorithm on sagemaker locally. Everything works fine, until I try and train the model. However, an error is produced at this stage. 

### Minimal repro / logs

training_image = get_image_uri(sess.boto_region_name, 'object-detection', repo_version="latest")
s3_output_location = 's3://{}/{}/output'.format(bucket, prefix)
od_model = sagemaker.estimator.Estimator(
                                         training_image, 
                                         role=role,
                                         train_instance_count=1, 
                                         train_instance_type='local',
                                        # train_volume_size = 5,
                                         train_max_run = 60,
                                         #input_mode = 'File',
                                         output_path=s3_output_location
                                         )

od_model.set_hyperparameters(base_network='resnet-50',
                             use_pretrained_model=1,
                             num_classes=5,
                             mini_batch_size=1,
                             epochs=1,
                             learning_rate=0.001,
                             optimizer='sgd',
                             momentum=0.9,
                             weight_decay=0.0005,
                             overlap_threshold=0.5,
                             nms_threshold=0.45,
                             image_shape=512,
                             label_width=600,
                             num_training_samples=3)

train_channel = prefix + '/train'
validation_channel = prefix + '/validation'
train_annotation_channel = prefix + '/train_annotation'
validation_annotation_channel = prefix + '/validation_annotation'

s3_train_data = 's3://{}/{}'.format(bucket, train_channel)
s3_validation_data = 's3://{}/{}'.format(bucket, validation_channel)
s3_train_annotation = 's3://{}/{}'.format(bucket, train_annotation_channel)
s3_validation_annotation = 's3://{}/{}'.format(bucket, validation_annotation_channel)

train_data = sagemaker.session.s3_input(s3_train_data, distribution='FullyReplicated', 
                        content_type='image/jpeg', s3_data_type='S3Prefix')
validation_data = sagemaker.session.s3_input(s3_validation_data, distribution='FullyReplicated', 
                             content_type='image/jpeg', s3_data_type='S3Prefix')
train_annotation = sagemaker.session.s3_input(s3_train_annotation, distribution='FullyReplicated', 
                             content_type='image/jpeg', s3_data_type='S3Prefix')
validation_annotation = sagemaker.session.s3_input(s3_validation_annotation, distribution='FullyReplicated', 
                             content_type='image/jpeg', s3_data_type='S3Prefix')
data_channels = {'train': train_data, 'validation': validation_data, 
                 'train_annotation': train_annotation, 'validation_annotation':validation_annotation}

od_model.fit(inputs=data_channels)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sagemaker\estimator.py", line 339, in fit
    self.latest_training_job = _TrainingJob.start_new(self, inputs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sagemaker\estimator.py", line 863, in start_new
    estimator.sagemaker_session.train(**train_args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sagemaker\session.py", line 394, in train
    ):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sagemaker\local\local_session.py", line 107, in create_training_job
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sagemaker\local\entities.py", line 96, in start
    input_data_config, output_data_config, hyperparameters, job_name
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sagemaker\local\image.py", line 150, in train
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sagemaker\local\image.py", line 812, in _ecr_login_if_needed
    sagemaker_match = sagemaker_pattern.match(image)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\sagemaker\local\image.py", line 684, in _check_output
    if isinstance(cmd, str):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

- **Exact command to reproduce**:
od_model.fit(inputs=data_channels)

**Comment by laurenyu** [comment]
@Ritika-a Local Mode is not supported for Amazon algorithms such as Object Detection. You will need to run your training job on SageMaker.

Local Mode docs: https://sagemaker.readthedocs.io/en/stable/overview.html#local-mode

**Comment by Ritika-a** [comment]
Thank you so much! However, it says that local Mode is supported for frameworks images (TensorFlow, MXNet, Chainer, PyTorch, and Scikit-Learn) and images you supply yourself. -- Would this mean it just includes your own algorithms which are written in these frameworks?

**Comment by laurenyu** [comment]
That is correct. The Amazon-implemented algorithms (e.g. Object Detection, KMeans, RandomCutForest), while they use MXNet under the hood, are not supported for Local Mode.
