### ISSUE TITLE
Multiple files not supported if not executed through notebook?

### ISSUE THREAD

**Issue by OktayGardener** [aws/sagemaker-python-sdk#116]
Hello.

I am currently facing the following problem:

I have built my own service for building, deploying and serving ML models using Sagemaker in production, and I am very much trying to make this work without using notebooks. 

I just encountered the following problem, and it seems like I am not able to simply use `entry_point=modelclass.py` in order to train a model that **imports from other local files**.

I was trying to recreate the [Cifar10 with Tensorboard example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_resnet_cifar10_with_tensorboard/tensorflow_resnet_cifar10_with_tensorboard.ipynb) in amazon-sagemaker-examples, but I got the following error, when using "resnet_cifar_10" as the entry_point for the `Tensorflow` `Estimator`:

```
ValueError: Error training cifar10-tensorflow-train-2018-04-01-23-14: Failed Reason: AlgorithmError: uncaught exception during training: No module named resnet_model
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 25, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train.py", line 87, in train
    customer_script = env.import_user_module()
  File "/usr/local/lib/python2.7/dist-packages/container_support/environment.py", line 88, in import_user_module
    user_module = importlib.import_module(script)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/ml/code/resnet_cifar_10.py", line 6, in <module>
    import resnet_model
ImportError: No module named resnet_model
```

By looking at this error, it seems like that if all the necessary code has to be in this file. This eventually gets nicely packaged into a Docker container on SageMaker's working out of the box if I understand it correctly. Is there a way to 'send more' files so the TF model doesn't have to be defined in one .py file conforming to the 5 must implement protocol methods?

**Comment by OktayGardener** [comment]
I just found it. This can be done with the ‘source_dir’ parameter passed to the Tensorflow Estimator object.
