### ISSUE TITLE
Packing a pre-trained model 

### ISSUE THREAD

**Issue by vlordier** [aws/sagemaker-python-sdk#1195]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: PyTorch / Custom
- **Framework Version**: 1.3.1
- **Python Version**: py3 
- **CPU or GPU**: GPU
- **Python SDK Version**:
- **Are you using a custom image**: No

### Describe the problem
On image deployment for inference, a pre-trained model needs to be fetched at first.
This is causing the worker to timeout.

### Minimal repro / logs
```Backend response time: 59933
Number or consecutive unsuccessful inference 1  
Backend worker error   
com.amazonaws.ml.mms.wlm.WorkerInitializationException: Backend worker did not respond in given time   
at com.amazonaws.ml.mms.wlm.WorkerThread.run(WorkerThread.java:150)  
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266)  
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)   
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  
at java.lang.Thread.run(Thread.java:748)  ```


- **Exact command to reproduce**:
Try and run an inference taking some time with a pre-trained model to download.


Question : is there a way to pre-package a pre-trained model into, say, `.cache/torch` as a workaround ?

**Comment by laurenyu** [comment]
You can get the model downloaded into `/opt/ml/model` before the model server starts up by uploading the model to S3 and using the `PyTorchModel` class. Here are a couple examples:

* not PyTorch, but shows downloading a model and uploading it to S3: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_onnx_superresolution/mxnet_onnx.ipynb
* skip down to "Host" to see how `PyTorchModel` is used: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/pytorch_lstm_word_language_model/pytorch_rnn.ipynb

however, if you need the model saved at `.cache/torch`, then we'll need a different approach. can you paste your code? (the inference script and the code used for starting an endpoint)

**Comment by laurenyu** [comment]
closing due to lack of activity.
