### ISSUE TITLE
docutils version conflict w/ boto3

### ISSUE THREAD

**Issue by kaungst** [aws/sagemaker-python-sdk#1227]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: N/A
- **Framework Version**: N/A
- **Python Version**: 3.6.9
- **CPU or GPU**: N/A
- **Python SDK Version**: 1.50.1
- **Are you using a custom image**: Yes

### Describe the problem
Looks like a version conflict w/ docutils. Would bumping requirements fix the issue? Attempting to use 1.49.0 for now

### Minimal repro / logs
Stacktrace
```
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.6/site-packages/sagemaker/__init__.py", line 18, in <module>
    from sagemaker import estimator, parameter, tuner  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/sagemaker/estimator.py", line 29, in <module>
    from sagemaker.analytics import TrainingJobAnalytics
  File "/usr/local/lib/python3.6/site-packages/sagemaker/analytics.py", line 23, in <module>
    from sagemaker.session import Session
  File "/usr/local/lib/python3.6/site-packages/sagemaker/session.py", line 34, in <module>
    from sagemaker.user_agent import prepend_user_agent
  File "/usr/local/lib/python3.6/site-packages/sagemaker/user_agent.py", line 23, in <module>
    SDK_VERSION = pkg_resources.require("sagemaker")[0].version
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (docutils 0.16 (/usr/local/lib/python3.6/site-packages), Requirement.parse('docutils<0.16,>=0.10'), {'botocore'})
```

**Comment by kaungst** [comment]
jk 1.49.0 has an issue w/ requests

**Comment by laurenyu** [comment]
do you have previous installations of docutils/botocore/boto3?

I'm unfortunately unable to reproduce what you're seeing (I created a new virtualenv, did `pip install -U sagemaker`, and was able to `import sagemaker` without issue)

**Comment by laurenyu** [comment]
closing due to lack of activity.
