### ISSUE TITLE
Sagemaker samples give an error for S3 Buckets requiring SSE encryption mode

### ISSUE THREAD

**Issue by jerrygb** [aws/sagemaker-python-sdk#1253]
**Describe the bug**
Trying to run through Sagemaker samples and hit the road block when using S3 Buckets which require objected to be encrypted using SSE.

**To reproduce**
Run the Parameter Server based distributed training in the notebook [here](https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/master/tf-distribution-options/tf-distributed-training.ipynb)

**_Updated class declaration:_**

```
estimator_ps = TensorFlow(
                       git_config=git_config,
                       source_dir='tf-distribution-options/code',
                       entry_point='train_ps.py', 
                       base_job_name='ps-cifar10-tf',
                       role=role,
                       framework_version='1.13',
                       py_version='py3',
                       hyperparameters=hyperparameters,
                       train_instance_count=ps_instance_count, 
                       train_instance_type=ps_instance_type,
                       model_dir=model_dir,
                       tags = [{'Key' : 'Project', 'Value' : 'cifar10'},{'Key' : 'TensorBoard', 'Value' : 'dist'}],
                       distributions=distributions,
                       output_kms_key='arn:aws:kms:us-east-1:yyyyyyy:key/key_id')
```

**Note:** The `output_kms_key` is defined since the policy requires that all objects are encrypted at-rest.

**Expected behavior**
Runs the tensorflow training given train, test and validation datasets and logs the model checkpoints on the S3 using the KMS key provided.

**Screenshots or logs**

Looks like part of the requested training is completed. However, when logging the modal checkpoints it gives an error. I do have access to the S3 bucket from the notebook environment. However, all the objects require to be SSE encrypted in my environment.

```
s/step - loss: 0.9891 - acc: 0.6518 - val_loss: 0.8898 - val_acc: 0.6931
INFO:root:Test loss:0.9299138677425873
INFO:root:Test accuracy:0.6730769276618958
2020-01-21 00:36:52,250 sagemaker_tensorflow_container.training INFO     master algo-1 is down, stopping parameter server
2020-01-21 00:36:52,250 sagemaker_tensorflow_container.training WARNING  Your model will NOT be servable with SageMaker TensorFlow Serving container.The model artifact was not saved in the TensorFlow SavedModel directory structure:
https://www.tensorflow.org/guide/saved_model#structure_of_a_savedmodel_directory
2020-01-21 00:36:52,251 sagemaker-containers INFO     Reporting training SUCCESS
Traceback (most recent call last):
  File "train_ps.py", line 141, in <module>
    main(args)
  File "train_ps.py", line 88, in main
    validation_steps=(num_examples_per_epoch('validation') // args.batch_size) // size, callbacks=callbacks)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 215, in model_iteration
    mode=mode)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 106, in configure_callbacks
    callback_list.set_model(callback_model)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 178, in set_model
    callback.set_model(model)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 1010, in set_model
    self._init_writer()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 947, in _init_writer
    self.writer = tf_summary.FileWriter(self.log_dir, K.get_session().graph)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/summary/writer/writer.py", line 367, in __init__
    filename_suffix)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/summary/writer/event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 442, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 458, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path), status)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AbortedError: All 10 retry attempts failed. The last failure: Unknown: AccessDenied: 1 failed parts. Access Denied
2020-01-21 00:37:28,821 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/usr/local/bin/python3.6 train_ps.py --batch-size 128 --epochs 10 --model_dir /opt/ml/model"

2020-01-21 00:37:36 Uploading - Uploading generated training model
2020-01-21 00:37:36 Failed - Training job failed
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-10-2e1ef825f72c> in <module>()
      1 remote_inputs = {'train' : inputs+'/train', 'validation' : inputs+'/validation', 'eval' : inputs+'/eval'}
----> 2 estimator_ps.fit(remote_inputs, wait=True)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config, run_tensorboard_locally)
    454                 tensorboard.join()
    455         else:
--> 456             fit_super()
    457 
    458     @classmethod

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit_super()
    433 
    434         def fit_super():
--> 435             super(TensorFlow, self).fit(inputs, wait, logs, job_name, experiment_config)
    436 
    437         if run_tensorboard_locally and wait is False:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    462         self.jobs.append(self.latest_training_job)
    463         if wait:
--> 464             self.latest_training_job.wait(logs=logs)
    465 
    466     def _compilation_job_name(self):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1059         # If logs are requested, call logs_for_jobs.
   1060         if logs != "None":
-> 1061             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1062         else:
   1063             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   2972 
   2973         if wait:
-> 2974             self._check_job_status(job_name, description, "TrainingJobStatus")
   2975             if dot:
   2976                 print()

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   2566                 ),
   2567                 allowed_statuses=["Completed", "Stopped"],
-> 2568                 actual_status=status,
   2569             )
   2570 

UnexpectedStatusException: Error for Training job ps-cifar10-tf-2020-01-21-00-32-13-303: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/usr/local/bin/python3.6 train_ps.py --batch-size 128 --epochs 10 --model_dir /opt/ml/model"
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 1.45.0.dev0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Tensorflow
- **Framework version**: 1.13
- **Python version**: 3.6.9
- **CPU or GPU**: GPU 
- **Custom Docker image (Y/N)**: N

**Comment by jerrygb** [comment]
The error was at precisely at logging directory setup by Keras callback. In the example environment/code we had something as shown below,

Environment:

```bash
SM_MODULE_DIR=s3://sagemaker-us-east-1-541676414377/ps-cifar10-tf-2020-01-22-03-17-15-101/source/sourcedir.tar.gz
```

Code:

```python
parser.add_argument('--tensorboard-dir',type=str,default=os.environ.get('SM_MODULE_DIR'))
callbacks.append(CustomTensorBoardCallback(log_dir=tensorboard_dir))
```


Our S3 Buckets requires SSE parameter to be explicitly specified each time, so it failed. Since this particular Callback tries to write to an S3 Bucket without SSE specified, it gave an error. We just need to override the `tensorboard_dir` parameter when initializing the Tensorflow Estimator.
