### ISSUE TITLE
local_gpu with Custom Image

### ISSUE THREAD

**Issue by phidodido** [aws/sagemaker-python-sdk#1259]
**Describe the bug**
Deployment fails when `instance_type='local_gpu'` in `model.deploy(1, instance_type)`.

**To reproduce**
```
model = sagemaker.Model(
    model_data='s3://bucket/mymodel.tar.gz',
    image='dkr.ecr.amazonaws.com/myimage:latest',
    role='MyRole'
)

model.deploy(1, instance_type='local_gpu')
```

**Expected behavior**
- Deployment with CPU works correctly when using `model.deploy(1, instance_type='local')`
- Deployment with GPU works correctly when running directly with docker and `--gpus all` as in `docker run -v $(pwd)/test_dir:/opt/ml -p 8080:8080 --gpus all --rm ${image} serve`

**Screenshots or logs**
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/sagemaker/local/image.py", line 614, in run
    _stream_output(self.process)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/sagemaker/local/image.py", line 673, in _stream_output
    raise RuntimeError("Process exited with code: %s" % exit_code)
RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/sagemaker/local/image.py", line 619, in run
    raise RuntimeError(msg)
RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmpbhgjl0ow/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 1

Traceback (most recent call last):
  File "deploy.py", line 87, in <module>
    run(cfg)
  File "deploy.py", line 27, in run
    instance_type='local_gpu'
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/sagemaker/model.py", line 486, in deploy
    data_capture_config_dict=data_capture_config_dict,
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/sagemaker/session.py", line 2831, in endpoint_from_production_variants
    return self.create_endpoint(endpoint_name=name, config_name=name, tags=tags, wait=wait)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/sagemaker/session.py", line 2360, in create_endpoint
    EndpointName=endpoint_name, EndpointConfigName=config_name, Tags=tags
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/sagemaker/local/local_session.py", line 265, in create_endpoint
    endpoint.serve()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/sagemaker/local/entities.py", line 475, in serve
    _wait_for_serving_container(serving_port)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/sagemaker/local/entities.py", line 510, in _wait_for_serving_container
    raise RuntimeError("Giving up, endpoint didn't launch correctly")
RuntimeError: Giving up, endpoint didn't launch correctly
```

**System information**
- **SageMaker Python SDK version**: 1.50.4
- **Framework name**: PyTorch
- **Framework version**: 1.3.1
- **Python version**: host=3.7, container=3.6.6
- **CPU or GPU**: GPU
- **Custom Docker image**: Yes based on [PyTorch image](https://github.com/aws/sagemaker-pytorch-container/blob/master/docker/1.3.1/py3/Dockerfile.gpu) and [Scikit example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/container/Dockerfile)

**Comment by laurenyu** [comment]
sorry for the lack of response here. could you post the container logs as well?

**Comment by phidodido** [comment]
I have found the reason for the error. `nvidia-docker2` was not set up correctly.

**Comment by mathephysicist** [comment]
How did you set it up correctly?

**Comment by phidodido** [comment]
I redid the instructions from https://github.com/NVIDIA/nvidia-docker
Likely I forgot to restart docker the first time.
