### ISSUE TITLE
ClientError: Data download failed:Insufficient disk space

### ISSUE THREAD

**Issue by samuelhkahn** [aws/sagemaker-python-sdk#128]
Regardless of what flavor p2 instance I spin-up, I am getting an insufficient disk space error. This is puzzling as this happens with a  `ml.p2.16xlarge`, `ml.p2.8xlarge` & `ml.p2.xlarge`.  Given that the total data I am putting on the instances is less than `70 G`, I am not sure what is going on.  Is there something simple I am missing?

My `input_fn` looks like the following:

```
def _input_fn(training_dir,mode):


    train_text_1=np.vstack((np.load(training_dir+"/negative_"+mode+"_text_1.npy"),np.load(training_dir+"/positive_"+mode+"_text_1.npy")))
    train_text_2=np.vstack((=np.load(training_dir+"/negative_"+mode+"_text_2.npy"),np.load(training_dir+"/positive_"+mode+"_text_2.npy")))
    train_title_1=np.load(training_dir+"/"+mode+"_title_1.npy")
    train_title_2=np.load(training_dir+"/"+mode+"_title_2.npy")

    y=np.load(training_dir+"/targets_"+mode+".npy")
    y=y.reshape((y.shape[0],1)).astype(np.float32)
    # y=tf.cast(y, tf.float32)



    x={INPUT_TENSOR_NAME_1: train_text_1, 
       INPUT_TENSOR_NAME_2: train_text_2,
       INPUT_TENSOR_NAME_3: train_title_1, 
       INPUT_TENSOR_NAME_4: train_title_2}
    dataset=tf.estimator.inputs.numpy_input_fn(x=x,y=y,batch_size=BATCH_SIZE,num_epochs=10,shuffle=False)()


    return dataset
```

and the error to console is as follows:

```
INFO:sagemaker:Creating training-job with name: shared-model-lstm-2018-04-05-16-31-11-064
.INFO:sagemaker:TensorBoard 0.1.7 at http://localhost:6006
...............................................................................................................................Traceback (most recent call last):
  File "train.py", line 21, in <module>
    if __name__ == "__main__": main()
  File "train.py", line 18, in main
    estimator.fit(TRAING_DATA_BUCKET,run_tensorboard_locally=True)
  File "/Users/samuelkahn/anaconda/lib/python2.7/site-packages/sagemaker/tensorflow/estimator.py", line 232, in fit
    fit_super()
  File "/Users/samuelkahn/anaconda/lib/python2.7/site-packages/sagemaker/tensorflow/estimator.py", line 221, in fit_super
    super(TensorFlow, self).fit(inputs, wait, logs, job_name)
  File "/Users/samuelkahn/anaconda/lib/python2.7/site-packages/sagemaker/estimator.py", line 610, in fit
    super(Framework, self).fit(inputs, wait, logs, self._current_job_name)
  File "/Users/samuelkahn/anaconda/lib/python2.7/site-packages/sagemaker/estimator.py", line 165, in fit
    self.latest_training_job.wait(logs=logs)
  File "/Users/samuelkahn/anaconda/lib/python2.7/site-packages/sagemaker/estimator.py", line 398, in wait
    self.sagemaker_session.logs_for_job(self.job_name, wait=True)
  File "/Users/samuelkahn/anaconda/lib/python2.7/site-packages/sagemaker/session.py", line 651, in logs_for_job
    self._check_job_status(job_name, description)
  File "/Users/samuelkahn/anaconda/lib/python2.7/site-packages/sagemaker/session.py", line 395, in _check_job_status
    raise ValueError('Error training {}: {} Reason: {}'.format(job, status, reason))
ValueError: Error training shared-model-lstm-2018-04-05-16-31-11-064: Failed Reason: ClientError: Data download failed:Insufficient disk space
```

**Comment by samuelhkahn** [comment]
hrmm maybe I just need to set `train_volume_size` to higher in my estimator.

**Comment by yangaws** [comment]
Hi @samuelhkahn ,

Thanks for using sagemaker.

Our default training data size limit is 30GB:

https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L45

So if you have training data more than that, you could increase the train_volume_size argument in the tensorflow class. This value must be large enough to store the training file.

**Comment by samuelhkahn** [comment]
Thanks @yangaws - I ended up figuring this out before you posted, but I appreciate the response anyways. Now I have encountered the following: [Issue 134](https://github.com/aws/sagemaker-python-sdk/issues/134)

**Comment by yangaws** [comment]
Hi @samuelhkahn ,

Glad your problem is solved! For https://github.com/aws/sagemaker-python-sdk/issues/134, I have already replied. 

I will close this issue for now. Feel free to reply if you have further problem and questions.

**Comment by loretoparisi** [comment]
@yangaws I'm facing the same disk size issue for a _custom_ algorithm. I think 30GB isn't enough in real world training, specially if you are dealing with images, videos, audios or NMT as well it's not enough to mount your training data. Supposed I need 100GB, how to increment the training volume size?
