### ISSUE TITLE
Sagemaker Predictive maintenance module failed to run

### ISSUE THREAD

**Issue by eleyeth** [aws/sagemaker-python-sdk#1416]
**Describe the bug**
I am trying to run the Sagemaker predictive maintenance file on AWS but it wont run. I have tried updating mxnet to 1.6.0 as was recommended but I keep getting the error: 

```
UnexpectedStatusException: Error for Training job pred-maintenance-mxnet-modelv11: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/usr/local/bin/python3.6 sagemaker_predictive_maintenance_entry_point.py --batch-size 1 --epochs 500 --log-interval 100 --num-datasets 4 --num-gpus 1 --optimizer adam"
```

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.

```python
from sagemaker.mxnet import MXNet

training_job_name = 'pred-maintenance-mxnet-modelv11'
train_instance_type = 'ml.p3.2xlarge'

m = MXNet(entry_point='sagemaker_predictive_maintenance_entry_point.py',
          source_dir='sagemaker_predictive_maintenance_entry_point',
          py_version='py3',
          role=role, 
          train_instance_count=1, 
          train_instance_type=train_instance_type,
          output_path=output_location,
          hyperparameters={'num-datasets' : len(train_df),
                           'num-gpus': 1,
                           'epochs': 500,
                           'optimizer': 'adam',
                           'batch-size':1,
                           'log-interval': 100},
         input_mode='File',
         train_max_run=7200,
         framework_version='1.6.0')

m.fit({'train': s3_train_data}, job_name=training_job_name)
```

**Expected behavior**
I expected it to run and provide me with the output and predicted failures for equipment. I want to customize it for a usecase.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.
```
2020-04-15 20:21:37 Starting - Starting the training job...
2020-04-15 20:21:40 Starting - Launching requested ML instances......
2020-04-15 20:22:46 Starting - Preparing the instances for training......
2020-04-15 20:23:59 Downloading - Downloading input data
2020-04-15 20:23:59 Training - Downloading the training image......
2020-04-15 20:25:03 Training - Training image download completed. Training in progress..2020-04-15 20:25:03,851 sagemaker-containers INFO     Imported framework sagemaker_mxnet_container.training
2020-04-15 20:25:03,879 sagemaker_mxnet_container.training INFO     MXNet training environment: {'SM_HOSTS': '["algo-1"]', 'SM_NETWORK_INTERFACE_NAME': 'eth0', 'SM_HPS': '{"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"}', 'SM_USER_ENTRY_POINT': 'sagemaker_predictive_maintenance_entry_point.py', 'SM_FRAMEWORK_PARAMS': '{}', 'SM_RESOURCE_CONFIG': '{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"}', 'SM_INPUT_DATA_CONFIG': '{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}', 'SM_OUTPUT_DATA_DIR': '/opt/ml/output/data', 'SM_CHANNELS': '["train"]', 'SM_CURRENT_HOST': 'algo-1', 'SM_MODULE_NAME': 'sagemaker_predictive_maintenance_entry_point', 'SM_LOG_LEVEL': '20', 'SM_FRAMEWORK_MODULE': 'sagemaker_mxnet_container.training:main', 'SM_INPUT_DIR': '/opt/ml/input', 'SM_INPUT_CONFIG_DIR': '/opt/ml/input/config', 'SM_OUTPUT_DIR': '/opt/ml/output', 'SM_NUM_CPUS': '8', 'SM_NUM_GPUS': '1', 'SM_MODEL_DIR': '/opt/ml/model', 'SM_MODULE_DIR': 's3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz', 'SM_TRAINING_ENV': '{"additional_framework_parameters":{},"channel_input_dirs":{"train":"/opt/ml/input/data/train"},"current_host":"algo-1","framework_module":"sagemaker_mxnet_container.training:main","hosts":["algo-1"],"hyperparameters":{"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"},"input_config_dir":"/opt/ml/input/config","input_data_config":{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","is_master":true,"job_name":"pred-maintenance-mxnet-modelv11","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz","module_name":"sagemaker_predictive_maintenance_entry_point","network_interface_name":"eth0","num_cpus":8,"num_gpus":1,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"},"user_entry_point":"sagemaker_predictive_maintenance_entry_point.py"}', 'SM_USER_ARGS': '["--batch-size","1","--epochs","500","--log-interval","100","--num-datasets","4","--num-gpus","1","--optimizer","adam"]', 'SM_OUTPUT_INTERMEDIATE_DIR': '/opt/ml/output/intermediate', 'SM_CHANNEL_TRAIN': '/opt/ml/input/data/train', 'SM_HP_BATCH-SIZE': '1', 'SM_HP_LOG-INTERVAL': '100', 'SM_HP_OPTIMIZER': 'adam', 'SM_HP_NUM-DATASETS': '4', 'SM_HP_NUM-GPUS': '1', 'SM_HP_EPOCHS': '500'}
2020-04-15 20:25:04,158 sagemaker-containers INFO     Module default_user_module_name does not provide a setup.py. 
Generating setup.py
2020-04-15 20:25:04,158 sagemaker-containers INFO     Generating setup.cfg
2020-04-15 20:25:04,158 sagemaker-containers INFO     Generating MANIFEST.in
2020-04-15 20:25:04,158 sagemaker-containers INFO     Installing module with the following command:
/usr/local/bin/python3.6 -m pip install . -r requirements.txt
Processing /tmp/tmpyb5_i2kw/module_dir
Collecting mxnet-cu90mkl>=1.4
  Downloading https://files.pythonhosted.org/packages/ad/38/e1dd60173e4a2d3398fb982e873423fc62321b97db0a57c36ef889df5135/mxnet_cu90mkl-1.5.1.post0-py2.py3-none-manylinux1_x86_64.whl (525.2MB)
Requirement already satisfied: gluonnlp in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.9.1)
Collecting pandas==0.22
  Downloading https://files.pythonhosted.org/packages/da/c6/0936bc5814b429fddb5d6252566fe73a3e40372e6ceaf87de3dec1326f28/pandas-0.22.0-cp36-cp36m-manylinux1_x86_64.whl (26.2MB)
Requirement already satisfied: requests<3,>=2.20.0 in /usr/local/lib/python3.6/site-packages (from mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: numpy<2.0.0,>1.16.0 in /usr/local/lib/python3.6/site-packages (from mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (1.17.2)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.6/site-packages (from mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (0.8.4)
Requirement already satisfied: cython in /usr/local/lib/python3.6/site-packages (from gluonnlp->-r requirements.txt (line 2)) (0.29.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/site-packages (from gluonnlp->-r requirements.txt (line 2)) (20.3)
Requirement already satisfied: python-dateutil>=2 in /usr/local/lib/python3.6/site-packages (from pandas==0.22->-r requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/site-packages (from pandas==0.22->-r requirements.txt (line 3)) (2019.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests<3,>=2.20.0->mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests<3,>=2.20.0->mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests<3,>=2.20.0->mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests<3,>=2.20.0->mxnet-cu90mkl>=1.4->-r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging->gluonnlp->-r requirements.txt (line 2)) (2.4.6)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from packaging->gluonnlp->-r requirements.txt (line 2)) (1.14.0)
Installing collected packages: mxnet-cu90mkl, pandas, default-user-module-name
  Found existing installation: pandas 0.25.1
    Uninstalling pandas-0.25.1:
      Successfully uninstalled pandas-0.25.1
    Running setup.py install for default-user-module-name: started
    Running setup.py install for default-user-module-name: finished with status 'done'
Successfully installed default-user-module-name-1.0.0 mxnet-cu90mkl-1.5.1.post0 pandas-0.22.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2020-04-15 20:25:37,520 sagemaker-containers INFO     Invoking user script

Training Env:

{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "train": "/opt/ml/input/data/train"
    },
    "current_host": "algo-1",
    "framework_module": "sagemaker_mxnet_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "batch-size": 1,
        "log-interval": 100,
        "optimizer": "adam",
        "num-datasets": 4,
        "num-gpus": 1,
        "epochs": 500
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "train": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "is_master": true,
    "job_name": "pred-maintenance-mxnet-modelv11",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz",
    "module_name": "sagemaker_predictive_maintenance_entry_point",
    "network_interface_name": "eth0",
    "num_cpus": 8,
    "num_gpus": 1,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "hosts": [
            "algo-1"
        ],
        "network_interface_name": "eth0"
    },
    "user_entry_point": "sagemaker_predictive_maintenance_entry_point.py"
}

Environment variables:

SM_HOSTS=["algo-1"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"}
SM_USER_ENTRY_POINT=sagemaker_predictive_maintenance_entry_point.py
SM_FRAMEWORK_PARAMS={}
SM_RESOURCE_CONFIG={"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"}
SM_INPUT_DATA_CONFIG={"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["train"]
SM_CURRENT_HOST=algo-1
SM_MODULE_NAME=sagemaker_predictive_maintenance_entry_point
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_mxnet_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=8
SM_NUM_GPUS=1
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{"train":"/opt/ml/input/data/train"},"current_host":"algo-1","framework_module":"sagemaker_mxnet_container.training:main","hosts":["algo-1"],"hyperparameters":{"batch-size":1,"epochs":500,"log-interval":100,"num-datasets":4,"num-gpus":1,"optimizer":"adam"},"input_config_dir":"/opt/ml/input/config","input_data_config":{"train":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","is_master":true,"job_name":"pred-maintenance-mxnet-modelv11","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://ascendpred/pred-maintenance-mxnet-modelv11/source/sourcedir.tar.gz","module_name":"sagemaker_predictive_maintenance_entry_point","network_interface_name":"eth0","num_cpus":8,"num_gpus":1,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"},"user_entry_point":"sagemaker_predictive_maintenance_entry_point.py"}
SM_USER_ARGS=["--batch-size","1","--epochs","500","--log-interval","100","--num-datasets","4","--num-gpus","1","--optimizer","adam"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TRAIN=/opt/ml/input/data/train
SM_HP_BATCH-SIZE=1
SM_HP_LOG-INTERVAL=100
SM_HP_OPTIMIZER=adam
SM_HP_NUM-DATASETS=4
SM_HP_NUM-GPUS=1
SM_HP_EPOCHS=500
PYTHONPATH=/opt/ml/code:/usr/local/bin:/usr/local/lib/python36.zip:/usr/local/lib/python3.6:/usr/local/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/site-packages

Invoking script with the following command:

/usr/local/bin/python3.6 sagemaker_predictive_maintenance_entry_point.py --batch-size 1 --epochs 500 --log-interval 100 --num-datasets 4 --num-gpus 1 --optimizer adam


Traceback (most recent call last):
  File "sagemaker_predictive_maintenance_entry_point.py", line 8, in <module>
    import mxnet as mx
  File "/usr/local/lib/python3.6/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/usr/local/lib/python3.6/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/usr/local/lib/python3.6/site-packages/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python3.6/site-packages/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/local/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory
2020-04-15 20:25:37,778 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/usr/local/bin/python3.6 sagemaker_predictive_maintenance_entry_point.py --batch-size 1 --epochs 500 --log-interval 100 --num-datasets 4 --num-gpus 1 --optimizer adam"
Traceback (most recent call last):
  File "/usr/local/bin/dockerd-entrypoint.py", line 20, in <module>
    subprocess.check_call(shlex.split(' '.join(sys.argv[1:])))
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['train']' returned non-zero exit status 1.

2020-04-15 20:25:51 Uploading - Uploading generated training model
2020-04-15 20:25:51 Failed - Training job failed
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-25-f6caccd9fd2a> in <module>()
     21          framework_version='1.6.0')
     22 
---> 23 m.fit({'train': s3_train_data}, job_name=training_job_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    463         self.jobs.append(self.latest_training_job)
    464         if wait:
--> 465             self.latest_training_job.wait(logs=logs)
    466 
    467     def _compilation_job_name(self):

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1056         # If logs are requested, call logs_for_jobs.
   1057         if logs != "None":
-> 1058             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1059         else:
   1060             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   3019 
   3020         if wait:
-> 3021             self._check_job_status(job_name, description, "TrainingJobStatus")
   3022             if dot:
   3023                 print()

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   2613                 ),
   2614                 allowed_statuses=["Completed", "Stopped"],
-> 2615                 actual_status=status,
   2616             )
   2617 

UnexpectedStatusException: Error for Training job pred-maintenance-mxnet-modelv11: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/usr/local/bin/python3.6 sagemaker_predictive_maintenance_entry_point.py --batch-size 1 --epochs 500 --log-interval 100 --num-datasets 4 --num-gpus 1 --optimizer adam"
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: MXnet
- **Framework version**:1.3.0 and 1.6.0
- **Python version**: 3.6
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: Y (i believe)

**Additional context**

**Comment by vishaalkapoor** [comment]
Taking a look.

**Comment by eleyeth** [comment]
> Taking a look.

I got advised of a solution by downgrading gluonnlp version. 
gluonlp 0.9.0 was looking for a parameter 'replace_file', which was added in MXNet 1.6.0.
However, changing the framework version of MXNet to 1.6.0 resolved the issue of gluonnlp but the training was failing with different stack trace.  downgrading the version of gluonnlp to 0.8.3 resolved the issue.

**Comment by laurenyu** [comment]
sounds like the issue was resolved - please feel free to reopen the issue if that's not the case

**Comment by mohitghatikar91** [comment]
@eleyeth Hi, I'm facing the same error as you. How did you downgrade the gluonnlp version?

**Comment by vishaalkapoor** [comment]
Hi @mohitghatikar91, 
please take a look at
https://stackoverflow.com/questions/61389632/import-error-while-executing-aws-predictive-maintenance-using-machine-learning-s 
and
https://github.com/awslabs/predictive-maintenance-using-machine-learning/issues/6 
If you have any issues, please file them in the issue above as they would be with the predictive maintenance solution and not the SDK. Thanks!
