### ISSUE TITLE
Error hosting endpoint - production variant AllTraffic did not pass the ping health check

### ISSUE THREAD

**Issue by OktayGardener** [aws/sagemaker-python-sdk#155]
Hello!

I am using sagemaker version 1.2.3, and using a Keras model.

I am using the sagemaker.Tensorflow class in order to train, create model, create endpoint config, create endpoint, I am however using the offered `fit()` and `deploy()` as defined by the sagemaker.Tensorflow API.

I am creating my estimator like the following:

```
    def estimator(self):
        return TensorFlow(
            entry_point=self.entry_point,
            source_dir=self.source_dir,
            role=self.config.role,
            output_path=self.config.output_path,
            code_location=self.config.code_location,
            train_instance_count=self.config.train_instance_count,
            train_instance_type=self.train_instance_type,
            training_steps=self.config.training_steps,
            evaluation_steps=self.config.evaluation_steps
        )
```

I am calling fit() and deploy() like the following:

```
            self.estimator.fit(
                self.train_data_location,
                job_name=self.training_job_name,
                run_tensorboard_locally=True,
            )

    def deploy(self):
            self.estimator.deploy(
                initial_instance_count=self.config.initial_instance_count,
                instance_type=self.instance_type,
                endpoint_name=self.endpoint_name
            )
```

No matter what model I try to deploy, I get the following error:

```ValueError: Error hosting endpoint model-tensorflow-endpoint: Failed Reason:  The primary container for production variant AllTraffic did not pass the ping health check.```

I am also getting the same error with the examples from the sagemaker-examples repo.

Here's the log from cloudwatch:

```
2018-04-17 21:44:34,190 WARNING - root - error reading log_level, using INFO
2018-04-17 21:44:34,190 INFO - root - running container entrypoint
2018-04-17 21:44:34,191 INFO - root - starting serve task
2018-04-17 21:44:34,191 INFO - container_support.serving - reading config
2018-04-17 21:44:34,194 ERROR - root - uncaught exception: 'SAGEMAKER_CONTAINER_LOG_LEVEL'
Traceback (most recent call last):
File "/usr/local/bin/entry.py", line 28, in <module>
modes[mode]()
File "/usr/local/lib/python2.7/dist-packages/container_support/serving.py", line 72, in start
env = cs.HostingEnvironment()
File "/usr/local/lib/python2.7/dist-packages/container_support/environment.py", line 297, in __init__
self.container_log_level = int(os.environ[ContainerEnvironment.CONTAINER_LOG_LEVEL_PARAM.upper()])
File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
raise KeyError(key)
KeyError: 'SAGEMAKER_CONTAINER_LOG_LEVEL'
```

What's with this? Am I missing something? The examples aren't passing this parameter in the sagemaker-examples repo either. I'm having this problem both for Tensorflow Model and by using BYO Model.

I should add that when I use the same code and try to deploy a new endpoint within a sagemaker notebook (that uses sagemaker version 1.0.1) on AWS, I have no problems and I can create a new endpoint.

**Comment by ChoiByungWook** [comment]
Hello,

Thanks for being this to our attention.

It looks like it is a problem with not being able to find the correct environment variable value in the hosting container.

Can you please provide the following:

1. What version of the TensorFlow container are you using?
2. Are you using your own TensorFlow image or SageMakers?
3. If this was run on SageMaker, can you please check to see if the environment variable, "sagemaker_container_log_level", for the corresponding model was set correctly? This can be done through the AWS console. (AWS Console -> SageMaker -> Models -> Your_Model -> "Environment Variables" under Primary Container)

If the environment variable isn't set within the SageMaker model, then it is most likely an SDK issue as that values get propagated through the SDK, https://github.com/aws/sagemaker-python-sdk/blob/157d8670977243f7f77327175d40364c885482b3/src/sagemaker/model.py#L179. If it is set in the model, but the problem still persists it is a container issue.

**Comment by OktayGardener** [comment]
Hey @ChoiByungWook! 
1: TF Version: 1.6.0
2: Image: SageMaker's image
3: Actually, it's 'empty'. This is pretty interesting. 

Yes, we found this today while going through the stack.


We also found this:

https://github.com/aws/sagemaker-python-sdk/blob/157d8670977243f7f77327175d40364c885482b3/src/sagemaker/model.py#L47

and 

https://github.com/aws/sagemaker-python-sdk/blob/157d8670977243f7f77327175d40364c885482b3/src/sagemaker/estimator.py#L182

so I thought I could do:

```
            self.estimator.deploy(
                initial_instance_count=self.initial_instance_count,
                instance_type=self.instance_type,
                endpoint_name=self.endpoint_name,
                # env={'SAGEMAKER_CONTAINER_LOG_LEVEL': 10}
            )
```

But no such luck. 

Interestingly, when I call the 'deploy' operation instantly after the 'fit' operation and not calling another function on my custom class, this works fine.

However, I also created functionality to be able to switch a model in production, and used the boto3 API to do so.

```
def postdeploy(self):
        """ Deploy a trained model, create corresponding endpoint configuration and endpoint """
        self.create_model_from_job()
        self.create_endpoint_configuration()
        self.session.create_endpoint(
            endpoint_name=self.config.endpoint_name,
            config_name=self.endpoint_config_name,
        )

    def create_model_from_job(self):
        self.session.create_model_from_job(
            training_job_name=self.training_job_name,
            name=self.config.model_name,
            role=self.config.role
        )

    def create_endpoint_configuration(self):
        self.endpoint_config_name = self.session.create_endpoint_config(
            name=self.endpoint_name,
            model_name=self.config.model_name,
            initial_instance_count=self.config.initial_instance_count,
            instance_type=self.instance_type
        )

    def update_endpoint(self):
        self.client.update_endpoint(
            EndpointName=self.config.endpoint_name, EndpointConfigName=self.endpoint_config_name
        )
```

and by looking at the signature,
```
    def create_model_from_job(self, training_job_name, name=None, role=None, primary_container_image=None,
                              model_data_url=None, env={}):
```

It looks like I can pass the 'env' params to set the `CONTAINER_LOG_LEVEL_PARAM_NAME` here. Hopefully you guys will integrate this boto3 API call to the sagemaker API soon.

**Comment by ChoiByungWook** [comment]
Awesome!

It looks like you were able to find a workaround for this issue. If you would like, please feel free to submit a pull request with our changes. We would really appreciate it!

Thanks!
