### ISSUE TITLE
input_fn gets called on inference outputs during inference job

### ISSUE THREAD

**Issue by dshen109** [aws/sagemaker-python-sdk#1649]
**Describe the bug**
I'm using the batch transform feature in Amazon Sagemaker sklearn and have defined a custom `input_fn` to do feature selection. However, it seems like this function gets called twice during the batch transform operation. The first time, the inputs are the desired test data, but the second time, the inputs are the outputs of the inference operation, which doesn't seem like it should be happening (and also causes the transform job to error).

**To reproduce**

```python
sagemaker_session = sagemaker.Session(default_bucket=BUCKET)

script_path = 'daily_building_peak_forecaster.py'

sklearn = SKLearn(
    image_name=IMAGE,
    entry_point=script_path,
    train_instance_type='ml.c4.xlarge',
    role=get_execution_role(),
    sagemaker_session=sagemaker_session)

sklearn.fit({'train': TRAINING_INPUT}, job_name=OUTPUT_DIR.replace("_", "-"))

model = sklearn.create_model(
    name=MODEL_NAME, env={"SITE_ID": SITE})

transformer = model.transformer(
    1, "ml.m5.large",
    output_path="s3://foo/")
TEST_DATA = "s3://bar/test.csv"
transformer.transform(TEST_DATA, content_type="text/csv", split_type="Line", wait=True, logs=True)
```

Custom input function:

```python
def input_fn(request_body, request_content_type):
    """ An input_fn that loads a text/csv array. """
    if not SITE:
        raise RuntimeError("No SITE_ID environment variable specified.")
    print("------------")
    print("Request body:")
    print(request_body)
    print("------------")

    if request_content_type == 'text/csv':
        df = pd.read_csv(
            StringIO(request_body), parse_dates=['timestamp'])
        return forecasting_service.data_to_features(
            SITE, df, FORECAST_HORIZON)
    else:
        raise ValueError(f"{request_content_type} not supported by script!")
```

**Expected behavior**
`input_fn` is called once.

**Screenshots or logs**

Logs:
```
--------------------
Request body:
timestamp,temperature
2018-04-01 00:00:00,51.08
2018-04-01 00:15:00,51.025
2018-04-01 00:30:00,50.97
2018-04-01 00:45:00,50.915
2018-04-01 01:00:00,50.86
2018-04-01 01:15:00,50.7325
2018-04-01 01:30:00,50.605
2018-04-01 01:45:00,50.4775
2018-04-01 02:00:00,50.35
2018-04-01 02:15:00,50.2
2018-04-01 02:30:00,50.05
2018-04-01 02:45:00,49.9
2018-04-01 03:00:00,49.75
2018-04-01 03:15:00,49.555
2018-04-01 03:30:00,49.36
2018-04-01 03:45:00,49.165

--------------------
169.254.255.130 - - [30/Jun/2020:04:10:55 +0000] "POST /invocations HTTP/1.1" 200 20 "-" "Go-http-client/1.1"
2020-06-30 04:10:56,008 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
--------------------
Request body:
[164.53500910814188]

--------------------

2020-06-30 04:10:56,727 ERROR - daily_building_peak_forecaster - Exception on /invocations [POST]
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 93, in wrapper
    return fn(*args, **kwargs)
  File "/opt/ml/code/daily_building_peak_forecaster.py", line 68, in input_fn
    df = pd.read_csv(StringIO(request_body), parse_dates=['timestamp'])
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1949, in __init__
    self._set_noconvert_columns()
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2015, in _set_noconvert_columns
    _set(val)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2005, in _set
    x = names.index(x)
ValueError: 'timestamp' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/miniconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_transformer.py", line 200, in transform
    self._model, request.content, request.content_type, request.accept
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_transformer.py", line 227, in _default_transform_fn
    data = self._input_fn(content, content_type)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 95, in wrapper
    six.reraise(error_class, error_class(e), sys.exc_info()[2])
  File "/miniconda3/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 93, in wrapper
    return fn(*args, **kwargs)
  File "/opt/ml/code/daily_building_peak_forecaster.py", line 68, in input_fn
    df = pd.read_csv(StringIO(request_body), parse_dates=['timestamp'])
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1949, in __init__
    self._set_noconvert_columns()
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2015, in _set_noconvert_columns
    _set(val)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2005, in _set
    x = names.index(x)
sagemaker_containers._errors.ClientError: 'timestamp' is not in list
169.254.255.130 - - [30/Jun/2020:04:10:56 +0000] "POST /invocations HTTP/1.1" 500 290 "-" "Go-http-client/1.1"
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 93, in wrapper
    return fn(*args, **kwargs)
  File "/opt/ml/code/daily_building_peak_forecaster.py", line 68, in input_fn
    df = pd.read_csv(StringIO(request_body), parse_dates=['timestamp'])
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1949, in __init__
    self._set_noconvert_columns()
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2015, in _set_noconvert_columns
    _set(val)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2005, in _set
    x = names.index(x)
ValueError: 'timestamp' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/miniconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/miniconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_transformer.py", line 200, in transform
    self._model, request.content, request.content_type, request.accept
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_transformer.py", line 227, in _default_transform_fn
    data = self._input_fn(content, content_type)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 95, in wrapper
    six.reraise(error_class, error_class(e), sys.exc_info()[2])
  File "/miniconda3/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 93, in wrapper
    return fn(*args, **kwargs)
  File "/opt/ml/code/daily_building_peak_forecaster.py", line 68, in input_fn
    df = pd.read_csv(StringIO(request_body), parse_dates=['timestamp'])
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1949, in __init__
    self._set_noconvert_columns()
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2015, in _set_noconvert_columns
    _set(val)
  File "/miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 2005, in _set
    x = names.index(x)
sagemaker_containers._errors.ClientError: 'timestamp' is not in list
169.254.255.130 - - [30/Jun/2020:04:10:56 +0000] "POST /invocations HTTP/1.1" 500 290 "-" "Go-http-client/1.1"
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 1.65.1.post0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: sklearn
- **Framework version**: 0.23.1
- **Python version**: 3.7
- **CPU or GPU**: 
- **Custom Docker image (Y/N)**: Y

**Comment by metrizable** [comment]
@dshen109 Thanks for filing the bug. Looking into this now. I'm assuming the rest of the contents of `daily_building_peak_forecaster.py` are pretty straightforward and do not invoke `input_fn` (the function looks to lie around line 68 in your Python script, at least from the logs).

**Comment by davidbrochart** [comment]
@dshen109 is this issue still relevant, or is it fine to close it?

**Comment by akrishna1995** [comment]
Closing this issue for now. Please feel free to reopen if the bug still exists with the latest sagemaker. Thanks
