### ISSUE TITLE
Read Sagemaker output into JSON

### ISSUE THREAD

**Issue by Sandy26** [aws/sagemaker-python-sdk#190]
Hello AWS Lambda/SageMaker community

- **Python Version**: 2.7
Using AWS Lambda code in Python 2.7 to call model in SageMaker using endpoint-

data=[6.4, 3.2, 4.5, 1.5]
response = sagemaker.invoke_endpoint(EndpointName="irispredict",Body=json.dumps(data))
print(response['Body'].read())

The print statement gives output-

{
  "result": {
    "classifications": [
      {
        "classes": [
          {
            "score": 3.324399585835636e-05, 
            "label": "0"
          }, 
          {
            "score": 0.9996429681777954, 
            "label": "1"
          }, 
          {
            "score": 0.0003237576747778803, 
            "label": "2"
          }
        ]
      }
    ]
  }
}

### Describe the problem
So the above part works fine. But I want now put the response['Body'] (it being a  <botocore.response.StreamingBody> object) in a useable format like JSON or Python Dictionary. So I tried this-
res_json = json.loads(response['Body'].read())
I get the an error-

No JSON object could be decoded: ValueError
Traceback (most recent call last):
  File "/var/task/test_python.py", line 24, in handler
    return on_intent(event['request'], event['session'])
  File "/var/task/test_python.py", line 59, in on_intent
    return get_rawtext(intent_request)
  File "/var/task/test_python.py", line 106, in get_rawtext
    res_json = json.loads(response['Body'].read())
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I also tried-
res_json = json.loads(response['Body'].read().decode("utf-8"))
but got the same error-
Traceback (most recent call last):
  File "/var/task/test_python.py", line 24, in handler
    return on_intent(event['request'], event['session'])
  File "/var/task/test_python.py", line 59, in on_intent
    return get_rawtext(intent_request)
  File "/var/task/test_python.py", line 105, in get_rawtext
    res_json = json.loads(response['Body'].read().decode("utf-8"))
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I see the json_loads function as a potential solution is some threads but I don't see it to be asserted by anyone to be working. If If there is away to convert this <botocore.response.StreamingBody> into python dictionary that would be great too!

Any pointers/thoughts are greatly appreciated.

Thank you,
Sandy

**Comment by Sandy26** [comment]
Hi All,
Please ignore the post as following works-
 res_json = json.loads(response['Body'].read().decode("utf-8"))

There were some tabbing issues in AWS Lamba. Hope this helps

Best,
Sandy
