### ISSUE TITLE
model_fn ignored on PyTorch v1.6 serving container?

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-python-sdk#1957]
**Describe the bug**

PyTorch inference container at v1.6 seems to ignore the provided [model_fn()](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#load-a-model) and attempt to load a `model.pth` file (non-existent in my case), resulting in an error for code which worked fine on the v1.4 container.

Maybe this is just a doc issue? I couldn't see any indication of how this override should be provided differently in v1.6.

**To reproduce**

- Train a model in PyTorch framework container v1.6 and save it as a non-standard artifact (e.g. put it in a zip file inside the model.tar.gz, or something)
- Create a `PyTorchModel` with e.g. `source_dir="src/", entry_point="src/inference.py"`, where the entry point script defines a `model_fn(model_dir: str)`
- Try to run the model e.g. as a batch transform.

(Will see if there's any public example I can link to to accelerate reproduction)

**Expected behavior**

The container calls the `model_fn` per the [SageMaker SDK docs](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#load-a-model) and loads the model successfully.

**Screenshots or logs**

My job appears to have generated **A LOT** of duplicate log entries repeating the below, before eventually going quiet/hanging. Still shows as in-progress with 0 CPU utilization many minutes later - much longer than the typical for same dataset on previous PyTorch versions - so I forcibly stopped it.

```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/model/model.pth'
Traceback (most recent call last):
  File "/opt/conda/bin/torch-model-archiver", line 10, in <module>
    sys.exit(generate_model_archive())
  File "/opt/conda/lib/python3.6/site-packages/model_archiver/model_packaging.py", line 60, in generate_model_archive
    package_model(args, manifest=manifest)
  File "/opt/conda/lib/python3.6/site-packages/model_archiver/model_packaging.py", line 37, in package_model
    model_path = ModelExportUtils.copy_artifacts(model_name, **artifact_files)
  File "/opt/conda/lib/python3.6/site-packages/model_archiver/model_packaging_utils.py", line 150, in copy_artifacts
    shutil.copy(path, model_path)
  File "/opt/conda/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/conda/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.15.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: PyTorch
- **Framework version**: 1.6
- **Python version**: 3
- **CPU or GPU**: GPU
- **Custom Docker image (Y/N)**: N

**Additional context**

N/A

**Comment by ChuyangDeng** [comment]
Hello @athewsey, do you have a `requirements.txt` in your model data archive or does your `inference.py` imports anything that's not pre-installed to the PyTorch container?

**Comment by cfregly** [comment]
@ChuyangDeng and @athewsey I believe the new PyTorch 1.6 image requires that the model filename be `model.pth`.  I had to make changes to our code, as well, to conform.  this is not ideal, of course.

here is the code relevant:  https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/9a6869e/src/sagemaker_pytorch_serving_container/torchserve.py#L121

and here is the sample that we're working from:  https://github.com/tobrien0/TorchServeOnAWS/blob/9fa0f87/2_serving_natively_with_amazon_sagemaker/deploy.ipynb

You might be able to override the default.  @ChuyangDeng can you advise?

cc @antje

**Comment by icywang86rui** [comment]
@athewsey Thanks for bring this to our attention. Are you using the official containers or did you build your own? Could you show me the code you use to start the batch job?

**Comment by antje** [comment]
Here's a sample notebook that succesfully deploys a PyTorch 1.6 model using the SageMaker PyTorch 1.6 framework container with TorchServe: 

https://github.com/data-science-on-aws/workshop/blob/374329adf15bf1810bfc4a9e73501ee5d3b4e0f5/09_deploy/wip/pytorch/01_Deploy_RoBERTa.ipynb

We use a pre-trained Hugging Face Roberta model with a custom inference script:
https://github.com/data-science-on-aws/workshop/blob/374329adf15bf1810bfc4a9e73501ee5d3b4e0f5/09_deploy/wip/pytorch/code/inference.py

It seems that the model has be called exactly `model.pth` for the SageMaker PyTorch 1.6 serving container to pick it up correctly: 
See: 
https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/6936c08581e26ff3bac26824b1e4946ec68ffc85/src/sagemaker_pytorch_serving_container/torchserve.py#L45

Hope that helps.
Antje

**Comment by athewsey** [comment]
Hi @ChuyangDeng and @icywang86rui sorry to be slow. I'm using the official PyTorch v1.6 container, providing both a `requirements.txt` and an `inference.py`.

My current flow is to first train an estimator, and then create a model and deploy it, like:

```python
training_job_desc = estimator.latest_training_job.describe()
model = PyTorchModel(
    model_data=training_job_desc["ModelArtifacts"]["S3ModelArtifacts"],
    name=training_job_desc["TrainingJobName"],
    role=role,
    source_dir="src/",  # also contains requirements.txt
    entry_point="src/inference.py",
    framework_version="1.6",
    py_version="py3",
)
```

Some libraries (e.g. [pytorch-tabnet](https://github.com/dreamquark-ai/tabnet)) do not produce `.pth` files because they wrap some additional configuration or functionality in their saved files/bundles. I'd prefer not to have to reverse engineer every high-level library I use to recover a raw `.pth` file, and in previous versions the `model_fn` pattern provided a great compatibility layer for achieving this.

I'm not really clear from the responses here whether this is planned to be "fixed" in the inference container or just removing the functionality from the docs? TorchServe [offers APIs](https://pytorch.org/serve/custom_service.html) to customize the `initialize()`ation functions for a model, right?
