### ISSUE TITLE
smdistributed.dataparallel.tensorflow.DistributedOptimizer(): apply_gradients() got an unexpected keyword argument 'global_step'

### ISSUE THREAD

**Issue by aysusayin** [aws/sagemaker-python-sdk#2077]
**Describe the bug**
I implemented my own tensorflow training script and want to use smdistributed.dataparallel.  I'm using Sagemaker Studio.
I defined the optimizer like this:
`optimizer = sdp.DistributedOptimizer(tf.keras.optimizers.Adam(learning_rate=args.learning_rate * sdp.size()))`
And the model is trained like this:
```
model.compile(loss=loss, optimizer=optimizer, metrics=metrics)
model.fit(x=xtrain_scaled, y=ytrain_scaled, validation_data= (xval_scaled, yval_scaled),
                 epochs=args.epochs,
                 batch_size=args.batch_size,
                 #callbacks = callbacks,
                 verbose=1)
```

However I get this error:
```
[1,6]<stdout>:Traceback (most recent call last):
[1,6]<stdout>:  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[1,6]<stdout>:    "__main__", mod_spec)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
[1,6]<stdout>:    exec(code, run_globals)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/mpi4py/__main__.py", line 7, in <module>
[1,6]<stdout>:    main()
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/mpi4py/run.py", line 196, in main
[1,6]<stdout>:    run_command_line(args)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/mpi4py/run.py", line 42, in run_command_line
[1,6]<stdout>:    run_module(sys.argv[0], run_name='__main__', alter_sys=True)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/runpy.py", line 205, in run_module
[1,6]<stdout>:    return _run_module_code(code, init_globals, run_name, mod_spec)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
[1,6]<stdout>:    mod_name, mod_spec, pkg_name, script_name)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
[1,6]<stdout>:    exec(code, run_globals)
[1,6]<stdout>:  File "/opt/ml/code/NNtrain_script.py", line 331, in <module>
[1,6]<stdout>:    model = sdp_train(args)
[1,6]<stdout>:  File "/opt/ml/code/NNtrain_script.py", line 313, in sdp_train
[1,6]<stdout>:    verbose=1)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 109, in _method_wrapper
[1,6]<stdout>:    return method(self, *args, **kwargs)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1126, in fit
[1,6]<stdout>:    tmp_logs = train_function(iterator)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
[1,6]<stdout>:    result = self._call(*args, **kwds)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
[1,6]<stdout>:    self._initialize(args, kwds, add_initializers_to=initializers)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
[1,6]<stdout>:    *args, **kwds))
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2857, in _get_concrete_function_internal_garbage_collected
[1,6]<stdout>:    graph_function, _, _ = self._maybe_define_function(args, kwargs)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3215, in _maybe_define_function
[1,6]<stdout>:    graph_function = self._create_graph_function(args, kwargs)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3077, in _create_graph_function
[1,6]<stdout>:    capture_by_value=self._capture_by_value),
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
[1,6]<stdout>:    func_outputs = python_func(*func_args, **func_kwargs)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
[1,6]<stdout>:    return weak_wrapped_fn().__wrapped__(*args, **kwds)
[1,6]<stdout>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
[1,6]<stdout>:    raise e.ag_error_metadata.to_exception(e)
[1,4]<stdout>:Traceback (most recent call last):
[1,6]<stdout>:TypeError: in user code:
[1,6]<stdout>:
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:825 train_function  *
[1,6]<stdout>:        return step_function(self, iterator)
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:815 step_function  **
[1,6]<stdout>:        outputs = model.distribute_strategy.run(run_step, args=(data,))
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
[1,6]<stdout>:        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
[1,6]<stdout>:        return self._call_for_each_replica(fn, args, kwargs)
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
[1,6]<stdout>:        return fn(*args, **kwargs)
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:808 run_step  **
[1,6]<stdout>:        outputs = model.train_step(data)
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:774 train_step
[1,6]<stdout>:        self.trainable_variables)
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:2806 _minimize
[1,6]<stdout>:        optimizer.apply_gradients(zip(gradients, trainable_variables))
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/tensorflow/python/keras/optimizers.py:775 apply_gradients
[1,6]<stdout>:        self.optimizer.apply_gradients(grads, global_step=self.iterations)
[1,6]<stdout>:    /usr/local/lib/python3.7/site-packages/smdistributed/dataparallel/tensorflow/__init__.py:169 apply_gradients
[1,6]<stdout>:        return self._optimizer.apply_gradients(*args, **kwargs)
[1,6]<stdout>:
[1,6]<stdout>:    TypeError: apply_gradients() got an unexpected keyword argument 'global_step'
```
**Expected behavior**
I expect the model to be trained.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:2.23.2
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:Tensorflow
- **Framework version**:2.3.1
- **Python version**:3.7
- **CPU or GPU**: GPU
- **Custom Docker image (Y/N)**:N

**Additional context**

**Comment by rahulShrivastavaAWS** [comment]
We are working on Keras support for smdataparallel.

**Comment by aysusayin** [comment]
When do you plan to release the Keras support for smdataparallel?

**Comment by rahulShrivastavaAWS** [comment]
We are working on it on priority basis but ETA is available.

**Comment by aysusayin** [comment]
Thank you!

**Comment by vrbsky** [comment]
Hi, there. Any updates on the ETA for smdataparallel Keras support?
@rahulShrivastavaAWS or anyone else
