### ISSUE TITLE
Load model failed: model, error: Worker died. when deploying estimator

### ISSUE THREAD

**Issue by tbass134** [aws/sagemaker-python-sdk#2284]
**Describe the bug**
After successfully building the Pytorch Estimator, im unable to deploy. 
"W-9000-model_1 org.pytorch.serve.wlm.BatchAggregator - Load model failed: model, error: Worker died."

**To reproduce**
Using FastAI (latest version)
deploy script

```
from sagemaker.pytorch.estimator import PyTorch 
estimator = PyTorch(entry_point='app.py',
                         source_dir='souce_trained_model',
                         base_job_name='coin-sentiment',
                         role='arn:aws:iam::471559725016:role/sagemaker-role',
                         framework_version='1.7.1',
                         py_version='py3',
                         instance_count=1,
                         instance_type="ml.p2.xlarge",
                            predictor=myPredictor
                   )
estimator.fit(inputs)
```

deploy
`predictor = estimator.deploy(initial_instance_count=1, instance_type="ml.p2.xlarge")
`

**Expected behavior**
The endpoint should be created

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.31.1
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:pytorch
- **Framework version**: 1.7.1
- **Python version**: 3.6
- **CPU or GPU**: cpu
- **Custom Docker image (Y/N)**:no

**Additional context**
Cloudwatch logs:
```

2021-04-13 17:56:37,713 [INFO ] W-9000-model_1 ACCESS_LOG - /10.32.0.2:35632 "GET /ping HTTP/1.1" 200 0
--
2021-04-13 17:56:37,713 [INFO ] W-9000-model_1 TS_METRICS - Requests2XX.Count:1\|#Level:Host\|#hostname:model.aws.local,timestamp:null
2021-04-13 17:56:38,635 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.ts.sock.9000
2021-04-13 17:56:38,635 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]126
2021-04-13 17:56:38,635 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2021-04-13 17:56:38,635 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.13
2021-04-13 17:56:38,636 [INFO ] W-9000-model_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2021-04-13 17:56:38,637 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2021-04-13 17:56:40,665 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ================ model_fn ================
2021-04-13 17:56:40,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model_dir ['/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/handler_service.py', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/MAR-INF', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/finetuned.pth', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/__pycache__', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/model.pkl', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/code']
2021-04-13 17:56:40,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2021-04-13 17:56:40,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2021-04-13 17:56:40,667 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2021-04-13 17:56:40,667 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.6/site-packages/ts/model_service_worker.py", line 182, in <module>
2021-04-13 17:56:40,667 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2021-04-13 17:56:40,668 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.6/site-packages/ts/model_service_worker.py", line 154, in run_server
2021-04-13 17:56:40,668 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2021-04-13 17:56:40,667 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.BatchAggregator - Load model failed: model, error: Worker died.
2021-04-13 17:56:40,668 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-model_1-stderr
2021-04-13 17:56:40,668 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-model_1-stdout
2021-04-13 17:56:40,669 [INFO ] W-9000-model_1 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 5 seconds.
2021-04-13 17:56:40,669 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-model_1-stdout
2021-04-13 17:56:40,692 [INFO ] W-9000-model_1-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-model_1-stderr
2021-04-13 17:56:42,713 [INFO ] W-9000-model_1 ACCESS_LOG - /10.32.0.2:35632 "GET /ping HTTP/1.1" 200 1
2021-04-13 17:56:42,713 [INFO ] W-9000-model_1 TS_METRICS - Requests2XX.Count:1\|#Level:Host\|#hostname:model.aws.local,timestamp:null
2021-04-13 17:56:45,798 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.ts.sock.9000
2021-04-13 17:56:45,798 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]142
2021-04-13 17:56:45,798 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2021-04-13 17:56:45,799 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.13
2021-04-13 17:56:45,799 [INFO ] W-9000-model_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2021-04-13 17:56:45,800 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2021-04-13 17:56:47,665 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ================ model_fn ================
2021-04-13 17:56:47,665 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model_dir ['/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/handler_service.py', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/MAR-INF', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/finetuned.pth', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/__pycache__', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/model.pkl', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/code']
2021-04-13 17:56:47,665 [INFO ] epollEventLoopGroup-5-2 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2021-04-13 17:56:47,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2021-04-13 17:56:47,666 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.BatchAggregator - Load model failed: model, error: Worker died.
2021-04-13 17:56:47,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2021-04-13 17:56:47,666 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-model_1-stderr
2021-04-13 17:56:47,667 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-model_1-stdout
2021-04-13 17:56:47,667 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.6/site-packages/ts/model_service_worker.py", line 182, in <module>




2021-04-13 17:56:37,713 [INFO ] W-9000-model_1 ACCESS_LOG - /10.32.0.2:35632 "GET /ping HTTP/1.1" 200 0
--
2021-04-13 17:56:37,713 [INFO ] W-9000-model_1 TS_METRICS - Requests2XX.Count:1\|#Level:Host\|#hostname:model.aws.local,timestamp:null
2021-04-13 17:56:38,635 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.ts.sock.9000
2021-04-13 17:56:38,635 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]126
2021-04-13 17:56:38,635 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2021-04-13 17:56:38,635 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.13
2021-04-13 17:56:38,636 [INFO ] W-9000-model_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2021-04-13 17:56:38,637 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2021-04-13 17:56:40,665 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ================ model_fn ================
2021-04-13 17:56:40,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model_dir ['/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/handler_service.py', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/MAR-INF', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/finetuned.pth', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/__pycache__', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/model.pkl', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/code']
2021-04-13 17:56:40,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2021-04-13 17:56:40,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2021-04-13 17:56:40,667 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2021-04-13 17:56:40,667 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.6/site-packages/ts/model_service_worker.py", line 182, in <module>
2021-04-13 17:56:40,667 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2021-04-13 17:56:40,668 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.6/site-packages/ts/model_service_worker.py", line 154, in run_server
2021-04-13 17:56:40,668 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2021-04-13 17:56:40,667 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.BatchAggregator - Load model failed: model, error: Worker died.
2021-04-13 17:56:40,668 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-model_1-stderr
2021-04-13 17:56:40,668 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-model_1-stdout
2021-04-13 17:56:40,669 [INFO ] W-9000-model_1 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 5 seconds.
2021-04-13 17:56:40,669 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-model_1-stdout
2021-04-13 17:56:40,692 [INFO ] W-9000-model_1-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-model_1-stderr
2021-04-13 17:56:42,713 [INFO ] W-9000-model_1 ACCESS_LOG - /10.32.0.2:35632 "GET /ping HTTP/1.1" 200 1
2021-04-13 17:56:42,713 [INFO ] W-9000-model_1 TS_METRICS - Requests2XX.Count:1\|#Level:Host\|#hostname:model.aws.local,timestamp:null
2021-04-13 17:56:45,798 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.ts.sock.9000
2021-04-13 17:56:45,798 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]142
2021-04-13 17:56:45,798 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2021-04-13 17:56:45,799 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.13
2021-04-13 17:56:45,799 [INFO ] W-9000-model_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2021-04-13 17:56:45,800 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2021-04-13 17:56:47,665 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ================ model_fn ================
2021-04-13 17:56:47,665 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model_dir ['/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/handler_service.py', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/MAR-INF', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/finetuned.pth', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/__pycache__', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/model.pkl', '/home/model-server/tmp/models/f0fd3b17bf9546dcbf726dc39956b075/code']
2021-04-13 17:56:47,665 [INFO ] epollEventLoopGroup-5-2 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2021-04-13 17:56:47,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2021-04-13 17:56:47,666 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.BatchAggregator - Load model failed: model, error: Worker died.
2021-04-13 17:56:47,666 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2021-04-13 17:56:47,666 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-model_1-stderr
2021-04-13 17:56:47,667 [WARN ] W-9000-model_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-model_1-stdout
2021-04-13 17:56:47,667 [INFO ] W-9000-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.6/site-packages/ts/model_service_worker.py", line 182, in <module>

```

app code:

i```
mport argparse
import logging, requests, os, io, glob, time, json
from fastai.text.all import *
import pandas as pd

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

JSON_CONTENT_TYPE = 'application/json'

def train(args):
    print("================ train ================")
    print("args.data_dir",glob.glob(args.data_dir+"/*"))
    print("args.model_dir",glob.glob(args.model_dir+"/*"))
          
    df = pd.read_csv(os.path.join(args.data_dir, "sentiment140_cleaned.csv"))
    dls_lm = TextDataLoaders.from_df(df, path=args.data_dir, valid_pct=0.1, is_lm=True, text_col ='text')
    learn = language_model_learner(dls_lm, AWD_LSTM, drop_mult=0.3, metrics=[accuracy, Perplexity()])
    learn.fit_one_cycle(1, 1e-2)
    learn.save_encoder(args.model_dir+'/finetuned')
          
    dls_clas = TextDataLoaders.from_df(df, path=args.data_dir, text_col='text', label_col='sentiment', valid_pct=0.1, text_vocab=dls_lm.train.vocab)
          
          
    learn = text_classifier_learner(dls_clas, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
    learn = learn.load_encoder(args.model_dir+'/finetuned')
    learn.fit_one_cycle(1, 1e-2)
          
    learn.export(args.model_dir+"/model.pkl")

# loads the model into memory from disk and returns it
def model_fn(model_dir):
    print("================ model_fn ================")
    print("model_dir",glob.glob(model_dir+"/*"))
    
    learn = load_learner(model_dir+'/model.pkl')
    print("loading model",learn)
    return learn

# Deserialize the Invoke request body into an object we can perform prediction on
def input_fn(request_body, content_type=JSON_CONTENT_TYPE):
    data = json.loads(request_body)
    print("================ input_fn ================")
    print(data)
    return data

# Perform prediction on the deserialized object, with the loaded model
def predict_fn(input_object, model):
    print("================ predict_fn ================")
    print("Calling model")
    start_time = time.time()
    predict_class,predict_idx,predict_values = model.predict(input_object)
    print("--- Inference time: %s seconds ---" % (time.time() - start_time))
    print(f'Predicted class is {str(predict_class)}')
    print(f'Predict confidence score is {predict_values[predict_idx.item()].item()}')
    response = {}
    response['class'] = str(predict_class)
    response['confidence'] = predict_values[predict_idx.item()].item()
    return response

# Serialize the prediction result into the desired response content type
def output_fn(prediction, accept=JSON_CONTENT_TYPE):  
    print("================ output_fn ================")
    print('Serializing the generated output.')
    if accept == JSON_CONTENT_TYPE:
        output = json.dumps(prediction)
        return output, accept
    raise Exception('Requested unsupported ContentType in Accept: {}'.format(accept))  
    
    
if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    # Container environment
    parser.add_argument("--hosts", type=list, default=json.loads(os.environ["SM_HOSTS"]))
    parser.add_argument("--current-host", type=str, default=os.environ["SM_CURRENT_HOST"])
    parser.add_argument("--model-dir", type=str, default=os.environ["SM_MODEL_DIR"])
    parser.add_argument("--data-dir", type=str, default=os.environ["SM_CHANNEL_TRAINING"])
#     parser.add_argument("--test", type=str, default=os.environ["SM_CHANNEL_TESTING"])
    parser.add_argument("--num-gpus", type=int, default=os.environ["SM_NUM_GPUS"])

    train(parser.parse_args())
```

**Comment by tbass134** [comment]
The issue was that the model was not loaded correctly,

**Comment by kmoy1** [comment]
could you elaborate on what you mean by "model was not loaded correctly"?
