### ISSUE TITLE
SDK v2 upgrade CLI tool fails with AttributeError

### ISSUE THREAD

**Issue by hsl89** [aws/sagemaker-python-sdk#2286]
**Describe the bug**
sagemaker-upgrade-v2 not working as expected

**To reproduce**
1. Go to sagemaker-debugger/xgboost_builtin_rules/ in aws/amazon-sagemaker-examples
2. sagemaker-upgrade-v2 --in-file xgboost-regression-debugger-rules.ipynb --out-file xgboost-regression-debugger-rules-v2.ipynb

**Expected behavior**

**Screenshots or logs**
```
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/sagemaker-upgrade-v2", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/sagemaker/cli/compatibility/v2/sagemaker_upgrade_v2.py", line 79, in main
    _update_file(args.in_file, args.out_file)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/sagemaker/cli/compatibility/v2/sagemaker_upgrade_v2.py", line 51, in _update_file
    updater_cls(input_path=input_file, output_path=output_file).update()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/sagemaker/cli/compatibility/v2/files.py", line 132, in update
    updated_source = self._update_code_from_cell(cell)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/sagemaker/cli/compatibility/v2/files.py", line 170, in _update_code_from_cell
    updated_ast = ASTTransformer().visit(pasta.parse(code))
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/sagemaker/cli/compatibility/v2/ast_transformer.py", line 137, in visit_Module
    self.generic_visit(node)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/ast.py", line 317, in generic_visit
    new_node = self.visit(old_value)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/sagemaker/cli/compatibility/v2/ast_transformer.py", line 84, in visit_Call
    node = function_checker.check_and_modify_node(node)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/sagemaker/cli/compatibility/v2/modifiers/modifier.py", line 25, in check_and_modify_node
    node = self.modify_node(node)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/sagemaker/cli/compatibility/v2/modifiers/image_uris.py", line 72, in modify_node
    original_args[1] = ast.Str(node.args[0].s)
AttributeError: 'Name' object has no attribute 's'
```

**System information**
Notebook Instance t2.medium

**Additional context**

**Comment by ajaykarpur** [comment]
https://github.com/aws/sagemaker-python-sdk/pull/2214 was closed. @ahsan-z-khan to provide an update.

**Comment by ahsan-z-khan** [comment]
Hi @hsl89 , I've replied on your slack message.

**Comment by martinRenou** [comment]
What was the reason for not merging the PR? Should we consider reviving it?

**Comment by akrishna1995** [comment]
Does this issue still persist? Closing this issue for now. Feel free to reopen if it still exists.
