### ISSUE TITLE
Endpoint Deserializer doesn't work no matter what I do

### ISSUE THREAD

**Issue by JayThibs** [aws/sagemaker-python-sdk#2686]
**Describe the bug**
After struggling to make the serializer work (because my images are too big when sent via JSON), I finally figured out how to send the data in numpy.ndarray for prediction. However, now I'm trying to send the data back after prediction and nothing I do seems to work. All errors I'm getting are similar to this:

> TypeError: Object of type 'BytesIO' is not JSON serializable

I get the 'numpy.ndarray' is not JSON serializable if I don't create buffer beforehand. Issues like this come up whether I use `NumpyDeserializer`, `JSONDeserializer` or `BytesDeserializer`. I just can't seem to get things in the right format. What's worse is that it's frustrating how I need to deploy and wait 10 minutes every new test I do...

Anyways, the data comes from a semantic segmentation prediction of a model and it is basically an ndarray of shape (1, 2, 512, 512) with 0s and 1s. I tried converting it into a list and using `json.dumps`, I've tried storing the ndarray in `BytesIO()` with `np.save`, I've tried sending the array just as is or using `np.asarray(array_var)`; nothing seems to work.

I don't know why JSON is even in the picture when I use `NumpyDeserializer`. But it runs the following line according to CloudWatch: `json_value = json.dumps(val, indent=2).encode("utf-8")`

It may have to do with the encoding? But then again, it makes sense it's not JSON serializable since I'm outputting BytesIO or a numpy array. It should work if it was a list though...

**Expected behavior**
I get my prediction back as a numpy array. At this point I don't really care in what format I receive it in, I just want to get the output of my prediction as long as I can convert it back into its original shape.

**System information**
- **SageMaker Python SDK version**: 2.59.7
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: PyTorch 1.8.1.
- **Framework version**: 1.8.1.
- **Python version**: 3.6
- **CPU or GPU**: ml.m4.xlarge
- **Custom Docker image (Y/N)**: N

**Additional Information:**

Error message:

```


---------------------------------------------------------------------------
ModelError                                Traceback (most recent call last)
<ipython-input-144-65f6749dd24c> in <module>
----> 1 results = predictor.predict(x_arr)

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/sagemaker/predictor.py in predict(self, data, initial_args, target_model, target_variant, inference_id)
    159             data, initial_args, target_model, target_variant, inference_id
    160         )
--> 161         response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
    162         return self._handle_response(response)
    163 

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    384                     "%s() only accepts keyword arguments." % py_operation_name)
    385             # The "self" in this scope is referring to the BaseClient.
--> 386             return self._make_api_call(operation_name, kwargs)
    387 
    388         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    703             error_code = parsed_response.get("Error", {}).get("Code")
    704             error_class = self.exceptions.from_code(error_code)
--> 705             raise error_class(parsed_response, operation_name)
    706         else:
    707             return parsed_response

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (503) from model with message "{
  "code": 503,
  "type": "InternalServerException",
  "message": "Unsupported model output data type."
}
". See https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/sagemaker/Endpoints/floodwater-tuning-211001-2300-002-99c3af83-2021-10-04-04-06-15 in account 034262493329 for more information.
```

CloudWatch Errors:

```


2021-10-04 04:21:03,693 [INFO ] W-9000-model_1-stdout MODEL_LOG -     json_value = json.dumps(val, indent=2).encode("utf-8")
--
2021-10-04 04:21:03,696 [INFO ] W-9000-model_1-stdout MODEL_LOG -   File "/opt/conda/lib/python3.6/json/__init__.py", line 238, in dumps
2021-10-04 04:21:03,696 [INFO ] W-9000-model_1-stdout MODEL_LOG -   File "/opt/conda/lib/python3.6/json/encoder.py", line 201, in encode
2021-10-04 04:21:03,697 [INFO ] W-9000-model_1-stdout MODEL_LOG -   File "/opt/conda/lib/python3.6/json/encoder.py", line 437, in _iterencode
2021-10-04 04:21:03,697 [INFO ] W-9000-model_1-stdout MODEL_LOG -   File "/opt/conda/lib/python3.6/json/encoder.py", line 180, in default
2021-10-04 04:21:03,697 [INFO ] W-9000-model_1-stdout MODEL_LOG - TypeError: Object of type 'BytesIO' is not JSON serializable
```

**Comment by JayThibs** [comment]
I was able to resolve this. Still running into some other issues, but I was able to get a response back.

I used NumpySerializer() and JSONDeserializer(). I wasn't able to use JSONSerializer since the data was bigger than 5 MB when sent to the endpoint. However, it seems this was not an issue when I sent the model prediction back to the client. This is may be because I converted the array in np.uint8 instead of np.float32. Here's what I used in output_fn():

```
res = predictions.astype(np.uint8)
res = json.dumps(res.tolist())
return res
```

Turning the array into a list usually works well IF the JSON doesn't get too big. Looks like it was fine for deserialization in my case.
