### ISSUE TITLE
Failed to run: ['docker-compose'], Process exited with code: 130

### ISSUE THREAD

**Issue by migueldft** [aws/sagemaker-python-sdk#2862]
**Describe the bug**
I am trying to test a batch/transform job locally on my computer but I am getting the following error at the end of the **transform** method.

"RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmpim0702so/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 130"

**To reproduce**

sklearn = SKLearn(
    entry_point='script.py',
    framework_version='0.23-1',
    instance_type='local',
    role=role,
    dependencies=['CustomClasses.py'],
    environment={'SAGEMAKER_REQUIREMENTS': 'requirements.txt'},
    source_dir='.',
    output_path='s3://sagemaker-us-east-1-296025910508/{}/training_jobs/'.format(project_name),
    code_location='s3://sagemaker-us-east-1-296025910508/{}/training_jobs'.format(project_name) ##Do not add a final slash
)

train_input = 's3://sagemaker-us-east-1-296025910508/sac-emails/input/training_data/poc_sac.parquet'

sklearn.fit(
    inputs={"train": train_input},
    job_name='{}-{}'.format(project_name, current_time)
)

transformer = sklearn.transformer(
    model_name='teste-miguel',
    instance_count=1,
    instance_type='local',
    output_path='s3://sagemaker-us-east-1-296025910508/teste-miguel/output/',
)

transformer.transform(
    's3://sagemaker-us-east-1-296025910508/sac-emails/input/payload.json',
    content_type='application/json'
)

**Screenshots or logs**
`Attaching to son7qsalar-algo-1-66sh7
son7qsalar-algo-1-66sh7  | 2022-01-21 17:37:44,390 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
son7qsalar-algo-1-66sh7  | 2022-01-21 17:37:44,396 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
son7qsalar-algo-1-66sh7  | 2022-01-21 17:37:44,397 INFO - sagemaker-containers - nginx config: 
son7qsalar-algo-1-66sh7  | worker_processes auto;
son7qsalar-algo-1-66sh7  | daemon off;
son7qsalar-algo-1-66sh7  | pid /tmp/nginx.pid;
son7qsalar-algo-1-66sh7  | error_log  /dev/stderr;
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  | worker_rlimit_nofile 4096;
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  | events {
son7qsalar-algo-1-66sh7  |   worker_connections 2048;
son7qsalar-algo-1-66sh7  | }
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  | http {
son7qsalar-algo-1-66sh7  |   include /etc/nginx/mime.types;
son7qsalar-algo-1-66sh7  |   default_type application/octet-stream;
son7qsalar-algo-1-66sh7  |   access_log /dev/stdout combined;
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  |   upstream gunicorn {
son7qsalar-algo-1-66sh7  |     server unix:/tmp/gunicorn.sock;
son7qsalar-algo-1-66sh7  |   }
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  |   server {
son7qsalar-algo-1-66sh7  |     listen 8080 deferred;
son7qsalar-algo-1-66sh7  |     client_max_body_size 0;
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  |     keepalive_timeout 3;
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  |     location ~ ^/(ping|invocations|execution-parameters) {
son7qsalar-algo-1-66sh7  |       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
son7qsalar-algo-1-66sh7  |       proxy_set_header Host $http_host;
son7qsalar-algo-1-66sh7  |       proxy_redirect off;
son7qsalar-algo-1-66sh7  |       proxy_read_timeout 60s;
son7qsalar-algo-1-66sh7  |       proxy_pass http://gunicorn;
son7qsalar-algo-1-66sh7  |     }
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  |     location / {
son7qsalar-algo-1-66sh7  |       return 404 "{}";
son7qsalar-algo-1-66sh7  |     }
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  |   }
son7qsalar-algo-1-66sh7  | }
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  | 
son7qsalar-algo-1-66sh7  | 2022/01/21 17:37:44 [crit] 20#20: *1 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:37:44 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
son7qsalar-algo-1-66sh7  | 2022-01-21 17:37:45,877 INFO - sagemaker-containers - Module script does not provide a setup.py. 
son7qsalar-algo-1-66sh7  | Generating setup.py
son7qsalar-algo-1-66sh7  | 2022-01-21 17:37:45,878 INFO - sagemaker-containers - Generating setup.cfg
son7qsalar-algo-1-66sh7  | 2022-01-21 17:37:45,879 INFO - sagemaker-containers - Generating MANIFEST.in
son7qsalar-algo-1-66sh7  | 2022-01-21 17:37:45,880 INFO - sagemaker-containers - Installing module with the following command:
son7qsalar-algo-1-66sh7  | /miniconda3/bin/python3 -m pip install . -r requirements.txt
son7qsalar-algo-1-66sh7  | Processing /opt/ml/code
son7qsalar-algo-1-66sh7  |   Preparing metadata (setup.py) ... [?25ldone
son7qsalar-algo-1-66sh7  | [?25hCollecting nltk
son7qsalar-algo-1-66sh7  |   Downloading nltk-3.6.7-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 4.2 MB/s            
son7qsalar-algo-1-66sh7  | [?25hCollecting unidecode
son7qsalar-algo-1-66sh7  |   Downloading Unidecode-1.3.2-py3-none-any.whl (235 kB)
     |████████████████████████████████| 235 kB 5.4 MB/s            
son7qsalar-algo-1-66sh7  | [?25hCollecting catboost
son7qsalar-algo-1-66sh7  | 2022/01/21 17:37:49 [crit] 20#20: *3 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:37:49 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
son7qsalar-algo-1-66sh7  |   Downloading catboost-1.0.4-cp37-none-manylinux1_x86_64.whl (76.1 MB)
     |██████████████▍                 | 34.2 MB 8.3 MB/s eta 0:00:062022/01/21 17:37:54 [crit] 20#20: *5 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:37:54 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
     |██████████████████████████████▋ | 72.8 MB 8.3 MB/s eta 0:00:01 2022/01/21 17:37:59 [crit] 20#20: *7 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:37:59 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
     |████████████████████████████████| 76.1 MB 88 kB/s              
son7qsalar-algo-1-66sh7  | [?25hCollecting imblearn
son7qsalar-algo-1-66sh7  |   Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
son7qsalar-algo-1-66sh7  | Requirement already satisfied: click in /miniconda3/lib/python3.7/site-packages (from nltk->-r requirements.txt (line 1)) (8.0.3)
son7qsalar-algo-1-66sh7  | Requirement already satisfied: tqdm in /miniconda3/lib/python3.7/site-packages (from nltk->-r requirements.txt (line 1)) (4.62.3)
son7qsalar-algo-1-66sh7  | Requirement already satisfied: joblib in /miniconda3/lib/python3.7/site-packages (from nltk->-r requirements.txt (line 1)) (1.1.0)
son7qsalar-algo-1-66sh7  | Collecting regex>=2021.8.3
son7qsalar-algo-1-66sh7  |   Downloading regex-2022.1.18-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (748 kB)
     |████████████████████████████████| 748 kB 6.8 MB/s            
son7qsalar-algo-1-66sh7  | [?25hCollecting matplotlib
son7qsalar-algo-1-66sh7  |   Downloading matplotlib-3.5.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
     |████████████████████████▋       | 8.7 MB 4.8 MB/s eta 0:00:012022/01/21 17:38:04 [crit] 20#20: *9 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:38:04 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
     |████████████████████████████████| 11.2 MB 4.8 MB/s            
son7qsalar-algo-1-66sh7  | [?25hRequirement already satisfied: six in /miniconda3/lib/python3.7/site-packages (from catboost->-r requirements.txt (line 3)) (1.15.0)
son7qsalar-algo-1-66sh7  | Requirement already satisfied: numpy>=1.16.0 in /miniconda3/lib/python3.7/site-packages (from catboost->-r requirements.txt (line 3)) (1.19.2)
son7qsalar-algo-1-66sh7  | Requirement already satisfied: scipy in /miniconda3/lib/python3.7/site-packages (from catboost->-r requirements.txt (line 3)) (1.5.3)
son7qsalar-algo-1-66sh7  | Collecting plotly
son7qsalar-algo-1-66sh7  |   Downloading plotly-5.5.0-py2.py3-none-any.whl (26.5 MB)
     |████████████████████████████████| 26.5 MB 8.3 MB/s eta 0:00:01 2022/01/21 17:38:09 [crit] 20#20: *11 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:38:09 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
     |████████████████████████████████| 26.5 MB 8.3 MB/s             
son7qsalar-algo-1-66sh7  | [?25hCollecting graphviz
son7qsalar-algo-1-66sh7  |   Downloading graphviz-0.19.1-py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 1.5 MB/s            
son7qsalar-algo-1-66sh7  | [?25hRequirement already satisfied: pandas>=0.24.0 in /miniconda3/lib/python3.7/site-packages (from catboost->-r requirements.txt (line 3)) (1.1.3)
son7qsalar-algo-1-66sh7  | Collecting imbalanced-learn
son7qsalar-algo-1-66sh7  |   Downloading imbalanced_learn-0.9.0-py3-none-any.whl (199 kB)
     |████████████████████████████████| 199 kB 13.4 MB/s            
son7qsalar-algo-1-66sh7  | [?25hRequirement already satisfied: python-dateutil>=2.7.3 in /miniconda3/lib/python3.7/site-packages (from pandas>=0.24.0->catboost->-r requirements.txt (line 3)) (2.8.1)
son7qsalar-algo-1-66sh7  | Requirement already satisfied: pytz>=2017.2 in /miniconda3/lib/python3.7/site-packages (from pandas>=0.24.0->catboost->-r requirements.txt (line 3)) (2021.3)
son7qsalar-algo-1-66sh7  | Requirement already satisfied: importlib-metadata in /miniconda3/lib/python3.7/site-packages (from click->nltk->-r requirements.txt (line 1)) (4.8.2)
son7qsalar-algo-1-66sh7  | Collecting scikit-learn>=1.0.1
son7qsalar-algo-1-66sh7  |   Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
     |███████████████████████         | 17.8 MB 11.5 MB/s eta 0:00:012022/01/21 17:38:14 [crit] 20#20: *13 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:38:14 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
     |████████████████████████████████| 24.8 MB 8.0 MB/s             
son7qsalar-algo-1-66sh7  | [?25hRequirement already satisfied: threadpoolctl>=2.0.0 in /miniconda3/lib/python3.7/site-packages (from imbalanced-learn->imblearn->-r requirements.txt (line 4)) (3.0.0)
son7qsalar-algo-1-66sh7  | Collecting pyparsing>=2.2.1
son7qsalar-algo-1-66sh7  |   Downloading pyparsing-3.0.7-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 3.1 MB/s             
son7qsalar-algo-1-66sh7  | [?25hCollecting fonttools>=4.22.0
son7qsalar-algo-1-66sh7  |   Downloading fonttools-4.28.5-py3-none-any.whl (890 kB)
     |████████████████████████████████| 890 kB 8.9 MB/s            
son7qsalar-algo-1-66sh7  | [?25hCollecting kiwisolver>=1.0.1
son7qsalar-algo-1-66sh7  |   Downloading kiwisolver-1.3.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 10.3 MB/s            
son7qsalar-algo-1-66sh7  | [?25hRequirement already satisfied: pillow>=6.2.0 in /miniconda3/lib/python3.7/site-packages (from matplotlib->catboost->-r requirements.txt (line 3)) (8.4.0)
son7qsalar-algo-1-66sh7  | Collecting packaging>=20.0
son7qsalar-algo-1-66sh7  |   Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 2.4 MB/s             
son7qsalar-algo-1-66sh7  | [?25hCollecting cycler>=0.10
son7qsalar-algo-1-66sh7  |   Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
son7qsalar-algo-1-66sh7  | Collecting tenacity>=6.2.0
son7qsalar-algo-1-66sh7  |   Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
son7qsalar-algo-1-66sh7  | Requirement already satisfied: typing-extensions>=3.6.4 in /miniconda3/lib/python3.7/site-packages (from importlib-metadata->click->nltk->-r requirements.txt (line 1)) (4.0.1)
son7qsalar-algo-1-66sh7  | Requirement already satisfied: zipp>=0.5 in /miniconda3/lib/python3.7/site-packages (from importlib-metadata->click->nltk->-r requirements.txt (line 1)) (3.6.0)
son7qsalar-algo-1-66sh7  | Building wheels for collected packages: script
son7qsalar-algo-1-66sh7  |   Building wheel for script (setup.py) ... [?25ldone
son7qsalar-algo-1-66sh7  | [?25h  Created wheel for script: filename=script-1.0.0-py2.py3-none-any.whl size=28785 sha256=38a6642803b2b7e6e1ebaf72362c8a9f81b4120c862ac8d02d5b8c8b91a9eb68
son7qsalar-algo-1-66sh7  |   Stored in directory: /home/model-server/tmp/pip-ephem-wheel-cache-it4oq_bl/wheels/3e/0f/51/2f1df833dd0412c1bc2f5ee56baac195b5be563353d111dca6
son7qsalar-algo-1-66sh7  | Successfully built script
son7qsalar-algo-1-66sh7  | Installing collected packages: pyparsing, tenacity, scikit-learn, packaging, kiwisolver, fonttools, cycler, regex, plotly, matplotlib, imbalanced-learn, graphviz, unidecode, script, nltk, imblearn, catboost
son7qsalar-algo-1-66sh7  |   Attempting uninstall: scikit-learn
son7qsalar-algo-1-66sh7  |     Found existing installation: scikit-learn 0.23.2
son7qsalar-algo-1-66sh7  |     Uninstalling scikit-learn-0.23.2:
son7qsalar-algo-1-66sh7  | 2022/01/21 17:38:19 [crit] 20#20: *15 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:38:19 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
son7qsalar-algo-1-66sh7  |       Successfully uninstalled scikit-learn-0.23.2
son7qsalar-algo-1-66sh7  | 2022/01/21 17:38:24 [crit] 20#20: *17 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:38:24 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
son7qsalar-algo-1-66sh7  | 2022/01/21 17:38:29 [crit] 20#20: *19 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:38:29 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
son7qsalar-algo-1-66sh7  | 2022/01/21 17:38:34 [crit] 20#20: *21 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:38:34 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
son7qsalar-algo-1-66sh7  | 2022/01/21 17:38:39 [crit] 20#20: *23 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /ping HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/ping", host: "localhost:8080"
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:38:39 +0000] "GET /ping HTTP/1.1" 502 182 "-" "-"
son7qsalar-algo-1-66sh7  | [31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
son7qsalar-algo-1-66sh7  | sagemaker-sklearn-container 2.0 requires scikit-learn==0.23.2, but you have scikit-learn 1.0.2 which is incompatible.[0m
son7qsalar-algo-1-66sh7  | Successfully installed catboost-1.0.4 cycler-0.11.0 fonttools-4.28.5 graphviz-0.19.1 imbalanced-learn-0.9.0 imblearn-0.0 kiwisolver-1.3.2 matplotlib-3.5.1 nltk-3.6.7 packaging-21.3 plotly-5.5.0 pyparsing-3.0.7 regex-2022.1.18 scikit-learn-1.0.2 script-1.0.0 tenacity-8.0.1 unidecode-1.3.2
son7qsalar-algo-1-66sh7  | [33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m
son7qsalar-algo-1-66sh7  | [nltk_data] Downloading package stopwords to /root/nltk_data...
son7qsalar-algo-1-66sh7  | [nltk_data]   Unzipping corpora/stopwords.zip.
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [49] [INFO] Starting gunicorn 20.0.4
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [49] [INFO] Listening at: unix:/tmp/gunicorn.sock (49)
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [49] [INFO] Using worker: gevent
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [52] [INFO] Booting worker with pid: 52
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [53] [INFO] Booting worker with pid: 53
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [54] [INFO] Booting worker with pid: 54
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [55] [INFO] Booting worker with pid: 55
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [56] [INFO] Booting worker with pid: 56
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [64] [INFO] Booting worker with pid: 64
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [65] [INFO] Booting worker with pid: 65
son7qsalar-algo-1-66sh7  | [2022-01-21 17:38:44 +0000] [66] [INFO] Booting worker with pid: 66
son7qsalar-algo-1-66sh7  | 2022-01-21 17:38:45,521 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
son7qsalar-algo-1-66sh7  | [nltk_data] Downloading package stopwords to /root/nltk_data...
son7qsalar-algo-1-66sh7  | [nltk_data]   Package stopwords is already up-to-date!
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:39:17 +0000] "GET /ping HTTP/1.1" 200 0 "-" "-"
son7qsalar-algo-1-66sh7  | 2022-01-21 17:39:17,151 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
son7qsalar-algo-1-66sh7  | [nltk_data] Downloading package stopwords to /root/nltk_data...
son7qsalar-algo-1-66sh7  | [nltk_data]   Package stopwords is already up-to-date!
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:39:50 +0000] "GET /execution-parameters HTTP/1.1" 404 232 "-" "-"
son7qsalar-algo-1-66sh7  | 2022-01-21 17:39:51,398 INFO - sagemaker-containers - No GPUs detected (normal if no gpus installed)
son7qsalar-algo-1-66sh7  | [nltk_data] Downloading package stopwords to /root/nltk_data...
son7qsalar-algo-1-66sh7  | [nltk_data]   Package stopwords is already up-to-date!
son7qsalar-algo-1-66sh7  | PREDICTT
son7qsalar-algo-1-66sh7  | PARTE1
son7qsalar-algo-1-66sh7  | PARTE2
son7qsalar-algo-1-66sh7  | PARTE3
son7qsalar-algo-1-66sh7  | 172.18.0.1 - - [21/Jan/2022:17:40:24 +0000] "POST /invocations HTTP/1.1" 200 666 "-" "-"
Gracefully stopping... (press Ctrl+C again to force)

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/miguel.filho/.local/lib/python3.8/site-packages/sagemaker/local/image.py", line 837, in run
    _stream_output(self.process)
  File "/home/miguel.filho/.local/lib/python3.8/site-packages/sagemaker/local/image.py", line 899, in _stream_output
    raise RuntimeError("Process exited with code: %s" % exit_code)
RuntimeError: Process exited with code: 130

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/miguel.filho/.local/lib/python3.8/site-packages/sagemaker/local/image.py", line 842, in run
    raise RuntimeError(msg)
RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmpim0702so/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 130
`

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.72.3
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: SKLearn
- **Framework version**:0.23-1
- **Python version**:3.85
- **CPU or GPU**:CPU
- **Custom Docker image (Y/N)**:N

**Comment by mufaddal-rohawala** [comment]
@migueldft what version of docker compose is installed in the system where the above faliure occurs?

**Comment by mollyheamazon** [comment]
Closing this issue since there is not enough data to replicate it. Please reopen if there are further questions.
