### ISSUE TITLE
Clarify throws IndexOutOfBounds when running run_pre_training_bias

### ISSUE THREAD

**Issue by rddefauw** [aws/sagemaker-python-sdk#3260]
It appears that Clarify requires a minimum number of rows in the data set when calling run_pre_training_bias.  Otherwise it throws an IndexOutOfBounds error.

The data set size limitation should be noted in the docs, and a clearer error message would help as well.

The stack trace is:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/analyzer/analysis_driver.py", line 438, in main
    violations = run_analysis(configs)
  File "/usr/local/lib/python3.9/site-packages/analyzer/analysis_driver.py", line 381, in run_analysis
    metrics_results: MetricResults = run_pandas_analysis(configs)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/analyzer/analysis_driver.py", line 266, in run_pandas_analysis
    pre_training_bias_analyzer.analyze(
  File "/usr/local/lib/python3.9/site-packages/analyzer/bias/bias_analyzer.py", line 111, in analyze
    metrics_result, value_or_threshold_label = self.generate_bias_report(
  File "/usr/local/lib/python3.9/site-packages/analyzer/bias/pretraining_bias_analyzer.py", line 37, in generate_bias_report
    metrics_result = bias_report(
  File "/usr/local/lib/python3.9/site-packages/smclarify/bias/report.py", line 387, in bias_report
    return _report(df, facet_column, label_column, stage_type, metrics_to_run, predicted_label_column, group_variable)
  File "/usr/local/lib/python3.9/site-packages/smclarify/bias/report.py", line 455, in _report
    facet_data_type, facet_data_series = common.ensure_series_data_type(df[facet_column.name], sensitive_facet_values)
  File "/usr/local/lib/python3.9/site-packages/smclarify/bias/metrics/common.py", line 167, in ensure_series_data_type
    if not (isinstance(values[0], int) or isinstance(values[0], float)):
```

**Comment by larroy** [comment]
Hello. I think I have fixed this recently: https://github.com/aws/amazon-sagemaker-clarify/pull/121
It will be also deployed soon. Did you run on this error locally or in SageMaker?
