### ISSUE TITLE
PropertyFile for ProcessingStep using FrameworkProcessor and step_args not recognized.

### ISSUE THREAD

**Issue by carlryn** [aws/sagemaker-python-sdk#3642]
**Describe the bug**
PropertyFile added to `ProcessingStep` using a `FrameworkProcessor` with `step_args` but it does not recognize that it exists.
When the pipeline is updated it fails to recognize the PropertyFile.

**To reproduce**
Execute the ProcessingStep in a pipeline. It fails when updating the pipeline.

**Expected behavior**
I'm expecting this to work since I have other ProcessingSteps that are not using the FrameworkProcessor working.

**Screenshots or logs**
Parts of the step:
```
from sagemaker.processing import (
    ProcessingInput,
    ProcessingOutput,
    FrameworkProcessor
)
from sagemaker.workflow.pipeline_context import PipelineSession
from sagemaker.workflow.properties import PropertyFile
from sagemaker.workflow.steps import (
    ProcessingStep,
)
from sagemaker.pytorch.estimator import PyTorch

processor = FrameworkProcessor(
    estimator_cls=PyTorch,
    framework_version="1.10", # Ignored when image uri is provided
    role=role,
    py_version="py38",
    # sagemaker_session=session,
    sagemaker_session=PipelineSession(),
    base_job_name=base_job_prefix + "/evaluation2",
    instance_count=1,
    instance_type=instance_type,
    command="python3",
)

step_args = processor.run(source_dir="pipelines/evaluation/inference", dependencies=dependencies, code="evaluation.py")

property_output_name = "evaluationInference"
evaluation_report = PropertyFile(
    name="EvaluationInferenceReport",
    output_name=property_output_name,
    path="end2end-metrics.json",
)

processing_step = ProcessingStep(
    "EvaluateInference",
    step_args=step_args,
    cache_config=CACHE_CONFIG,
    inputs=[
        ProcessingInput(
            source=model_s3_path,
            destination="/opt/ml/processing/model",
        ),
        ProcessingInput(
            source=dataset_s3_path,
            destination="/opt/ml/processing/test",
        ),
    ],
    outputs=[
        ProcessingOutput(
            output_name=property_output_name, source="/opt/ml/processing/evaluation/metrics"
        )
    ],
    property_files=[evaluation_report]
)

```

Parts of the execution and error msg:
```
      "Name": "EvaluateInference",
      "PropertyFiles": [
        {
          "FilePath": "end2end-metrics.json",
          "OutputName": "evaluationInference",
          "PropertyFileName": "EvaluationInferenceReport"
        }
      ],
      "Type": "Processing"
    }
  ],
  "Version": "2020-12-01"
}INFO:sagemaker.image_uris:Defaulting to the only supported framework/algorithm version: latest.
INFO:sagemaker.image_uris:Ignoring unnecessary instance type: None.
INFO:sagemaker.image_uris:Defaulting to the only supported framework/algorithm version: latest.
INFO:sagemaker.image_uris:Ignoring unnecessary instance type: None.
INFO:sagemaker.processing:Uploaded pipelines/evaluation/inference to ...
INFO:sagemaker.processing:runproc.sh uploaded to ...
Job Name: ...
Inputs: ...
Outputs:  []
Traceback (most recent call last):
  File "scripts/run_pipeline.py", line 179, in <module>
    main(
  File "scripts/run_pipeline.py", line 88, in main
    upsert_response = pipeline.upsert(
  File "/usr/local/lib/python3.8/site-packages/sagemaker/workflow/pipeline.py", line 257, in upsert
    response = self.update(role_arn, description)
  File "/usr/local/lib/python3.8/site-packages/sagemaker/workflow/pipeline.py", line 222, in update
    return self.sagemaker_session.sagemaker_client.update_pipeline(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the UpdatePipeline operation: Property file OutputName: [evaluationInference] does not exist in ProcessingJob outputs
make: *** [Makefile:99: docker-run-staging] Error 1
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
2.131
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
Pipelines, Pytorch, FrameworkProcessor, ProcessingStep
- **Framework version**:
Pytorch=1.0.1
- **Python version**:
3.8

**Additional context**
Would be happy to provide more information if needed.

**Comment by qidewenwhen** [comment]
Hi @carlryn, thanks for reaching out! I can reproduce the error with your code snippet.

According to your code sample, seems you're mix using both the new step interface (via supplying `step_args` to `ProcessingStep`) and the obsoleted step interface (passing `inputs` and `outputs` directly to the `ProcessingStep`). As our logic honors the new interface, the `inputs` and `outputs` given to `ProcessingStep` are ignored, that's why you saw this error message: `botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the UpdatePipeline operation: Property file OutputName: [evaluationInference] does not exist in ProcessingJob outputs`.

Thus you can resolve the issue by simply updating your code as the following, which works on my side:
```
    processor = FrameworkProcessor(...)
    step_args = processor.run(
        source_dir="pipelines/evaluation/inference", 
        dependencies=dependencies
        code="evaluation.py",
        inputs=[
                ProcessingInput(
                    source=model_s3_path,
                    destination="/opt/ml/processing/model",
                ),
                ProcessingInput(
                    source=dataset_s3_path,
                    destination="/opt/ml/processing/test",
                ),
        ],
        outputs=[
                ProcessingOutput(
                    output_name=property_output_name, source="/opt/ml/processing/evaluation/metrics"
                )
        ],
    )  # All processor.run args should go here
...
    evaluation_report = PropertyFile(
        name="EvaluationInferenceReport",
        output_name=property_output_name,
        path="end2end-metrics.json",
    )

    step_process = ProcessingStep(
        "EvaluateInference",
        step_args=step_args,
        cache_config=CACHE_CONFIG,
        property_files=[evaluation_report],
    )
```
Please let us know if this works for you and find more info for the new interface in https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_model_building_pipeline.html#processingstep

**Comment by carlryn** [comment]
Thanks for the answer, I'm able to make this work. However, I would like to point out that this is a very non-trivial behavior from my point of view. I would suggest one of the following two modifications:

1. Arguments not provided in the processor.run should be taken from the ProcessingStep. 
2. Warning that some arguments will be ignored.

**Comment by qidewenwhen** [comment]
Closing the issue as it's not a customer blocker anymore. The PR https://github.com/aws/sagemaker-python-sdk/pull/3814 will be refined and republished.
Feel free to reopen if you have any further questions. Thanks!
