### ISSUE TITLE
Deploy Falcon-7b model on Sagemaker endpoint

### ISSUE THREAD

**Issue by karthikgali** [aws/sagemaker-python-sdk#3905]
**Describe the bug**

I am trying to deploy "tiiuae/falcon-7b" model on Sagemaker endpoint based on the steps mentioned in this blog:
https://huggingface.co/blog/sagemaker-huggingface-llm

However, I am getting below error:
ValueError: Loading tiiuae/falcon-7b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

**To reproduce**
Try the steps mentioned here:
https://huggingface.co/blog/sagemaker-huggingface-llm

**Expected behavior**
Able to deploy the Falcon model on Sagemaker endpoint

**Screenshots or logs**

ValueError: Loading tiiuae/falcon-7b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.162.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:torch==1.13.1
- **Framework version**:
- **Python version**:Python 3.9.15
- **CPU or GPU**:GPU
- **Custom Docker image (Y/N)**:N

**Additional context**

**Comment by mufaddal-rohawala** [comment]
Thanks for reaching out to SageMaker! @karthikgali is there more error tracelogs available for debug?

**Comment by karthikgali** [comment]
Hi @mufaddal-rohawala 

sure, please find the required details below:
Logs:

#033[2m2023-06-07T07:27:13.626137Z#033[0m #033[31mERROR#033[0m #033[1mshard-manager#033[0m: #033[2mtext_generation_launcher#033[0m#033[2m:#033[0m Error when initializing model

Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 58, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 143, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)

> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 112, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 115, in get_model
    config = AutoConfig.from_pretrained(model_id, revision=revision)
  File "/usr/src/transformers/src/transformers/models/auto/configuration_auto.py", line 913, in from_pretrained
    raise ValueError(

ValueError: Loading tiiuae/falcon-7b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
 #033[2m#033[3mrank#033[0m#033[2m=#033[0m1#033[0m

--------------------------------------------------------------------------

I am getting this error at deploy step. (llm_model.deploy())

Please let me know if you need more details.

**Comment by mufaddal-rohawala** [comment]
Thanks, this does not seem to be an issue related to SageMaker Python SDK, seems like the issue occurs during model deploy to SageMaker. I will consult internally with the endpoint team.

**Comment by mufaddal-rohawala** [comment]
@karthikgali Can you please refer to the latest blog, https://www.philschmid.de/sagemaker-falcon-llm.

https://huggingface.co/blog/sagemaker-huggingface-llm needs a correction which is on SageMaker-HuggingFace's radar.

Please reopen the issue if issue still persists.

**Comment by philschmid** [comment]
Blogs are updated

**Comment by walkingerica** [comment]
I can reproduce this issue with p3.2xlarge, but for g5.2xlarge, it works. Any hints for this? Thank you!

**Comment by philschmid** [comment]
p3.2xlarge is too small to run the model

**Comment by pnkr01** [comment]
I want to know how much resources will it take to train and run this model, like Ram, GPU, like what will be the cost of running it on aws per month??

**Comment by w601sxs** [comment]
Has this been fixed in the SDK? I still get errors with the the image version 1.1.0


```
Loading /.sagemaker/mms/models/tiiuae__falcon-7b requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code\u003dTrue` to remove this error.
```
