### ISSUE TITLE
requirements.txt being ignored by HuggingFaceModel

### ISSUE THREAD

**Issue by greenpau** [aws/sagemaker-python-sdk#3954]
SDK version: 2.165.0

I am using `HuggingFaceModel` in the following way.

```
from sagemaker.huggingface.model import HuggingFaceModel

hf_model = HuggingFaceModel(
   model_data=s3_model_location,
   role=role,
   transformers_version="4.26",
   pytorch_version="1.13",
   py_version='py39',
   model_server_workers=1
)

predictor = hf_model.deploy(
    initial_instance_count=1,
    instance_type="ml.g4dn.xlarge",
    endpoint_name=model_endpoint_name,
)
```

In my custom `inference.py` file I am importing a package.

The import fails and I am getting:

```
2023-06-22T17:30:54,155 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Traceback (most recent call last):
2023-06-22T17:30:54,156 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.9/site-packages/sagemaker_huggingface_inference_toolkit/handler_service.py", line 219, in handle
2023-06-22T17:30:54,156 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     self.initialize(context)
2023-06-22T17:30:54,157 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.9/site-packages/sagemaker_huggingface_inference_toolkit/handler_service.py", line 74, in initialize
2023-06-22T17:30:54,157 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     self.validate_and_initialize_user_module()
2023-06-22T17:30:54,158 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.9/site-packages/sagemaker_huggingface_inference_toolkit/handler_service.py", line 251, in validate_and_initialize_user_module
2023-06-22T17:30:54,158 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     user_module = importlib.import_module(user_module_name)
2023-06-22T17:30:54,158 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
2023-06-22T17:30:54,159 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2023-06-22T17:30:54,159 [INFO ] W-9000-model ACCESS_LOG - /169.254.178.2:45818 "POST /invocations HTTP/1.1" 400 11
2023-06-22T17:30:54,159 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2023-06-22T17:30:54,160 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2023-06-22T17:30:54,160 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2023-06-22T17:30:54,161 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2023-06-22T17:30:54,161 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2023-06-22T17:30:54,162 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2023-06-22T17:30:54,163 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/opt/ml/model/inference.py", line 6, in <module>
2023-06-22T17:30:54,163 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     from InstructorEmbedding import INSTRUCTOR
2023-06-22T17:30:54,165 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'InstructorEmbedding'
2023-06-22T17:30:54,165 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - 
2023-06-22T17:30:54,165 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - During handling of the above exception, another exception occurred:
2023-06-22T17:30:54,166 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - 
2023-06-22T17:30:54,166 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Traceback (most recent call last):
2023-06-22T17:30:54,166 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.9/site-packages/mms/service.py", line 108, in predict
2023-06-22T17:30:54,167 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     ret = self._entry_point(input_batch, self.context)
2023-06-22T17:30:54,167 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/opt/conda/lib/python3.9/site-packages/sagemaker_huggingface_inference_toolkit/handler_service.py", line 243, in handle
2023-06-22T17:30:54,167 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     raise PredictionException(str(e), 400)
2023-06-22T17:30:54,168 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - mms.service.PredictionException: No module named 'InstructorEmbedding' : 400
```

I have `requirements.txt` with the following content.

```
sentence-transformers==2.2.2
InstructorEmbedding==1.0.1
numpy==1.25.0
```

It looks like it is being ignored.

Please assist.

**Comment by benjaminbrown038** [comment]
#self-assign

**Comment by greenpau** [comment]
The issue is resolved if I have `code/` directory in `model.tar.gz` file and inside it I have `inference.py` and `requirements.txt`.

If the above two files are in the root of  `model.tar.gz` file, then `requirements.txt` is being ignored.

**Comment by lucafrost** [comment]
Hey @greenpau 👋

This is expected behaviour, at least with PyTorch versions >= 1.3.1. The [SageMaker - PyTorch with Third-party Libraries](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#using-third-party-libraries) guide explains this.

See also: https://huggingface.co/docs/sagemaker/inference#user-defined-code-and-modules
