### ISSUE TITLE
Cannot schedule model quality job

### ISSUE THREAD

**Issue by Nick-McElroy** [aws/sagemaker-python-sdk#3959]
**Describe the bug**
Attempting to schedule a model quality monitoring job using `ModelQualityMonitor` and its `.create_monitoring_schedule` method will error out due to being unable to satisfy what's needed to create the schedule. Providing only the endpoint name will result in an error: 
```
"errorMessage": "An error occurred (ValidationException) when calling the CreateModelQualityJobDefinition operation: InvalidParameter: 1 validation error(s) found.\n- missing required field, CreateModelQualityJobDefinitionInput.ModelQualityJobInputs.EndpointInput.InferenceAttribute.\n",
```
While using an `EndpointInput` object errors out because `LocalPath` is required and the object takes no such parameter:
```
[ERROR] TypeError: __init__() got an unexpected keyword argument 'local_path'Traceback (most recent call last):  File "/var/task/lambda_function.py", line 18, in lambda_handler    new_schedules = start_monitor(  File "/var/task/lib/aws_lambdas/create_model_monitoring/create_model_monitoring.py", line 31, in start_monitor    endpoint_input = EndpointInput( | [ERROR] TypeError: __init__() got an unexpected keyword argument 'local_path' Traceback (most recent call last):   File "/var/task/lambda_function.py", line 18, in lambda_handler     new_schedules = start_monitor(   File "/var/task/lib/aws_lambdas/create_model_monitoring/create_model_monitoring.py", line 31, in start_monitor     endpoint_input = EndpointInput(
```

**To reproduce**
1. Instantiate a `ModelQualityMonitor` object:
```
model_monitor = ModelQualityMonitor(
                              role=AWS_ROLE,
                              instance_count=1,
                              instance_type="ml.t3.large",
                              volume_size_in_gb=4,
                              max_runtime_in_seconds=3600,
                              sagemaker_session=sagemaker_session,
        )
```
2a. Call the `.create_monitoring_schedule` function using an endpoint name as an input:
```
model_schedule = model_monitor.create_monitoring_schedule(
            monitor_schedule_name=f"{endpoint_name}-model-monitoring-schedule",
            endpoint_input=endpoint_name,
            problem_type="Regression",
            output_s3_uri=model_output_path,
            constraints=model_constraints,
            ground_truth_input=gt_dataset,
            schedule_cron_expression=CronExpressionGenerator.hourly(),
            enable_cloudwatch_metrics=True,
        )
```
2b. Call `.create_monitoring_schedule` providing an `EndpointInput` object as input:
```
endpoint_input = EndpointInput(
        endpoint_name=endpoint_name, 
        destination="",
        inference_attribute="score", 
        local_path="/opt/program"
    )

model_schedule = model_monitor.create_monitoring_schedule(
            monitor_schedule_name=f"{endpoint_name}-model-monitoring-schedule",
            endpoint_input=endpoint_input,
            problem_type="Regression",
            output_s3_uri=model_output_path,
            constraints=model_constraints,
            ground_truth_input=gt_dataset,
            schedule_cron_expression=CronExpressionGenerator.hourly(),
            enable_cloudwatch_metrics=True,
        )
```

**Expected behavior**
Expected to be able to create the model quality monitoring schedule by using one of the two above methods.

**Screenshots or logs**
Logs provided above.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:2.168.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:N/A
- **Framework version**:N/A
- **Python version**:3.9
- **CPU or GPU**:CPU
- **Custom Docker image (Y/N)**:N

**Comment by trungleduc** [comment]
Hi @Nick-McElroy, could you provide a fully reproducible code?

**Comment by trungleduc** [comment]
Closing the issue, please feel free to re-open for more discussion.
