### ISSUE TITLE
[FATAL tini (7)] exec train failed: No such file or directory

### ISSUE THREAD

**Issue by celsofranssa** [aws/sagemaker-python-sdk#4113]
**BUG Description**
I'm trying to automate and scale a large collection of experiments using AWS SageMamker via Python SDK. However, I am facing an error that does not give any direction to resolve it.

**To reproduce**
```python
role = "arn:..."

    estimator = PyTorch(
        image_uri="1...ecr...amazonaws.com/...:prototype",
        entry_point="main.py",
        role=role,
        region="us-...",
        instance_type="ml...xlarge",
        instance_count=1,
        volume_size=225,
        hyperparameters=hparams
    )
    estimator.fit()
```

**Expected behavior**
The model is expected to start to train and log metrics and losses.

**Screenshots or logs**
```python
[2023-09-10 23:08:59,329][sagemaker][INFO] - Creating training-job with name: xmtc-2023-09-11-02-08-56-094
2023-09-11 02:09:00 Starting - Starting the training job...
2023-09-11 02:09:18 Starting - Preparing the instances for training......
2023-09-11 02:10:27 Downloading - Downloading input data
2023-09-11 02:10:27 Training - Downloading the training image..................
2023-09-11 02:13:33 Training - Training image download completed. Training in progress..[FATAL tini (7)] exec train failed: No such file or directory

2023-09-11 02:14:15 Uploading - Uploading generated training model
2023-09-11 02:14:15 Failed - Training job failed
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/celso/projects/LightningPrototype/run_on_sagemaker.py", line 32, in run_on_sagemaker
    estimator.fit()
  File "/home/celso/projects/LightningPrototype/venv/lib/python3.10/site-packages/sagemaker/workflow/pipeline_context.py", line 311, in wrapper
    return run_func(*args, **kwargs)
  File "/home/celso/projects/LightningPrototype/venv/lib/python3.10/site-packages/sagemaker/estimator.py", line 1292, in fit
    self.latest_training_job.wait(logs=logs)
  File "/home/celso/projects/LightningPrototype/venv/lib/python3.10/site-packages/sagemaker/estimator.py", line 2474, in wait
    self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
  File "/home/celso/projects/LightningPrototype/venv/lib/python3.10/site-packages/sagemaker/session.py", line 4849, in logs_for_job
    _logs_for_job(self.boto_session, job_name, wait, poll, log_type, timeout)
  File "/home/celso/projects/LightningPrototype/venv/lib/python3.10/site-packages/sagemaker/session.py", line 6760, in _logs_for_job
    _check_job_status(job_name, description, "TrainingJobStatus")
  File "/home/celso/projects/LightningPrototype/venv/lib/python3.10/site-packages/sagemaker/session.py", line 6813, in _check_job_status
    raise exceptions.UnexpectedStatusException(
sagemaker.exceptions.UnexpectedStatusException: Error for Training job xmtc-2023-09-11-02-08-56-094: Failed. Reason: AlgorithmError: , exit code: 127

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Process finished with exit code 1
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: sagemaker 2.177.1
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Pytorch 2.0.1
- **Python version**: Python 3.10
- **Custom Docker image (Y/N)**: Yes, on ECR.

**Comment by nichiporenko** [comment]
The same issue when switched to new custom Docker image. 
In the logs just: `[FATAL tini (7)] exec train failed: No such file or directory`

**Comment by bhupendra-riotinto** [comment]
add these two lines at the bottom of your Dockerfile and will fix the error

'''
COPY code/train.py /opt/ml/code/
ENTRYPOINT ["python", "/opt/ml/code/train.py"]
'''

**Comment by celsofranssa** [comment]
> add these two lines at the bottom of your Dockerfile and will fix the error
> 
> ''' COPY code/train.py /opt/ml/code/ ENTRYPOINT ["python", "/opt/ml/code/train.py"] '''

From where does it come from?

**Comment by celsofranssa** [comment]
Hello @martinRenou. Do you have any directions here?
I've faced a related issue #4191 when using this script with `instance_type="local"`.

**Comment by cjuracek** [comment]
+1, recently stumbled onto this issue as well

**Comment by bjaeger1** [comment]
The solution for me was to add `pip install sagemaker-training` to my requirements.txt for my custom docker image.

**Comment by cjuracek** [comment]
Worked for me, thanks for the suggestion @bjaeger1 !

**Comment by jjerphan** [comment]
Indeed `sagemaker-training` (or any other tookit) is required in any custom Docker Image.

#4270 documents that custom Docker image must incorporate one of the toolkits. The documentation will be updated when the next release is publish.

Please, let me know if you have any other problem.

**Comment by omaratef3221** [comment]
I tried adding the sagemaker-tranining to my requirements.txt and tried again and I got this error:

```
2024-02-23 06:37:09 Starting - Starting the training job......
2024-02-23 06:37:46 Starting - Preparing the instances for training...
2024-02-23 06:38:35 Downloading - Downloading input data...
2024-02-23 06:38:55 Downloading - Downloading the training image......
2024-02-23 06:39:58 Training - Training image download completed. Training in progress..2024-02-23 06:40:08,652 sagemaker-training-toolkit ERROR    Reporting training FAILURE
2024-02-23 06:40:08,652 sagemaker-training-toolkit ERROR    Framework Error: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/sagemaker_training/trainer.py", line 104, in train
    runner_type=runner_type,
  File "/opt/conda/lib/python3.7/site-packages/sagemaker_training/entry_point.py", line 97, in run
    install(name=user_entry_point, path=environment.code_dir, capture_error=capture_error)
  File "/opt/conda/lib/python3.7/site-packages/sagemaker_training/entry_point.py", line 127, in install
    entry_point_type = _entry_point_type.get(path, name)
  File "/opt/conda/lib/python3.7/site-packages/sagemaker_training/_entry_point_type.py", line 43, in get
    if name.endswith(".sh"):
AttributeError: 'NoneType' object has no attribute 'endswith'
'NoneType' object has no attribute 'endswith'
2024-02-23 06:40:08,652 sagemaker-training-toolkit ERROR    Encountered exit_code 1

2024-02-23 06:40:29 Uploading - Uploading generated training model
2024-02-23 06:40:29 Failed - Training job failed
```

Any Suggestions ?

**Comment by zrecommender** [comment]
I'm seeing the same error as @omaratef3221.

**Comment by FaustineBt** [comment]
> [pip.freeze.txt](https://github.com/aws/sagemaker-python-sdk/files/15154841/pip.freeze.txt) I'm seeing the same error as @omaratef3221. See pip freeze. My container is based on python:3.9 EDIT: Actually, I was just missing `ENTRYPOINT` in the Dockerfile.

Hello, I have the same error as the one described on omaratef3221's logs.

What do you mean with "I was just missing ENTRYPOINT in the Dockerfile" ? 

Thank you for your help.

**Comment by zrecommender** [comment]
https://docs.docker.com/reference/dockerfile/#entrypoint

**Comment by sard0r** [comment]
Hello @FaustineBt  and @zrecommender. Did you guys solve this issue? if you did can you tell me what to do. I am encountering same issue over and over again.

**Comment by zrecommender** [comment]
As I explained above, my issue was that my Dockerfile was missing the ENTRYPOINT directive.
