### ISSUE TITLE
Access denied to save model checkpoint on AWS S3

### ISSUE THREAD

**Issue by celsofranssa** [aws/sagemaker-python-sdk#4201]
**Describe the bug**
Access denied to save model checkpoint on AWS S3.

**To reproduce**
```python
estimator = PyTorch(
        source_dir=os.getcwd(),
        entry_point="run.sh",
        image_uri=params.sagemaker.image_uri,
        role=role,
        region=params.sagemaker.region,
        instance_type=params.sagemaker.instance_type,
        instance_count=params.sagemaker.instance_count,
        volume_size=params.sagemaker.volume_size,
        environment={"WANDB_API_KEY": os.getenv("WANDB_API_KEY")}
    )
```
witch builds a Pytorch Lightning model with CLOUD-BASED CHECKPOINTS:
```python
# `default_root_dir` is the default path used for logs and checkpoints
trainer = Trainer(default_root_dir="s3://my_bucket/data/")
trainer.fit(model)
```
However, it seems that Sagemaker is not migrating the AWS autentications to the remote instance where the training happens.

**Screenshots or logs**
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/s3fs/core.py", line 113, in _error_wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiobotocore/client.py", line 383, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
```

**System information**
- **SageMaker Python SDK version**: sagemaker 2.192.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Pytorch 2.0.1
- **Python version**: Python 3.10
- **Docker**: 24.0.6
- **Custom Docker image (Y/N)**: Yes, on ECR.

**Comment by celsofranssa** [comment]
I keep facing this issue even passing the `sagemaker.Session()`.
Any help here?

**Comment by trungleduc** [comment]
Hi, could you post the full code for reproduction and the full error log?
Thanks

**Comment by celsofranssa** [comment]
The response took so long that it is no longer necessary.
