### ISSUE TITLE
ValueError: as_list() is not defined on an unknown TensorShape, using Tensorflow-Sagemaker Estimator

### ISSUE THREAD

**Issue by sahithyaswaminathan** [aws/sagemaker-python-sdk#422]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow
- **Framework Version**: 1.9
- **CPU or GPU**: CPU
- **Are you using a custom image**: No

### Describe the problem
I am trying to use Tensorflow estimator, using the custom model.py built using Tensorflow. 
Input: 11 features,  Output: 12 classes (I want the probability of each class as well as argmax at the output)

Here's is the model code built:
`
import numpy as np
import os
import tensorflow as tf
from tensorflow.python.estimator.export.export import build_raw_serving_input_receiver_fn
from tensorflow.python.estimator.export.export_output import PredictOutput

INPUT_TENSOR_NAME = "inputs"
SIGNATURE_NAME = "serving_default"
LEARNING_RATE = 0.001

def _input_fn(training_dir, training_filename):
    training_set =tf.contrib.learn.datasets.base.load_csv_without_header(filename=os.path.join(training_dir, training_filename), target_dtype=np.int, features_dtype=np.float32)
    #tf.estimator.inputs.numpy -> this is used to return the input function with numpy array dict
    return tf.estimator.inputs.numpy_input_fn(x={INPUT_TENSOR_NAME: np.array(training_set.data)}, 
                                                 y = np.array(training_set.target),
                                                 num_epochs = None,
                                                 shuffle = True)()
    
params = {"learning_rate": LEARNING_RATE}

def train_input_fn(training_dir, params):
    return _input_fn(training_dir, 'train.csv')

def eval_input_fn(training_dir, params):
    return _input_fn(training_dir, 'validation.csv')

def serving_input_fn(params):
    tensor = tf.placeholder(tf.float64, shape= None) #let shape=None, feed tensor of any shape
    return build_raw_serving_input_receiver_fn({INPUT_TENSOR_NAME: tensor})()

def model_fn(features, labels, mode, params):
    """Model architechture is built using this function
    Input features and labels tensors are derived from _input_fn"""
    first_hidden_layer = tf.keras.layers.Dense(100, activation='relu', name='first-layer')(features[INPUT_TENSOR_NAME])
    second_hidden_layer = tf.keras.layers.Dense(50, activation='relu')(first_hidden_layer)
    third_hidden_layer = tf.keras.layers.Dense(25, activation= 'relu')(second_hidden_layer)
    first_dropout = tf.keras.layers.Dropout(0.5)(third_hidden_layer)
    logits = tf.keras.layers.Dense(12)(first_dropout) #number of class
    predictions = {
      "classes": tf.argmax(input=logits, axis=1),
      "probabilities": tf.nn.softmax(logits, name="softmax_tensor")
      }
    if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(mode=mode, predictions=predictions)
    loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)
    if mode == tf.estimator.ModeKeys.TRAIN:
        optimizer = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE)
        train_op = optimizer.minimize(loss=loss, global_step=tf.train.get_global_step())
        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)
    eval_metric_ops = {"accuracy": tf.metrics.accuracy(labels=labels, predictions=predictions["classes"])}
    return tf.estimator.EstimatorSpec(mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)`

But, while deploying on Sagemaker's Tensorflow estimator, I'm getting the below error:
ValueError: Error training sagemaker-tensorflow-2018-10-08-05-48-18-434: Failed Reason: AlgorithmError: uncaught exception during training: as_list() is not defined on an unknown TensorShape.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 164, in train
    train_wrapper.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 73, in train
    tf.estimator.train_and_evaluate(estimator=estimator, train_spec=train_spec, eval_spec=eval_spec)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 447, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 558, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 615, in run_master
    self._start_distributed_training(saving_listeners=

Is there something which I need to change on model.py code?

Any inputs will be helpful.

**Comment by icywang86rui** [comment]
Hi,

I think the problem might be your _input_fn is not returning the function generated with numpy_input_fn. It's returning the return value of that function because the extra '()' at the end. Removing the '()' should fix it. Please let us know if the problem persists.

**Comment by laurenyu** [comment]
Closing due to inactivity. feel free to reopen if necessary
