### ISSUE TITLE
Support more flexible timestamps for metrics logging

### ISSUE THREAD

**Issue by lorenzwalthert** [aws/sagemaker-python-sdk#4240]
**Describe the feature you'd like**
Be able to log metrics to sagemaker experiments with any timestamp. Currently Logging with timestamps too far from the current time gives and error:
```python
>>> run.log_metrics()
aws sagemaker experiment Timestamps must be between two weeks before and two hours from now.
```

<details>

```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <genexpr>
  File "/Users/lorenz/git/signals/.venv/lib/python3.11/site-packages/sagemaker/experiments/_utils.py", line 90, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lorenz/git/signals/.venv/lib/python3.11/site-packages/sagemaker/experiments/run.py", line 290, in log_metric
    self._metrics_manager.log_metric(
  File "/Users/lorenz/git/signals/.venv/lib/python3.11/site-packages/sagemaker/experiments/_metrics.py", line 137, in log_metric
    metric_data = _RawMetricData(metric_name, value, timestamp, step)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lorenz/git/signals/.venv/lib/python3.11/site-packages/sagemaker/experiments/_metrics.py", line 70, in __init__
    raise ValueError(
```
</details>

I guess the underlaying assumption is that I always want to log a metric of the current wallclock time, e.g. if I run a training job and I want to record training loss. But maybe, I have a dataset with different observations that correspond to a timestamp (e.g. birth days of people I analyse) and I want to log a metric for each of them. 

An alternative to removing the checks entirely would be an option that could be set, e.g. 
```python
sagemaker.experiments.merics.allow_arbitrary_timestamps = True
```
To opt out of the default behaviour.

**How would this feature be used? Please describe.**
Logging by timestamp that is outside the arbitrary window of 2 weeks and 2h allows to use sagemaker experiments for more use-cases and allows to leverage the plotting possibilities in sagemaker studio as well.

**Describe alternatives you've considered**
Drop the information that a logged metric has a temporal dimension and use plain integer indices.

**Comment by lorenzwalthert** [comment]
I just figured out I can parametrise myself as follows since the values are set in the `_metrics.py` module:
```
sagemaker.experiments._metrics.METRIC_TS_LOWER_BOUND_TO_NOW = 1209600  # on seconds
sagemaker.experiments._metrics.METRIC_TS_UPPER_BOUND_FROM_NOW = 7200  # on seconds
```
Not sure that is officially supported though so I would not want to rely on setting private constants of that module.

**Comment by lorenzwalthert** [comment]
Does not really make that much sense anyways since in a few views in Sagemaker Studio, the last value is displayed instead of the average, so it seems to only make sense for things like loss where the final value is relevant. Hence, this seems to require a few changes in a few places so closing this as out of scope for now.
