### ISSUE TITLE
Exception when serving_input_fn is used with Keras model

### ISSUE THREAD

**Issue by sharmasx** [aws/sagemaker-python-sdk#428]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:TensorFlow (Keras)
- **Framework Version**:1.10.0
- **Python Version**:3.6
- **CPU or GPU**: GPU
- **Python SDK Version**:
- **Are you using a custom image**:No

### Describe the problem

Adding, *serving_input_fn* to a working  keras sequential model results in an exception (*KeyError: 'Contents'*).  When *serving_input_fn* is removed, code successfully runs to completion. Also using *estimator.export_savedmodel* locally works.

#### Logs:
````
2018-10-12 18:31:30,697 INFO - tensorflow - Done calling model_fn.
2018-10-12 18:31:30,698 INFO - tensorflow - Signatures INCLUDED in export for Classify: None
2018-10-12 18:31:30,698 INFO - tensorflow - Signatures INCLUDED in export for Regress: None
2018-10-12 18:31:30,698 INFO - tensorflow - Signatures INCLUDED in export for Predict: ['serving_default']
2018-10-12 18:31:30.698635: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-10-12 18:31:30.698785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 324 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1e.0, compute capability: 7.0)
2018-10-12 18:31:30,712 INFO - tensorflow - Restoring parameters from /opt/ml/output/models/model.ckpt-2251
2018-10-12 18:31:30,724 INFO - tensorflow - Assets added to graph.
2018-10-12 18:31:30,725 INFO - tensorflow - No assets to write.
2018-10-12 18:31:30,766 INFO - tensorflow - SavedModel written to: /opt/ml/output/models/export/Servo/temp-1539369090/saved_model.pb
2018-10-12 18:31:30,861 ERROR - tf_container - Failed to download saved model. File does not exist in s3://ddc1-lexisai-users/sharmasx/tf/artifacts/shep/sagemaker-tensorflow-2018-10-12-18-27-41-782/checkpoints
2018-10-12 18:31:30,861 ERROR - container_support.training - uncaught exception during training: 'Contents'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 168, in train
    serve.export_saved_model(checkpoint_dir, env.model_dir)
  File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 54, in export_saved_model
    raise e
KeyError: 'Contents'
````
#### Code:
**tf_text_classify.py**
````

def keras_model_fn(hyperparameters):
    model = Sequential()
    model.add(InputLayer(input_shape=(maxlen,), name=PREDICT_INPUTS))

    model.add(Embedding(max_features,
                        embedding_dims,
                        input_length=maxlen))
    model.add(Dropout(0.2))

    # we add a Convolution1D, which will learn filters
    # word group filters of size filter_length:
    model.add(Conv1D(filters,
                     kernel_size,
                     padding='valid',
                     activation='relu',
                     strides=1))
    # we use max pooling:
    model.add(GlobalMaxPooling1D())

    # We add a vanilla hidden layer:
    model.add(Dense(hidden_dims))
    model.add(Dropout(0.2))
    model.add(Activation('relu'))

    # We project onto a single unit output layer, and squash it with a sigmoid:
    model.add(Dense(1))
    model.add(Activation('sigmoid'))

    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    return model
````
````
def estimator_fn(run_config, params):
    my_checkpointing_config = tf.estimator.RunConfig(
        save_checkpoints_secs=20 * 60,  # Save checkpoints every 20 minutes.
        keep_checkpoint_max=10,  # Retain the 10 most recent checkpoints.
        model_dir=model_dir
    )
    return tf.keras.estimator.model_to_estimator(keras_model=keras_model_fn(params), config=my_checkpointing_config)

def serving_input_fn(hyperparameters):
    feature_spec = {PREDICT_INPUTS: tf.FixedLenFeature(dtype=tf.float32, shape=[400])}
    return tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()

def train_input_fn(hyperparameters):
    return numpy_input_fn(x={PREDICT_INPUTS: x_train}, y=np.asarray(y_train).reshape((-1, 1)), shuffle=False)()

def eval_input_fn(hyperparameters):
    return numpy_input_fn(x={PREDICT_INPUTS: x_test}, y=np.array(y_test).reshape((-1, 1)), shuffle=False)()

````

### Invoking code ###
```
   session = boto3.Session(profile_name='appropriate profile')
    s3 = session.resource('s3')
    sagemaker_session = sagemaker.Session(boto_session=session)
    role = 'appropriate role'

    estimator = TensorFlow(entry_point='tf_text_classify.py',
                           # input_mode='Pipe',
                           role=role,
                           sagemaker_session=sagemaker_session,
                           output_path=model_artifacts_location,
                           code_location=custom_code_upload_location,
                           hyperparameters={'throttle_secs': 120000},
                           training_steps=620000,
                           evaluation_steps=30000,
                           train_instance_count=1,
                           train_instance_type="ml.p3.2xlarge", 
                           )

    training_dir = 's3://../data'

    estimator.fit(training_dir)

```

**Comment by icywang86rui** [comment]
It seems like training job failed here - https://github.com/aws/sagemaker-tensorflow-container/blob/master/src/tf_container/serve.py#L46

What's the output_path you are using? Does the bucket and prefix exist? What's the output of 

```
import boto3
s3 = boto3.client('s3')
s3.list_objects_v2(Bucket='Bucket', Prefix='Prefix')
```

**Comment by icywang86rui** [comment]
What role were you using? Does it have permission to the bucket 'corpusers'? Are there any checkpoint files saved in that bucket from that failed training job?

> Looking at the code (you pointed to) indicates that it is getting checkpoint directory rather than output_path.
Model artifacts including the saved models and checkpoints are saved under output_path.

Also from the logs it seems like your output path is:
```
s3://ddc1-lexisai-users/sharmasx/tf/artifacts/shep/sagemaker-tensorflow-2018-10-12-18-27-41-782/checkpoints
```
not "s3://corpusers/user1/tf/artifacts/proj". Is that the correct bucket you intended to use?

**Comment by sharmasx** [comment]
The `s3://corpusers/user1/tf/artifacts/proj `was to illustrate the pattern. The path in logs is correct and the role does have S3 permission. There are no checkpoint files in S3 bucket but I can see checkpoints stored in tmp dir. I see entries like `Saving checkpoints for 1338 into /tmp/tmpBpO4lj/model.ckpt `in the logs

**Comment by sharmasx** [comment]
Ok, figured out the reason for the problem though not sure why it causes error.
```
def estimator_fn(run_config, params):
    my_checkpointing_config = tf.estimator.RunConfig(
        save_checkpoints_secs=20 * 60,  # Save checkpoints every 20 minutes.
        keep_checkpoint_max=10,  # Retain the 10 most recent checkpoints.
        log_step_count_steps=20
        # model_dir=model_dir
    )
    return tf.keras.estimator.model_to_estimator(keras_model=keras_model_fn(params), config=run_config) # config=my_checkpointing_config)
```
Above using custom config `config=my_checkpointing_config` is causing the issue. Using default config, seems to resolve the issue. Not sure why custom config is causing that issue though. Is there some mandatory value that need to be set in the config object.

**Comment by icywang86rui** [comment]
I am glad that you are unblocked. I think the problem might be the model_dir is not set in your custom config. Also we if you are providing keras_model_fn in your script it's not necessary to provide estimator_fn anymore. The container takes care of the model to estimator conversion. Please let us know if you any further questions.
