### ISSUE TITLE
Bug with schema version when installing sagemaker

### ISSUE THREAD

**Issue by ltoniazzi** [aws/sagemaker-python-sdk#4539]
**Describe the bug**

I get an error importing sagemaker after installation. The error complains about a version of `schema`:

The import works if I upgrade `schema` to `0.7.5`

**To reproduce**

```
virtualenv --python=python3.9 .test_venv
source .test_venv/bin/activate
pip install sagemaker
python
>>> import sagemaker
```

To fix 
```
pip install schema==0.7.5
```

**Expected behavior**

Error trace:
```
import sagemaker
sagemaker.config INFO - Not applying SDK defaults from location: /Library/Application Support/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /Users/lorenzo/Library/Application Support/sagemaker/config.yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/Workspace/.test_venv/lib/python3.9/site-packages/sagemaker/__init__.py", line 18, in <module>
    from sagemaker import estimator, parameter, tuner  # noqa: F401
  File "/usr/Workspace/.test_venv/lib/python3.9/site-packages/sagemaker/estimator.py", line 79, in <module>
    from sagemaker.model import (
  File "/usr/Workspace/.test_venv/lib/python3.9/site-packages/sagemaker/model.py", line 54, in <module>
    from sagemaker.predictor import PredictorBase
  File "/usrWorkspace/.test_venv/lib/python3.9/site-packages/sagemaker/predictor.py", line 20, in <module>
    from sagemaker.jumpstart.factory.model import get_default_predictor
  File "/usr/Workspace/.test_venv/lib/python3.9/site-packages/sagemaker/jumpstart/factory/model.py", line 53, in <module>
    from sagemaker.model_monitor.data_capture_config import DataCaptureConfig
  File "/usr/Workspace/.test_venv/lib/python3.9/site-packages/sagemaker/model_monitor/__init__.py", line 30, in <module>
    from sagemaker.model_monitor.clarify_model_monitoring import BiasAnalysisConfig  # noqa: F401
  File "/usr/Workspace/.test_venv/lib/python3.9/site-packages/sagemaker/model_monitor/clarify_model_monitoring.py", line 29, in <module>
    from sagemaker.clarify import SageMakerClarifyProcessor, ModelPredictedLabelConfig
  File "/usr/Workspace/project-x/.test_venv/lib/python3.9/site-packages/sagemaker/clarify.py", line 30, in <module>
    from schema import Schema, And, Use, Or, Optional as SchemaOptional, Regex
ModuleNotFoundError: No module named 'schema'
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.214.0
- **Python version**: 3.9.18
- **pip version**: pip: 24.0
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Comment by ltoniazzi** [comment]
Closed as this issue has been opened already here https://github.com/aws/sagemaker-python-sdk/issues/4538
