### ISSUE TITLE
[ERROR] NameError: Field name "json" shadows a BaseModel attribute; use a different field name with "alias='json'"

### ISSUE THREAD

**Issue by sravanthijoshi** [aws/sagemaker-python-sdk#4944]
**Describe the bug**

[ERROR] NameError: Field name "json" shadows a BaseModel attribute; use a different field name with "alias='json'".
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/test_lambda_docker_container_image/hrfin_mec_provision_llm.py", line 5, in <module>
    from sagemaker.jumpstart.model import JumpStartModel

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
The provided code need to be **complete** and **runnable**, if additional data is needed, please include them in the issue.

We are trying to create a sagemaker jumpstart llm model endpoint from the AWS lambda using docker

This code was running very well for last one year  , but it is failing from 12/01 with below error . I have tried to pip install --upgrade sagemaker as well to upgrade the sagemaker packages in docker container. 

Code :

import json
import time
from boto3 import client as boto3_client
from aws_lambda_powertools import Logger
from sagemaker.jumpstart.model import JumpStartModel

logger = Logger(service="test_lambda_docker_container_image")

def lambda_handler(event, context):

    # Retrieve the model_id and model_version parameters from the json
    # payload. Defaults to llama 7b optimized for text generation. Other
    # parameters can be added to the lambda in this way.
    model_id = event.get('model_id', 'meta-textgeneration-llama-2-7b-f')
    model_version = event.get('model_version', '2.*')

    # Deploy the model to a predictor object. Set the wait parameter to False
    # to allow the lambda to terminate before the resource is provisioned.
    # This allows asynchronous communication between lambda controls and
    # provisioned predictor resources.
    model = JumpStartModel(model_id=model_id, model_version=model_version, instance_type='ml.g5.4xlarge')
    predictor = model.deploy(accept_eula=True, wait=False)

    # We want to return a reference to the endpoint so that other programs can
    # communicate with it once it has become available. To do this, we extract
    # the endpoint_name attribute from the Predictor object `predictor`
    endpoint_name = predictor.endpoint_name

    payload = {'endpoint_name': endpoint_name}

    print(payload)

    time.sleep(600)

**Expected behavior**

above code should execute well and create a meta llm model

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.235.2 --- I have tried pip install ---upgrade sagemaker in the code package  to fetch latest version and this bug exists
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:  3.9
- **CPU or GPU**:
- **Custom Docker image (Y/N)**: Y

**Additional context**

**Comment by sravanthijoshi** [comment]
we were able to execute above code with sagemaker 2.227.0 version but not with latest version 2.235.2

**Comment by sravanthijoshi** [comment]
Team , any udate on this bug?

**Comment by ZMarouani** [comment]
I started having this Bug automatically within an old working code .. is this fixed yet ?

**Comment by faithfulalabi** [comment]
Hey, team friendly bump on this issue.

**Comment by neal-harrington** [comment]
Bump, we see this simply doing an import of Predictor, it it does appear that it is due to a dependency of this import on jumpstart 


```
Python 3.10.16 (main, Dec 18 2024, 11:29:39) [Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sagemaker import Predictor

NameError: Field name "json" shadows a BaseModel attribute; use a different field name with "alias='json'".
```


```
>>> from sagemaker.jumpstart.types import JumpStartLaunchedRegionInfo

...sagemaker_core/main/shapes.py:2509 in <module>                                                                    │
│                                                                                                  │
│    2506 │   """                                                                                  │
│    2507                                                                                          │
│    2508                                                                                          │
│ ❱  2509 class MonitoringDatasetFormat(Base):                                                     │
│    2510 │   """                                                                                  │
│    2511 │   MonitoringDatasetFormat                                                              │
│    2512 │     Represents the dataset format used when running a monitoring job.                  │
│                                                                                                  │
│ in pydantic.main.ModelMetaclass.__new__:186                                                      │
│                                                                                                  │
│ in pydantic.utils.validate_field_name:168                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: Field name "json" shadows a BaseModel attribute; use a different field name with "alias='json'".
>>> from sagemaker.jumpstart.types import JumpStartLaunchedRegionInfo
```

**Comment by suleimandeni** [comment]
Still an error today

**Comment by mohamedzeidan2021** [comment]
This is a pydantic v1 issue — the `Field name "json" shadows a BaseModel attribute` error is raised by pydantic v1 (see the `pydantic.utils.validate_field_name` / `ModelMetaclass` frames), which rejects a model field named `json` because it collides with the v1 `BaseModel.json()` method. The `MonitoringDatasetFormat` shape has a `json` field, so class definition failed under pydantic v1.

The current SDK requires pydantic v2 (`pydantic>=2.0.0,<3.0.0`), under which a `json` field is permitted and the shape loads without error — verified by importing and instantiating `MonitoringDatasetFormat` on pydantic 2.13.x with no error or warning. Upgrading to a current SDK release (with pydantic 2) resolves this. Closing as resolved — please reopen if you still hit it on a pydantic-2 environment.
