### ISSUE TITLE
py3.6 support for SageMaker SDK -> CoreML conversion issue

### ISSUE THREAD

**Issue by niakki** [aws/sagemaker-python-sdk#555]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Sci-kit Learn / Logistic Regression
- **Framework Version**: 0.20
- **Python Version**: 3.5
- **CPU or GPU**: CPU
- **Python SDK Version**: SageMaker SDK on py3.5 
- **Are you using a custom image**: No

### Describe the problem
Created a training job using SageMaker SDK's SKlearn model wrapper, extra hook added for converting *.joblib (pickled) sklearn files to Apple's CoreML (*.mlmodel) format in train.py. However, running the code on SageMaker training job instance gives an error.

### Minimal repro / logs
[13/Dec/2018 07:49:49] INFO - Converting SKLearn model to CoreML
07:49:49
[ERROR] Currently "One Vs Rest" is the only supported multiclass option.
07:49:49
Traceback (most recent call last): File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main "__main__", mod_spec) File "/usr/lib/python3.5/runpy.py", line 85, in _run_code exec(code, run_globals) File "/opt/ml/code/train.py", line 68, in <module> model_uri_http = coreml_converter(model, bucketName) File "/opt/ml/code/util.py", line 34, in coreml_converter mlmode
07:49:49
TypeError: Expected model to be a .mlmodel file or a Model_pb2 object

this issue is with Python3.5, I have checked it on my local (Py3.6 works just fine)

**Comment by ChoiByungWook** [comment]
Hello @niakki,

Thank you for bringing this to our attention.

If I am understanding you correctly, it seems that when running a training job using our SKLearnEstimator, you run into the following exception:

> TypeError: Expected model to be a .mlmodel file or a Model_pb2 object

This problem seems to be solved on Python 3.6, however fails on Python 3.5, which seems to be the Python version that our [SKLearn container](https://github.com/aws/sagemaker-scikit-learn-container/blob/master/docker/0.20.0/base/Dockerfile.cpu#L15) supports as the base image is [16.04 for Ubuntu](https://packages.ubuntu.com/xenial/python3-dev).

I apologize for the experience. Our SKLearn container is open source and  we are always open to suggestions and appreciate contributions!
- https://github.com/aws/sagemaker-scikit-learn-container

As a quick work around if needed, you can build your own container with Python 3.6 for SKLearn through these instructions: https://github.com/aws/sagemaker-scikit-learn-container#building-your-image

Please let me know if there is anything I can clarify.

Thanks!
