### ISSUE TITLE
Script mode not uploading model to S3 in Sagemaker jupyter lab

### ISSUE THREAD

**Issue by JingJZ160** [aws/sagemaker-python-sdk#578]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow
- **Framework Version**: 1.11.0
- **Python Version**: py3
- **CPU or GPU**: CPU
- **Python SDK Version**: Not sure how to check...The one that is used by the jupyter lab in the AWS console.
- **Are you using a custom image**: No

### Describe the problem
I'm running the jupyter lab `tensorflow_abalone_age_predictor_using_layers.ipynb` in the AWS console using the kernel `conda_tensorflow_p36`. When running in the default mode (not script mode), the train job finished successfully and uploaded the model to the S3 location at `s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-2018-12-21-15-14-36-526/output/model.tar.gz`.

However, when I switched to script mode by adding the py_version parameter, the generated model was not found even though the training job finished successfully. At first I thought it was because of some permission issue with the host accessing S3, but then I found a source file tar.gz at `s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/source/sourcedir.tar.gz` uploaded by the training job. However, the model directory `s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/model` was missing. 

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
INFO:sagemaker:Created S3 bucket: sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER
INFO:sagemaker:Creating training-job with name: sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723
2018-12-21 15:24:20 Starting - Starting the training job...
2018-12-21 15:24:23 Starting - Launching requested ML instances......
2018-12-21 15:25:29 Starting - Preparing the instances for training......
2018-12-21 15:26:46 Downloading - Downloading input data
2018-12-21 15:26:46 Training - Training image download completed. Training in progress.
2018-12-21 15:26:46 Uploading - Uploading generated training model.
2018-12-21 15:26:43,617 sagemaker-containers INFO     Imported framework sagemaker_tensorflow_container.training
2018-12-21 15:26:43,623 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2018-12-21 15:26:44,045 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2018-12-21 15:26:44,056 sagemaker-containers INFO     Invoking user script

Training Env:

{
    "additional_framework_parameters": {},
    "channel_input_dirs": {
        "training": "/opt/ml/input/data/training"
    },
    "current_host": "algo-1",
    "framework_module": "sagemaker_tensorflow_container.training:main",
    "hosts": [
        "algo-1"
    ],
    "hyperparameters": {
        "model_dir": "s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/model",
        "learning_rate": 0.001
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "training": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "job_name": "sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723",
    "log_level": 20,
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/source/sourcedir.tar.gz",
    "module_name": "abalone",
    "network_interface_name": "ethwe",
    "num_cpus": 4,
    "num_gpus": 0,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "hosts": [
            "algo-1"
        ],
        "network_interface_name": "ethwe"
    },
    "user_entry_point": "abalone.py"
}

Environment variables:

SM_HOSTS=["algo-1"]
SM_NETWORK_INTERFACE_NAME=ethwe
SM_HPS={"learning_rate":0.001,"model_dir":"s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/model"}
SM_USER_ENTRY_POINT=abalone.py
SM_FRAMEWORK_PARAMS={}
SM_RESOURCE_CONFIG={"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"ethwe"}
SM_INPUT_DATA_CONFIG={"training":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["training"]
SM_CURRENT_HOST=algo-1
SM_MODULE_NAME=abalone
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_tensorflow_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=4
SM_NUM_GPUS=0
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{"training":"/opt/ml/input/data/training"},"current_host":"algo-1","framework_module":"sagemaker_tensorflow_container.training:main","hosts":["algo-1"],"hyperparameters":{"learning_rate":0.001,"model_dir":"s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/model"},"input_config_dir":"/opt/ml/input/config","input_data_config":{"training":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","job_name":"sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723","log_level":20,"model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/source/sourcedir.tar.gz","module_name":"abalone","network_interface_name":"ethwe","num_cpus":4,"num_gpus":0,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"ethwe"},"user_entry_point":"abalone.py"}
SM_USER_ARGS=["--learning_rate","0.001","--model_dir","s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/model"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TRAINING=/opt/ml/input/data/training
SM_HP_MODEL_DIR=s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/model
SM_HP_LEARNING_RATE=0.001
PYTHONPATH=/opt/ml/code:/usr/local/bin:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/dist-packages:/usr/lib/python3/dist-packages

Invoking script with the following command:

/usr/bin/python abalone.py --learning_rate 0.001 --model_dir s3://sagemaker-us-east-1-MY_AWS_ACCOUNT_NUMBER/sagemaker-tensorflow-scriptmode-2018-12-21-15-24-19-723/model


2018-12-21 15:26:45,250 sagemaker-containers INFO     Reporting training SUCCESS

2018-12-21 15:26:51 Completed - Training job completed
Billable seconds: 24
```

- **Exact command to reproduce**:
As mentioned above, using the provided lab notebook in a Sagemaker instance `tensorflow_abalone_age_predictor_using_layers.ipynb`, kernel version conda_tensorflow_p36. The only modified code is adding the py_version parameter.
```
from sagemaker.tensorflow import TensorFlow

abalone_estimator = TensorFlow(entry_point='abalone.py',
                               role=role,
                               framework_version='1.11.0',
                               hyperparameters={'learning_rate': 0.001},
                               train_instance_count=1,
                               train_instance_type='ml.c4.xlarge', py_version='py3')

abalone_estimator.fit(inputs)
```

**Comment by laurenyu** [comment]
hi @JingJZ160, thanks for using SageMaker!

Training scripts for legacy mode and script mode with TF are not interchangeable, and one difference which you've run into is that in script mode, the training script needs to explicitly save the model to the path defined by `os.environ['SM_MODEL_DIR']`. You can read more at https://github.com/aws/sagemaker-python-sdk/tree/master/src/sagemaker/tensorflow#adapting-your-local-tensorflow-script

**Comment by laurenyu** [comment]
That is correct - that script is not meant for script mode. You can tell that [the script](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_abalone_age_predictor_using_layers/abalone.py) is written for legacy mode because it contains no code that would execute if one were to run the script on its own with no knowledge of the functions defined within it.

There are a couple sample notebooks for TF script mode right now: [tensorflow_script_mode_quickstart.ipynb](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_script_mode_quickstart/tensorflow_script_mode_quickstart.ipynb) and [tensorflow_script_mode_using_shell_commands.ipynb](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_script_mode_using_shell_commands/tensorflow_script_mode_using_shell_commands.ipynb)

You can also find an example script on its own [here](https://github.com/aws/sagemaker-tensorflow-container/blob/script-mode/test/resources/mnist/distributed_mnist.py).

Your code outline looks right except that you don't need `estimator.fit({'train': args.train, 'eval': args.test})` at the end - that's needed only for the Jupyter cell.

**Comment by cfournies** [comment]
Hello, I have a very similar problem, I'm not sure what I'm doing wrong. I have follow the documentation and sagemaker is not uploading the output to S3. 

`test_estimator = TensorFlow(entry_point='DNN-test.py',
                            role=role,
                            py_version = "py3",
                            framework_version=1.11,
                            output_path = model_artifacts_location,
                            model_dir = 's3://sagemaker-ai-model-data/Output/Checkpoints',
                            train_instance_count=1,
                            train_instance_type='ml.c4.xlarge')`
As you can see I'm specifying the output_path and model_dir, that according to the documentation will be safe after the training is done to that path. That is what I understand from your documentation

> When the training job finishes, the container will be deleted including its file system expect for /opt/ml/model and /opt/ml/output. Use /opt/ml/model to save the model checkpoints. These checkpoints will be uploaded to the default S3 bucket. 

After running the model I see that the variable `SM_MODULE_DIR` is define as: 
`SM_MODULE_DIR=s3://sagemaker-us-east-1-ACCOUNT-NUMBER/sagemaker-tensorflow-scriptmode-2019-01-04-02-37-02-156/source/sourcedir.tar.gz`

But is not the url that I'm providing in the output_path which is:
`bucket = 'sagemaker-ai-model-data'
model_artifacts_location = 's3://{}/Output'.format(bucket)`

Not sure what I'm doing wrong, I have read every documentation (new to Sagemaker)

**Comment by nadiaya** [comment]
`output_path` is an s3 location were artifacts from `/opt/ml/output` and `/opt/ml/model` will be moved by sagemaker service at the end of training.

`model_dir` is an s3 location for checkpoints to be saved.

We do not save a model from the checkpoints or write anything by default into `/opt/ml/model` directory. This should be done explicitly in the user script.

**Comment by cfournies** [comment]
Thanks for the reply. I understand that is how it suppose to work, but on my end, the problem is that sagemaker it not moving the files to the `output_path`.  Therefore I can't deploy the model because I get `CreateModel operation: Could not find model data at s3://sagemaker-ai-model-data/Output`

**Comment by cfournies** [comment]
Not sure, I'm using similar code that the original post.  The only thing that is different is that I have a function call estimator_fn so I don't define the estimator again under `if __name__ =='__main__':`

In other words, I don't see where you explicitly save it in the example given above. if you can help me point that out I will really appreciate.

**Comment by AlexandreRozier** [comment]
Hi! Thanks for helping us keep up  with the latest releases of the Script Mode. I have the same problem as @cfournies, which is I need to export the model.tar.gz to SM_MODEL_DIR. I tried using in my user script the following snippet: 
`estimator.export_saved_model(
        os.environ.get('SM_MODEL_DIR'),
        serving_input_fn,
        assets_extra=None,
        as_text=False,
        checkpoint_path=None
    )` 
But this doesn't seem to write to /opt/ml/model. Any idea of how one could save a tf model to this location ? [tf version: 1.12]

**Comment by tbs17** [comment]
i have the same issue but in the sagemaker pytorch container. I used the below script to execute the estimator function for a BERT model:

```container_data_dir='/opt/ml/input/data/training'
container_model_dir='opt/ml/model'
output_prefix='BERT/pytorch-output'
output_path='s3://{}/{}'.format(bucket,output_prefix)

parameters={
    'model_type':'bert',
    'model_name_or_path':'bert-base-uncased',
    'task_name':task_name,
    'data_dir':container_data_dir,
    'output_dir': container_model_dir,
    'num_train_epochs':4,
    'per_gpu_train_batch_size':16,
    'per_gpu_eval_batch_size':16,
    'save_steps':150,
    'logging_steps':150,
    'do_train':True,
    'do_eval':True,
    'do_lower_case':True,
    'learning_rate':2e-5,
    'max_seq_length':128

}


train_instance_type='ml.p3.2xlarge'
output_prefix='BERT/pytorch-output'
output_path='s3://{}/{}'.format(bucket,output_prefix)
glue_estimator=PyTorch(entry_point='run_glue.py',
                       source_dir='./train_scripts/',
                       hyperparameters=parameters,
                       role=role,
                       framework_version='1.1.0',#original version was 1.1.0
                       train_instance_count=1,
                       train_instance_type=train_instance_type
                       ,output_path = output_path
                      )
```

If i don't sepcify an output_path, then the output will be saved under another bucket which sagemaker creates. If i specify an output path, then the output_path will save debug_output, the souce file which contains source.tar.gz will still go to the bucket that sagemaker creates by default. I have run the lstm model suggested from sagemaker pytorch container github page :[https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/pytorch_lstm_word_language_model/pytorch_rnn.ipynb](url), it can upload model.tar.gz to the s3 even if i don't specify any output directory. The only thing i noticed differently is that it uses a train.py and generate.py to spearately do training and inference. The entry point script i used has triaining and evaluation code as well. but it doesn't have prediction code. In other words, i don't necessary have model_fn, input_fn, output_fn(), etc. I wonder if that's the reason?

I also attach here my training script 'run_glue.py'
[run_glue_txt.txt](https://github.com/aws/sagemaker-python-sdk/files/4484762/run_glue_txt.txt)

**Comment by swraza** [comment]
Hello @laurenyu,
                         I need your help in solving my issue with script mode AWS image classification.
this is my entry_point.

import tensorflow as tf
from tensorflow.python.keras import Sequential
from tensorflow.python.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
from tensorflow.python.training.rmsprop import RMSPropOptimizer
import argparse
import os

HEIGHT = 128
WIDTH = 128
DEPTH = 3
NUM_CLASSES = 2
BATCH_SIZE = 64
INPUT_TENSOR_NAME = "inputs_input" # According to Amazon, needs to match the name of the first layer + "_input"
                              # Workaround for actual known bugs
 
    
def keras_model_fn(hyperparameters):
    base_model_VGG16 = applications.VGG16(weights="imagenet", input_shape=(256,256,3), include_top=False)
    model_VGG16 = Sequential()
    model_VGG16.add(base_model_VGG16) ## here we add VGG as base_model and our classifier as top_model
    model_VGG16.add(Flatten())
    model_VGG16.add(Dense(1, activation='sigmoid'))
    for layer in model_VGG16.layers[:-2]:
        layer.trainable = False
    model_VGG16.compile(loss='binary_crossentropy',optimizer=optimizers.Adam(lr=1e-4),metrics=['accuracy'])
    return model_VGG16

def serving_input_fn(hyperparameters):
    tensor = tf.placeholder(tf.float32, shape=[None, HEIGHT, WIDTH, DEPTH])
    inputs = {INPUT_TENSOR_NAME: tensor}
    return tf.estimator.export.ServingInputReceiver(inputs, inputs)

def train_input_fn(training_dir, hyperparameters):
    return _input(tf.estimator.ModeKeys.TRAIN, batch_size=BATCH_SIZE, data_dir=training_dir)


def eval_input_fn(training_dir, hyperparameters):
    return _input(tf.estimator.ModeKeys.EVAL, batch_size=BATCH_SIZE, data_dir=training_dir)


def _input(mode, batch_size, data_dir):
    assert os.path.exists(data_dir), ("Unable to find images resources for input, are you sure you downloaded them ?")

    if mode == tf.estimator.ModeKeys.TRAIN:
        datagen = ImageDataGenerator(
            rescale=1. / 255,
            shear_range=0.2,
            zoom_range=0.2,
            horizontal_flip=True
        )
    else:
        datagen = ImageDataGenerator(rescale=1. / 255)

    generator = datagen.flow_from_directory(data_dir, target_size=(HEIGHT, WIDTH), batch_size=batch_size)
    images, labels = generator.next()

    return {INPUT_TENSOR_NAME: images}, labels


if __name__ =='__main__':

    parser = argparse.ArgumentParser()

    # hyperparameters sent by the client are passed as command-line arguments to the script.
    parser.add_argument('--epochs', type=int, default=10)
    parser.add_argument('--batch_size', type=int, default=100)
    parser.add_argument('--learning_rate', type=float, default=0.1)

    # input data and model directories
    parser.add_argument('--model_dir', type=str, default=os.environ.get('SM_MODEL_DIR'))
    parser.add_argument('--train', type=str, default=os.environ.get('SM_CHANNEL_TRAIN'))
    parser.add_argument('--eval', type=str, default=os.environ.get('SM_CHANNEL_TEST'))

    args, _ = parser.parse_known_args()

    # create my own custom estimator, by defining 
    my_classifier = tf.estimator.Estimator(model_fn=keras_model_fn, model_dir=args.model_dir)
    train_spec = tf.estimator.TrainSpec(train_input_fn, max_steps=1000)
    eval_spec = tf.estimator.EvalSpec(eval_input_fn)
    tf.estimator.train_and_evaluate(my_classifier, train_spec, eval_spec)

And this is my estimator in Jupyter notebook
estimator = TensorFlow(
  entry_point="BrainImageClassification.py",             # Your entry script
  role=sagemaker.get_execution_role(),
  framework_version="1.12.0",               # TensorFlow's version
  hyperparameters=hyperparameters,
  training_steps=1000,
  evaluation_steps=100,
  train_instance_count=1,                   # "The number of GPUs instances to use"
  train_instance_type=train_instance_type,
  py_version="py3", # https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html
  #script_mode=True
)

But this is what I am facing.
Traceback (most recent call last):
  File "BrainImageClassification.py", line 104, in <module>
    my_classifier = tf.estimator.Estimator(model_fn=keras_model_fn, model_dir=args.model_dir)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 204, in __init__
    _verify_model_fn_args(model_fn, params)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 1827, in _verify_model_fn_args
    raise ValueError('model_fn (%s) must include features argument.' % model_fn)
ValueError: model_fn (<function keras_model_fn at 0x7f83c7cc1ea0>) must include features argument.
2021-02-10 16:08:48,967 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/usr/bin/python BrainImageClassification.py --decay 1e-06 --learning_rate 0.0001 --model_dir s3://sagemaker-us-east-2-458149152225/sagemaker-tensorflow-scriptmode-2021-02-10-15-55-39-799/model"

**Comment by laurenyu** [comment]
hi @swraza, you're commenting on an issue that's both old and closed - you'll be better off if you open a new issue next time (and it'll be easier to follow for others who may come across the issue later).

Aside from that, it looks like your issue is with your TensorFlow script:

```
File "BrainImageClassification.py", line 104, in
    my_classifier = tf.estimator.Estimator(model_fn=keras_model_fn, model_dir=args.model_dir)
[...]
ValueError: model_fn (<function keras_model_fn at 0x7f83c7cc1ea0>) must include features argument.
```

Make sure your `model_fn` follows the requirements outlined in the TF documentation: https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#args

If you need help writing a TF script, try StackOverflow - that seems to be where the TF maintainers send people when issues are opened in their repo.

**Comment by swraza** [comment]
ok thank you let me try my luck there
