### ISSUE TITLE
Issues with code in source_dir

### ISSUE THREAD

**Issue by soufianekhoudmi** [aws/sagemaker-python-sdk#648]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: SKLearn / Custom
- **Framework Version**: 0.20.0
- **Python Version**: 3.5
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.18.2
- **Are you using a custom image**: No

### Describe the problem
Describe the problem or feature request clearly here.

While my source_dir code is successfully processed when I fit my model, I am unable to call my source_dir code when deploying.

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The interesting part of my source_dir is :

```
__init.py
data
lib
    __init__.py
    transformers --> define my intermediate computations
        __init__.py
        some_transformers.py
    training.py  --> train models, in a dict, to be pickled using transformers and a gridsearchCV. 
    prediction.py --> use pickled models to select the most appropriate one, to predict values and confidence interval.
    my_sagemaker_script.py
    my_sagemaker_runner.ipynb
```

My my_sagemaker_script.py is :

```
import argparse
import os
import sys
from sklearn.externals import joblib
from lib import training, prediction
training_data_path = 'data/extract.csv'
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-data-dir", type=str, default=os.environ["SM_OUTPUT_DATA_DIR"])
    parser.add_argument("--model-dir", type=str, default=os.environ["SM_MODEL_DIR"])
   args = parser.parse_args()
    grid_models_dict =\
        training.generate_trained_models(raw_training_data=training_data_path)
    joblib.dump(grid_models_dict, os.path.join(args.model_dir, "model"))
def model_fn(model_dir):
    grid_models_dict = joblib.load(os.path.join(model_dir, "model"))
    return grid_models_dict
def predict_fn(input_data, model):
    predicted = prediction.predict(input_data, model))
    return predicted
def predict_fn(input_data, model):
    predicted = prediction.predict(input_data, model))
    return predicted
```

I instantiate my SKLearn :
```
script_path = 'my_sagemaker_script.py'
sklearn = SKLearn(
    entry_point=script_path,
    train_instance_type="ml.c4.xlarge",
    source_dir = './',
    role=role,
    sagemaker_session=sagemaker_session)
```
I fit it,  successfully
```
sklearn.fit()
```
Output : Reporting training SUCCESS

However, when I deploy :
```
predictor = sklearn.deploy(initial_instance_count=1, instance_type="ml.m4.xlarge")
```
my code is not processed (ImportError). In CloudWatch : 

[2019-02-18 17:40:09 +0000] [31] [ERROR] Error handling request /ping
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_modules.py", line 248, in import_module
module = importlib.import_module(name)
File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 986, in _gcd_import
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 665, in exec_module
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "/usr/local/lib/python3.5/dist-packages/dili_sagemaker_script.py", line 28, in <module>
from lib import training, prediction
ImportError: cannot import name 'training'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
addr)
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_sklearn_container/serving.py", line 99, in main
user_module = modules.import_module(serving_env.module_dir, serving_env.module_name)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_modules.py", line 253, in import_module
six.reraise(_errors.ImportModuleError, _errors.ImportModuleError(e), sys.exc_info()[2])
File "/usr/local/lib/python3.5/dist-packages/six.py", line 692, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_modules.py", line 248, in import_module
module = importlib.import_module(name)
File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 986, in _gcd_import
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 665, in exec_module
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "/usr/local/lib/python3.5/dist-packages/dili_sagemaker_script.py", line 28, in <module>
from lib import training, prediction
sagemaker_containers._errors.ImportModuleError: cannot import name 'training'

Any solution or workaround ?  Thank you in advance.

**Comment by soufianekhoudmi** [comment]
The deployment seems to work with 
```
module_path = os.path.abspath('/opt/ml/code')
if module_path not in sys.path:
    sys.path.append(module_path)
from lib import training, prediction
```

**Comment by laurenyu** [comment]
thanks for your patience! we've reached out to the team that is responsible for our Scikit-learn support to see if they have any insight.

**Comment by suchak-dwivedi** [comment]
I face same situation with deploying Sklearn model. It throws error while deploying but doesn't while training. Do you have an ETA for fix?

**Comment by soufianekhoudmi** [comment]
It seems that the paths in training and in deploy are not similar. This workaround did the job for me : add your code in sys.path before importing your code. Put this in the beginning of your script.

'''
import os
module_path = os.path.abspath('/opt/ml/code')
if module_path not in sys.path:
    sys.path.append(module_path)
'''

Hope this help.

Complete example code with the fix.
'''
import argparse
import os
module_path = os.path.abspath('/opt/ml/code')
if module_path not in sys.path:
    sys.path.append(module_path)

import sys
from sklearn.externals import joblib
from lib import training, prediction
training_data_path = 'data/transactions/tests/extract_samples.csv'
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-data-dir", type=str, default=os.environ["SM_OUTPUT_DATA_DIR"])
    parser.add_argument("--model-dir", type=str, default=os.environ["SM_MODEL_DIR"])
   args = parser.parse_args()
    grid_models_dict =\
        training.generate_trained_models(raw_training_data=training_data_path)
    joblib.dump(grid_models_dict, os.path.join(args.model_dir, "model"))
def model_fn(model_dir):
    grid_models_dict = joblib.load(os.path.join(model_dir, "model"))
    return grid_models_dict
'''

**Comment by suchak-dwivedi** [comment]
Thanks, it does work with your workaround. It would be better if this is
fixed in more elegant way.

**Comment by mvsusp** [comment]
Hi @soufianekhoudmi ,

The original files are stored under the /opt/ml/code directory. I'm adding a feature request in the roadmap to add /opt/ml/code to PYTHONPATH as well.

In the meanwhile, I believe you already found a solution for that issue.

Thanks for using SageMaker.
