### ISSUE TITLE
Unable to install sagemaker using pip3 and python3 (3.5.2) on ubuntu 16.04

### ISSUE THREAD

**Issue by karanrn** [aws/sagemaker-python-sdk#7]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/sagemaker/__init__.py", line 15, in <module>
    from sagemaker import estimator
  File "/usr/local/lib/python3.5/dist-packages/sagemaker/estimator.py", line 24, in <module>
    from sagemaker.model import Model
  File "/usr/local/lib/python3.5/dist-packages/sagemaker/model.py", line 18, in <module>
    from sagemaker.session import Session
  File "/usr/local/lib/python3.5/dist-packages/sagemaker/session.py", line 32, in <module>
    SDK_VERSION = pkg_resources.require('sagemaker')[0].version
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.7.48 (/home/karan/.local/lib/python3.5/site-packages), Requirement.parse('botocore<1.9.0,>=1.8.0'), {'boto3'})

**Comment by lukmis** [comment]
Hi,

Seems like you might have previous version of botocore installed on your system. Could you try to upgrade the botocore with:

pip3 install -U botocore

After you upgrade this error should go away.

**Comment by karanrn** [comment]
I had to uninstall and install botocore again.
