### ISSUE TITLE
CloudWatch reports "no SavedModel bundles found" with apparently conforming serving model

### ISSUE THREAD

**Issue by tigerhawkvok** [aws/sagemaker-python-sdk#828]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow
- **Framework Version**: 1.12.0
- **Python Version**: 3
- **CPU or GPU**: GPU

### Describe the problem

With a `*.pb` saved model, I can't package it into a `*.tar.gz` and send it to a Tensorflow Serving instance

### Minimal repro / logs

Please let me know if the targz file should be provided, and I can give a Drive or Dropbox link to the file.

- **Exact command to reproduce**:

the flag `isArtifactMode` is false, since I'm supplying a raw `*.pb` and `*.txt` file here.

We're working in a folder `CONTAINER_DIR`, and will label our model version with `VERSION_INT`, both supplied by the user at the top of the notebook. Variable types have been checked and directories created.

```python
import datetime as dt
if not isArtifactMode:
    # Create a versioned path for the models to live in
    # See https://stackoverflow.com/a/54014480/1877527
    modelVersionPath = os.path.join(CONTAINER_DIR, VERSION_INT)
    if not os.path.exists(modelVersionPath):
        os.mkdir(modelVersionPath)
    # Create a source and destination for the model and its label file
    modelPath = os.path.join(CONTAINER_DIR, VERSION_INT, baseModelPath)
    s3ModelPath = os.path.join(bucketPath, baseModelPath)              
    modelLabel = os.path.join(CONTAINER_DIR, VERSION_INT, baseModelLabel) 
    s3ModelLabel = os.path.join(bucketPath, baseModelLabel)              
    # Copy the files from S3 to our local instance
    !aws s3 cp {s3ModelPath} {modelPath}
    !aws s3 cp {s3ModelLabel} {modelLabel}
    # Make sure they worked
    if not os.path.exists(modelPath) or not os.path.exists(modelLabel):
        raise ValueError("Couldn't create models locally!")
    # Prep for serving
    modelName = f"livemodel_{dt.datetime.now().timestamp()}.tar.gz"
    # Copy the version directory temporarily here to package
    while os.path.exists(VERSION_INT):
        # Wait for another notebook to clean up...
        import time
        time.sleep(1)
    !cp -R {modelVersionPath} ./
    # gziptar it
    !tar -czvf {modelName} {VERSION_INT}
    # Shove it back to S3 for serving
    !aws s3 cp {modelName} {bucketPath}
    shutil.rmtree(VERSION_INT) # Cleanup
    # create predictor
    from sagemaker.tensorflow.serving import Model
    model = Model(model_data= os.path.join(bucketPath, modelName), role= role)
    predictor = model.deploy(initial_instance_count=1, instance_type= COMPUTE_INSTANCE_TYPE)
    print("Created predictor from local artifact")
```

This results in

```
download: s3://sagemaker-pkahn-uswest2-uc/smtest.pb to pkahn_uc_predictpool/1/smtest.pb
download: s3://sagemaker-pkahn-uswest2-uc/smtest.txt to pkahn_uc_predictpool/1/smtest.txt
1/
1/smtest.pb
1/smtest.txt
upload: ./livemodel_1559671583.380835.tar.gz to s3://sagemaker-pkahn-uswest2-uc/livemodel_1559671583.380835.tar.gz
----------------------------------------------------------------------------------------------------------------------------------------------------------------*
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-be711eb43207> in <module>()
     23     from sagemaker.tensorflow.serving import Model
     24     model = Model(model_data= os.path.join(bucketPath, modelName), role= role)
---> 25     predictor = model.deploy(initial_instance_count=1, instance_type= COMPUTE_INSTANCE_TYPE)
     26     print("Created predictor from local artifact")

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/sagemaker/model.py in deploy(self, initial_instance_count, instance_type, accelerator_type, endpoint_name, update_endpoint, tags, kms_key)
    278         else:
    279             self.sagemaker_session.endpoint_from_production_variants(self.endpoint_name, [production_variant],
--> 280                                                                      tags, kms_key)
    281 
    282         if self.predictor_cls:

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in endpoint_from_production_variants(self, name, production_variants, tags, kms_key, wait)
   1066 
   1067             self.sagemaker_client.create_endpoint_config(**config_options)
-> 1068         return self.create_endpoint(endpoint_name=name, config_name=name, tags=tags, wait=wait)
   1069 
   1070     def expand_role(self, role):

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in create_endpoint(self, endpoint_name, config_name, tags, wait)
    776         self.sagemaker_client.create_endpoint(EndpointName=endpoint_name, EndpointConfigName=config_name, Tags=tags)
    777         if wait:
--> 778             self.wait_for_endpoint(endpoint_name)
    779         return endpoint_name
    780 

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in wait_for_endpoint(self, endpoint, poll)
    932         if status != 'InService':
    933             reason = desc.get('FailureReason', None)
--> 934             raise ValueError('Error hosting endpoint {}: {} Reason: {}'.format(endpoint, status, reason))
    935         return desc
    936 

ValueError: Error hosting endpoint sagemaker-tensorflow-serving-2019-06-04-18-06-30-251: Failed Reason:  The primary container for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint.
```

The gztar looks fine

![image](https://user-images.githubusercontent.com/165937/58907277-a9ad6000-86c2-11e9-8741-d8e90652e6a7.png)

The CloudWatch logs say

```

18:19:57
INFO:__main__:starting services

18:19:57
Traceback (most recent call last): File "/sagemaker/serve.py", line 327, in <module> ServiceManager().start() File "/sagemaker/serve.py", line 287, in start self._create_tfs_config() File "/sagemaker/serve.py", line 76, in _create_tfs_config raise ValueError('no SavedModel bundles found!')

18:19:57
ValueError: no SavedModel bundles found!
```

See also #603 , #599 which are slightly different but probably related

**Comment by tigerhawkvok** [comment]
In a bit of a meta-comment, @jesterhazy was the source of the StackOverflow answer I used as a base, and his comments on PR #607 seemed to indicate that those set of instructions were incorrect.

**Comment by ChoiByungWook** [comment]
The stacktrace is caused here: https://github.com/aws/sagemaker-tensorflow-serving-container/blob/master/container/sagemaker/serve.py#L76

Which was caused due to this code condition not being met: https://github.com/aws/sagemaker-tensorflow-serving-container/blob/master/container/sagemaker/serve.py#L152

What are your pb files named as? I believe the container is expecting: https://github.com/aws/sagemaker-tensorflow-serving-container/blob/master/container/sagemaker/serve.py#L168

For quicker iterations, I recommend using local mode, which will run a docker container on your local host in a SageMaker emulated environment. This can be enabled by using 'local' for the instance_type in the deploy call. This does require docker-compose.

Example: https://github.com/aws/sagemaker-python-sdk/blob/master/tests/integ/test_local_mode.py#L107

**Comment by tigerhawkvok** [comment]
Thanks @ChoiByungWook 

The local mode tends to blow up the instance with docker container spam. I still haven't found a way to clean up aborted training instances, so our group has been shutting down and resizing the volume then restarting instances when running in 'local'. (The docs could definitely use an update there).

You definitely answered my question, though apparently I need to do some manipulation since the `SERVING` tag wasn't on my model

```
2019-06-04 22:33:52.615633: E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: model version: 1} failed: Not found: Could not find meta graph def matching supplied tags: { serve }. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
```

For context, I'm trying to use one or more already-retrained Inception models that were saved with
```python
def save_graph_to_file(sess, graph, graph_file_name):
    """Saves an graph to file, creating a valid quantized one if necessary."""
    output_graph_def = graph_util.convert_variables_to_constants(sess, graph.as_graph_def(), [FLAGS.final_tensor_name])
    with gfile.FastGFile(graph_file_name, 'wb') as f:
        f.write(output_graph_def.SerializeToString())
```

Apparently I need to get a serving tag somewhere in there... I'll update and close this issue when I figure that out, probably tomorrow.

**Comment by tigerhawkvok** [comment]
Solved by creating new models when needed, and loading and-resaving existing modesl with `saved_model.simple_save`


```python
#!python3
"""
Assumes we've defined:

- A directory for our working files to live in, CONTAINER_DIR
- an arbitrary integer VERSION_INT
- We have established local and S3 paths for our model and their labels as variables
"""

# Create a versioned path for the models to live in
# See https://stackoverflow.com/a/54014480/1877527
modelVersionPath = os.path.join(CONTAINER_DIR, VERSION_INT)
if os.path.exists(modelVersionPath):
    shutil.rmtree(modelVersionPath)
os.mkdir(modelVersionPath)
import tensorflow as tf
def load_graph(model_file, returnElements= None):
    """
    Code from v1.6.0 of Tensorflow's label_image.py example
    """
    graph = tf.Graph()
    graph_def = tf.GraphDef()
    with open(model_file, "rb") as f:
        graph_def.ParseFromString(f.read())
    returns = None
    with graph.as_default():
        returns = tf.import_graph_def(graph_def, return_elements= returnElements)
    if returnElements is None:
        return graph
    return graph, returns
# Set up dirs
exportDir = modelVersionPath
# Clean up any existing one
import shutil
if os.path.exists(exportDir):
    shutil.rmtree(exportDir)
# Add the serving metagraph tag
# We need the inputLayerName; in Inception we're feeding the resized tensor
# corresponding to resized_input_tensor_name
# May be able to get away with auto-determining this if not using Inception,
# but for Inception this is the 11th layer
inputLayerName = "Mul:0"
# Load the graph
if inputLayerName is None:
    graph = load_graph(modelPath)
    inputTensor = None
else:
    graph, returns = load_graph(modelPath, returnElements= [inputLayerName])
    inputTensor = returns[0]
with tf.Session(graph= graph) as sess:
    # Read the layers
    try:
        from tensorflow.compat.v1.saved_model import simple_save
    except (ModuleNotFoundError, ImportError):
        from tensorflow.saved_model import simple_save
    with graph.as_default():
        layers = [n.name for n in graph.as_graph_def().node]
        outName = layers.pop() + ":0"
        if inputLayerName is None:
            inputLayerName = layers.pop(0) + ":0"
    print("Checking outlayer", outName)
    outLayer = tf.get_default_graph().get_tensor_by_name(outName)
    if inputTensor is None:
        print("Checking inlayer", inputLayerName)
        inputTensor = tf.get_default_graph().get_tensor_by_name(inputLayerName)
    inputs = {
        inputLayerName: inputTensor
    }
    outputs = {
        outName: outLayer
    }
    simple_save(sess, exportDir, inputs, outputs)
print("Built a SavedModel")
```
