### ISSUE TITLE
SKLearn model fails to train: "HeadObject not found"

### ISSUE THREAD

**Issue by AlexUP** [aws/sagemaker-python-sdk#835]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: SKLearn
- **Framework Version**: Default
- **Python Version**: 3
- **CPU or GPU**: cpu
- **Python SDK Version**: Latest
- **Are you using a custom image**: No
- **Are you very very new to SageMaker**: Yes

### Describe the problem
Model training fails on local Windows machine with sagemaker api.

### Minimal repro / logs
Full console message:
```
PS C:\Users\AlexL\Documents\Projects\IMPI> python .\sagemaker_sklearn\sagemaker_calls.py
2019-06-06 10:05:26 Starting - Starting the training job...
2019-06-06 10:05:30 Starting - Launching requested ML instances...
2019-06-06 10:06:32 Starting - Preparing the instances for training...
2019-06-06 10:07:10 Downloading - Downloading input data
2019-06-06 10:07:10 Training - Downloading the training image...
2019-06-06 10:07:45 Uploading - Uploading generated training model
2019-06-06 10:07:45 Failed - Training job failed

?[31m2019-06-06 10:07:34,063 sagemaker-containers INFO     Imported framework sagemaker_sklearn_container.training?[0m
?[31m2019-06-06 10:07:34,066 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)?[0m
?[31m2019-06-06 10:07:34,087 sagemaker_sklearn_container.training INFO     Invoking user training script.?[0m
?[31m2019-06-06 10:07:34,314 sagemaker-containers ERROR    Reporting training FAILURE?[0m
?[31m2019-06-06 10:07:34,314 sagemaker-containers ERROR    framework error: ?[0m
?[31mTraceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_trainer.py", line 66, in train
    entrypoint()
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_sklearn_container/training.py", line 36, in main
    train(framework.training_env())
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_sklearn_container/training.py", line 32, in train
    training_environment.to_env_vars(), training_environment.module_name)
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_modules.py", line 276, in run_module
    _files.download_and_extract(uri, name, _env.code_dir)
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_files.py", line 125, in download_and_extract
    s3_download(uri, dst)
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_files.py", line 155, in s3_download
    s3.Bucket(bucket).download_file(key, dst)
  File "/usr/local/lib/python3.5/dist-packages/boto3/s3/inject.py", line 246, in bucket_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/usr/local/lib/python3.5/dist-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python3.5/dist-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/s3transfer/download.py", line 353, in _submit
    **transfer_future.meta.call_args.extra_args
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/botocore/client.py", line 624, in _make_api_call
    raise error_class(parsed_response, operation_name)?[0m
?[31mbotocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
?[0m
?[31mAn error occurred (404) when calling the HeadObject operation: Not Found?[0m
Traceback (most recent call last):
  File ".\sagemaker_sklearn\sagemaker_calls.py", line 34, in <module>
    sklearn.fit({'train': data_dir})
  File "C:\Users\AlexL\AppData\Roaming\Python\Python36\site-packages\sagemaker\estimator.py", line 236, in fit
    self.latest_training_job.wait(logs=logs)
  File "C:\Users\AlexL\AppData\Roaming\Python\Python36\site-packages\sagemaker\estimator.py", line 602, in wait
    self.sagemaker_session.logs_for_job(self.job_name, wait=True)
  File "C:\Users\AlexL\AppData\Roaming\Python\Python36\site-packages\sagemaker\session.py", line 1221, in logs_for_job
    self._check_job_status(job_name, description, 'TrainingJobStatus')
  File "C:\Users\AlexL\AppData\Roaming\Python\Python36\site-packages\sagemaker\session.py", line 917, in _check_job_status
    raise ValueError('Error for {} {}: {} Reason: {}'.format(job_type, job, status, reason))
ValueError: Error for Training job sagemaker-scikit-learn-2019-06-06-10-05-23-431: Failed Reason: AlgorithmError: framework error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_trainer.py", line 66, in train
    entrypoint()
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_sklearn_container/training.py", line 36, in main
    train(framework.training_env())
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_sklearn_container/training.py", line 32, in train
    training_environment.to_env_vars(), training_environment.module_name)
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_modules.py", line 276, in run_module
    _files.download_and_extract(uri, name, _env.code_dir)
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_files.py", line 125, in download_and_extract
    s3_download(uri, dst)
  File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_files.py", line 155, in s3_download
    s3.Bucket(bucket).download_file(key, dst)
  File "/usr/local/lib/python3.5/dist-packages/boto3/s3/inje
```
*Gets cut off*

- **Exact command to reproduce**:
```
sklearn = SKLearn(
    entry_point = some script.py,
    source_dir = full path to s3 bucket directory hosting entry_point scipt,
    train_instance_type = "ml.c4.xlarge",
    role = role with FullSageMakerAccess,
    py_version = "py3",
    hyperparameters = {
        'model_name': model_name
    }
)

sklearn.fit({'train': data_dir})
```

entry_point script essentially is the same as sciki_learn_iris.py (https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk/scikit_learn_iris), except using Adaboost.
data_dir contains the full path to s3 bucket directory hosting the dataset

**Comment by laurenyu** [comment]
hi @AlexUP, does the role you're using have permission to download objects from the S3 bucket where your entry script is?

**Comment by AlexUP** [comment]
Hi @laurenyu, 

Yes, I have also attached an S3FullAccess to the role, and made all files in the s3 bucket public.

**Comment by laurenyu** [comment]
are you using an S3 bucket that's not the default generated one? If so, can you specify `code_location` ([docs](https://sagemaker.readthedocs.io/en/stable/estimators.html#sagemaker.estimator.Framework)) in your `SKLearn` constructor?

**Comment by AlexUP** [comment]
I figured it out after a couple of guesses. The source_dir must point to a .tar.gz file in a s3 bucket and not just the directory itelf. Meaning the source scripts must be compressed before the sagemaker container can download the files and extract it. It would have been nice if the sagemaker-python-sdk documentation highlighted this: https://sagemaker.readthedocs.io/en/stable/using_sklearn.html#required-arguments

Thank you for your assistance.
