### ISSUE TITLE
PyTorch: increasing --shm-size to allow multiprocessing data loaders

### ISSUE THREAD

**Issue by ksanjeevan** [aws/sagemaker-python-sdk#937]
### System Information
- **Framework**: PyTorch
- **Framework Version**: 1.1.0
- **Python Version**:py3
- **CPU or GPU**: Both
- **Python SDK Version**: 1.32.0
- **Are you using a custom image**: Yes, N/A

### Describe the problem
When using  a data loader with multiprocessing in PyTorch (set `num_workers > 0`), the following error comes up:
```bash
algo-1-xxsq9_1  |   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 519, in _try_get_batch
algo-1-xxsq9_1  |     raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
algo-1-xxsq9_1  | RuntimeError: DataLoader worker (pid(s) 76) exited unexpectedly
tmpitprkm4o_algo-1-xxsq9_1 exited with code 1
```

This is because /dev/shm is at only 64M by default. The solution to this seems to be simply passing `--shm-size` with a higher value to `docker run` but if one is using `sagemaker` that option isn't there. 

I've extended the PyTorch container and added a bunch of custom packages and settings in the Dockerfile with no problem, but can't with runtime flags/args meant to be passed to `docker run` (Note: `docker build` has a `--shm-size` args but that is NOT related to the /dev/shm size of the final container).

This becomes a huge bottleneck since training is very slow with `num_workers = 0`. Can't we just increase the default shared memory? Or provide an easier way for users to set it using the sagemaker sdk?
 

- **Exact command to reproduce**:
Any example using [DataLoader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) with `num_workers > 0`.

**Comment by ChoiByungWook** [comment]
Hello @ksanjeevan,

Thanks for bringing this issue to our attention.

Let me reach out to the team that owns the training platform.

**Comment by ishaaq** [comment]
In fact docker containers running in SageMaker training do NOT use the 64MB default shm-size - we adjust it depending on the instance type.

You didn't mention the instance type you're using, which is it? And how much is the max shared memory is your algorithm meant to use?

**Comment by ksanjeevan** [comment]
Yeah this was using local mode, using remote seems to be fine.

**Comment by laurenyu** [comment]
thanks for the clarification! So it seems that we would need to find a way to expose shm-size as an option that would then get written into the docker-compose.yml file that is used for local mode. I'll open up an item in our internal backlog, which we're always reprioritizing based on feedback.

some potentially helpful links for anyone wanting to take a stab at this:
* [code where the yaml file is written](https://github.com/aws/sagemaker-python-sdk/blob/3739e5b5451107eefd8d6664b6ada905aee3086e/src/sagemaker/local/image.py#L404)
* [docker compose shm-size option](https://docs.docker.com/compose/compose-file) - note that this would also include upgrading [the version we use for the file](https://github.com/aws/sagemaker-python-sdk/blob/3739e5b5451107eefd8d6664b6ada905aee3086e/src/sagemaker/local/image.py#L447-L448)

**Comment by ksanjeevan** [comment]
Hi @laurenyu, yes thanks! In an ideal world, we could pass some kind of `run_hyperparameters` dictionary so that we can add any flag for `docker run`, but having `shm-size` is good enough.

**Comment by bill10** [comment]
just wondering if this issue is resolved. This feature will really make debugging much easier.

**Comment by austinmw** [comment]
Also experiencing this issue trying to use >1 worker and/or a reasonably large batch size with an mxnet gluoncv object detection script in local mode.

**Comment by VladVin** [comment]
Any updates? The feature would be usefull indeed for debugging locally

**Comment by VladVin** [comment]
As a workaround I found the solution to change default parameters of a Docker daemon. May be suitable for those who have rights to change them:
1. Open this file in your editor:
```
sudo vim /etc/docker/daemon.json
```
2. Add option `"default-shm-size": "13G"` as mentioned in the [Docker docs](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file). You can specify another value, I have just set 13Gb as I have 16Gb of RAM on my server.
3. Restart Docker daemon:
```
sudo systemctl restart docker
```

**Comment by ivan-saptech** [comment]
> As a workaround I found a solution to change the default parameters of the Docker daemon. May be suitable for those who have rights to change them:
> 
> 1. Open this file in your editor:
> 
> ```
> sudo vim /etc/docker/daemon.json
> ```
> 
> 1. Add option `"default-shm-size": "13G"` as mentioned in the [Docker docs](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file). You can specify another value, I just set 13Gb as I have 16Gb of RAM on my server.
> 2. Restart Docker daemon:
> 
> ```
> sudo systemctl restart docker
> ```

Thanks! This is the only valid solution to this issue in my case. Finally found your solution after a few hours of searching.

**Comment by arulbharathi** [comment]
> > As a workaround I found a solution to change the default parameters of the Docker daemon. May be suitable for those who have rights to change them:
> > 
> > 1. Open this file in your editor:
> > 
> > ```
> > sudo vim /etc/docker/daemon.json
> > ```
> > 
> > 
> > 
> > 1. Add option `"default-shm-size": "13G"` as mentioned in the [Docker docs](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file). You can specify another value, I just set 13Gb as I have 16Gb of RAM on my server.
> > 2. Restart Docker daemon:
> > 
> > ```
> > sudo systemctl restart docker
> > ```
> 
> Thanks! This is the only valid solution to this issue in my case. Finally found your solution after a few hours of searching.

@ivan-saptech will we able to deploy the same into sagemaker and the sagemaker endpoint will get the same shm-size configuration?

CC - @VladVin

**Comment by lou-k** [comment]
This is happening in sagemaker studio as well. Is there a way to adjust the studio settings?

**Comment by jacquesboitreaud** [comment]
This is also a bottleneck in the sagemaker processing jobs, where we cannot pass arguments to the `docker run` command. Any way to fix this ?

**Comment by bertocast** [comment]
Any updates on this?

**Comment by lou-k** [comment]
I've raised the issue to the sagemaker studio team nearly a year ago, but they have not taken any action.

**Comment by titanium-cranium** [comment]
Impossible to train popular YOLOv5 models in studio with such low shared memory (64M).  Launching a single Notebook instance makes it possible as shared memory on the instance I spun up was 32G (ml.g4dn.4xlarge).  If your premier service of Studio is less capable than the older Notebooks this should be called out and or prioritised.  I spent quite some time trying to work out how I could use Studio before I found this post and simply dumped it in favour of a Notebook.

**Comment by knikure** [comment]
Thank you for reaching out! The latest SageMaker Studio release now offers increased shared memory on instances running Studio Apps. The memory size scales in proportion to the size of the instance being used. Please update your Studio Apps as described [here](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-tasks-update-apps.html), to see these improvements.

**Comment by Ajay-Reva** [comment]
What do I do when I run from the notebook? Because I'm facing the same issue with my processing job when running from the notebook.

**Comment by Ajay-Reva** [comment]
I'm running this on AWS studio with a notebook and my own processing container.  


```
#000Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 808, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/opt/conda/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 193) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 388, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1003, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 960, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 821, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 193) exited unexpectedly
```

**Comment by thvasilo** [comment]
Hello, is it possible to set the size of `/dev/shm` now for SageMaker training jobs? We're running into the same issue.

**Comment by ntw-au** [comment]
> Hello, is it possible to set the size of `/dev/shm` now for SageMaker training jobs? We're running into the same issue.

I'm also keen to have either higher or configurable shared memory limits. We are using SageMaker Training with PyTorch in a custom container and use shared memory to cache the whole dataset and therefore avoid returning to S3 every epoch. This works on `ml.p4d.24xlarge` but not `ml.g5.48xlarge`, where the process runs out of shared memory. I really want to have the _whole_ of system RAM available for caching, like I would when running outside a container.

**Comment by gui-miotto** [comment]
I solved my shared memory issues by setting `pin_memory` to `True` in **all** [dataloaders](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) (train, valid, test, etc.)
